import type { Lesson } from '@/types/lesson'

export const cssSelectors: Lesson = {
  slug: 'css-selectors',
  category: 'CSS',
  readTime: 10,
  icon: '🎯',
  title_ru: 'CSS-селекторы',
  title_en: 'CSS Selectors',
  description_ru: 'Научитесь точно выбирать HTML-элементы с помощью тегов, классов, идентификаторов и псевдоклассов.',
  description_en: 'Learn to precisely target HTML elements using tags, classes, IDs, and pseudo-classes.',
  sections: [
    { id: 'intro', title_ru: 'Что такое селектор', title_en: 'What is a Selector' },
    { id: 'basic', title_ru: 'Базовые селекторы', title_en: 'Basic Selectors' },
    { id: 'combinators', title_ru: 'Комбинаторы', title_en: 'Combinators' },
    { id: 'pseudo', title_ru: 'Псевдоклассы и псевдоэлементы', title_en: 'Pseudo-classes & Pseudo-elements' },
    { id: 'specificity', title_ru: 'Специфичность', title_en: 'Specificity' },
  ],
  slides: [
    {
      id: 'slide-1',
      type: 'title',
      title_ru: 'CSS-селекторы',
      title_en: 'CSS Selectors',
      body_ru: 'Селекторы — это шаблоны, которые указывают браузеру, к каким элементам применять стили. Освойте их — и вы получите полный контроль над внешним видом страницы.',
      body_en: 'Selectors are patterns that tell the browser which elements to style. Master them and you gain complete control over the look of any page.',
      visual: { kind: 'emoji', emojis: ['🎯', '🖥️', '✨'], caption_ru: 'Точное попадание в нужный элемент', caption_en: 'Pinpointing exactly the right element' },
    },
    {
      id: 'slide-2',
      type: 'analogy',
      title_ru: 'Аналогия: адрес доставки',
      title_en: 'Analogy: Delivery Address',
      body_ru: 'Представьте CSS как курьерскую службу. Селектор — это адрес на посылке. Чем точнее адрес (город → улица → дом → квартира), тем конкретнее получатель. Так же и с селекторами: от общего тега до уникального ID.',
      body_en: 'Think of CSS as a courier service. The selector is the address on the package. The more specific the address (city → street → house → flat), the more precise the recipient. Selectors work the same way: from a broad tag to a unique ID.',
      visual: { kind: 'emoji', emojis: ['📦', '🏠', '📍'], caption_ru: 'От города до квартиры — от тега до ID', caption_en: 'From city to flat — from tag to ID' },
    },
    {
      id: 'slide-3',
      type: 'concept',
      title_ru: 'Базовые селекторы',
      title_en: 'Basic Selectors',
      body_ru: 'Три кита CSS-селекторов: тег, класс и ID.',
      body_en: 'The three pillars of CSS selectors: tag, class, and ID.',
      bullets: [
        { text_ru: 'Тег: `p { }` — все абзацы на странице', text_en: 'Tag: `p { }` — every paragraph on the page' },
        { text_ru: 'Класс: `.card { }` — элементы с `class="card"`', text_en: 'Class: `.card { }` — elements with `class="card"`' },
        { text_ru: 'ID: `#title { }` — единственный элемент с `id="title"`', text_en: 'ID: `#title { }` — the one element with `id="title"`' },
      ],
    },
    {
      id: 'slide-4',
      type: 'code-anim',
      title_ru: 'От общего к конкретному',
      title_en: 'From General to Specific',
      body_ru: 'Наблюдайте, как селекторы становятся всё точнее — от тега до псевдокласса.',
      body_en: 'Watch selectors grow more precise — from tag to pseudo-class.',
      codeLang: 'css',
      animMode: 'preview',
      animSteps: [
        {
          code: 'p {\n  color: gray;\n}',
          comment_ru: 'Тег-селектор: стилизует все <p> на странице',
          comment_en: 'Tag selector: styles every <p> on the page',
          preview: '<p style="color:gray">Все абзацы становятся серыми / All paragraphs turn gray</p>',
        },
        {
          code: 'p {\n  color: gray;\n}\n\n.card {\n  background: #f0f4ff;\n  padding: 16px;\n  border-radius: 8px;\n}',
          comment_ru: 'Класс: стилизует только элементы с class="card"',
          comment_en: 'Class: styles only elements with class="card"',
          preview: '<div style="background:#f0f4ff;padding:16px;border-radius:8px"><p style="color:gray">Карточка / Card</p></div>',
        },
        {
          code: 'p {\n  color: gray;\n}\n\n.card {\n  background: #f0f4ff;\n  padding: 16px;\n  border-radius: 8px;\n}\n\n#title {\n  font-size: 2rem;\n  font-weight: bold;\n  color: #1c7ed6;\n}',
          comment_ru: 'ID: один уникальный заголовок получает особые стили',
          comment_en: 'ID: one unique heading gets special styles',
          preview: '<h1 style="font-size:2rem;font-weight:bold;color:#1c7ed6" id="title">Уникальный заголовок / Unique Heading</h1>',
        },
        {
          code: 'p {\n  color: gray;\n}\n\n.card {\n  background: #f0f4ff;\n  padding: 16px;\n  border-radius: 8px;\n}\n\n#title {\n  font-size: 2rem;\n  font-weight: bold;\n  color: #1c7ed6;\n}\n\n.card:hover {\n  box-shadow: 0 4px 12px rgba(0,0,0,0.15);\n  transform: translateY(-2px);\n}',
          comment_ru: 'Псевдокласс :hover — интерактивное состояние при наведении',
          comment_en: 'Pseudo-class :hover — interactive state on mouse-over',
          preview: '<div style="background:#f0f4ff;padding:16px;border-radius:8px;box-shadow:0 4px 12px rgba(0,0,0,0.15);transform:translateY(-2px)">Наведите курсор / Hover me</div>',
        },
      ],
    },
    {
      id: 'slide-5',
      type: 'concept',
      title_ru: 'Комбинаторы',
      title_en: 'Combinators',
      body_ru: 'Комбинаторы описывают связи между элементами в дереве HTML.',
      body_en: 'Combinators describe relationships between elements in the HTML tree.',
      bullets: [
        { text_ru: '`div p` — потомок: все `<p>` внутри любого `<div>`', text_en: '`div p` — descendant: all `<p>` inside any `<div>`' },
        { text_ru: '`ul > li` — прямой потомок: только `<li>` непосредственно в `<ul>`', text_en: '`ul > li` — direct child: only `<li>` immediately inside `<ul>`' },
        { text_ru: '`h2 + p` — соседний: первый `<p>` сразу после `<h2>`', text_en: '`h2 + p` — adjacent sibling: first `<p>` right after `<h2>`' },
      ],
      code: 'nav > ul > li { list-style: none; }\nnav a:hover { text-decoration: underline; }',
      codeLang: 'css',
    },
    {
      id: 'slide-6',
      type: 'code',
      title_ru: 'Псевдоэлементы ::before и ::after',
      title_en: 'Pseudo-elements ::before and ::after',
      body_ru: '`::before` и `::after` вставляют виртуальный контент до или после содержимого элемента — без изменения HTML.',
      body_en: '`::before` and `::after` inject virtual content before or after an element\'s content — without touching the HTML.',
      code: '.badge::before {\n  content: "★ ";\n  color: gold;\n}\n\n.tooltip::after {\n  content: attr(data-tip);\n  position: absolute;\n  background: #333;\n  color: #fff;\n  padding: 4px 8px;\n  border-radius: 4px;\n  font-size: 0.75rem;\n}',
      codeLang: 'css',
    },
    {
      id: 'slide-7',
      type: 'compare',
      title_ru: 'Класс vs ID',
      title_en: 'Class vs ID',
      body_ru: 'Когда использовать `.class`, а когда `#id`?',
      body_en: 'When should you use `.class` vs `#id`?',
      compareLeft: {
        label_ru: '.class — многоразовый',
        label_en: '.class — reusable',
        items_ru: ['Можно применять к нескольким элементам', 'Идеально для повторяющихся компонентов', 'Специфичность: 0-1-0', 'Пример: .btn, .card, .tag'],
        items_en: ['Can be applied to many elements', 'Perfect for repeating components', 'Specificity: 0-1-0', 'Example: .btn, .card, .tag'],
        color: 'blue',
      },
      compareRight: {
        label_ru: '#id — уникальный',
        label_en: '#id — unique',
        items_ru: ['Только один элемент на страницу', 'Для якорей и уникальных секций', 'Специфичность: 1-0-0', 'Пример: #header, #main, #footer'],
        items_en: ['Only one element per page', 'For anchors and unique sections', 'Specificity: 1-0-0', 'Example: #header, #main, #footer'],
        color: 'amber',
      },
    },
    {
      id: 'slide-8',
      type: 'tip',
      title_ru: 'Совет: держите специфичность низкой',
      title_en: 'Tip: Keep Specificity Low',
      body_ru: 'Избегайте цепочек вроде `div#sidebar .menu > li a`. Чем проще селектор — тем легче поддерживать стили. Предпочитайте классы тегам и ID, используйте методологию БЭМ для предсказуемого именования.',
      body_en: 'Avoid chains like `div#sidebar .menu > li a`. The simpler the selector, the easier the styles are to maintain. Prefer classes over tags and IDs, and use BEM naming for predictable selectors.',
      visual: { kind: 'emoji', emojis: ['⚡', '🧹'], caption_ru: 'Чистые селекторы — чистый код', caption_en: 'Clean selectors — clean code' },
    },
    {
      id: 'slide-9',
      type: 'practice-cta',
      title_ru: 'Время практиковаться!',
      title_en: 'Time to Practice!',
      body_ru: 'Создайте карточку товара, используя разные типы селекторов: тег, класс, псевдокласс :hover и псевдоэлемент ::before.',
      body_en: 'Build a product card using different selector types: tag, class, :hover pseudo-class, and ::before pseudo-element.',
      visual: { kind: 'emoji', emojis: ['💻', '🎯'], caption_ru: 'Откройте редактор и попробуйте сами', caption_en: 'Open the editor and try it yourself' },
    },
  ],
  content: {
    intro_ru: 'CSS-селекторы — это сердце каскадных таблиц стилей. Без умения выбирать нужные элементы невозможно создать сложный и поддерживаемый интерфейс. В этом уроке вы освоите полный арсенал: от простых тегов до специфичных псевдоэлементов.',
    intro_en: 'CSS selectors are the heart of cascading style sheets. Without the ability to target the right elements, building a complex and maintainable UI is impossible. In this lesson you will master the full arsenal: from simple tags to specific pseudo-elements.',
    blocks: [
      {
        sectionId: 'intro',
        heading_ru: 'Что такое селектор',
        heading_en: 'What is a Selector',
        text_ru: 'Селектор — это шаблон, который CSS использует для поиска нужных HTML-элементов и применения к ним стилей. Перед фигурными скобками с объявлениями всегда стоит селектор. Он определяет, какие именно элементы на странице получат заданные свойства — цвет, отступ, шрифт или что-то ещё.\n\nОт выбора правильного селектора зависит, насколько точно и предсказуемо будут применяться стили. Слишком широкий селектор (например, тег `p`) затронет все абзацы — что может быть и задумано, и нежелательно. Слишком конкретный превратит CSS в нечитаемую цепочку вложенностей. Хорошие CSS-практики строятся на балансе между точностью и простотой.\n\nСелекторы — это не только теги, классы и идентификаторы. CSS предоставляет мощный набор инструментов: атрибутные селекторы, псевдоклассы состояний, псевдоэлементы и комбинаторы для описания структурных связей. Освоив их, вы сможете прицельно стилизовать любой элемент страницы.',
        text_en: 'A selector is a pattern that CSS uses to find the right HTML elements and apply styles to them. Every CSS rule has a selector before the curly braces. It determines exactly which elements on the page receive the declared properties — color, spacing, font, or anything else.\n\nChoosing the right selector determines how precisely and predictably styles are applied. A selector that is too broad (such as the tag `p`) will target all paragraphs — which may or may not be the intention. One that is too specific turns CSS into an unreadable chain of nested qualifiers. Good CSS practice is built on the balance between precision and simplicity.\n\nSelectors are not limited to tags, classes, and IDs. CSS offers a powerful toolkit: attribute selectors, state pseudo-classes, pseudo-elements, and combinators for describing structural relationships. Once you have mastered them, you can pinpoint any element on a page.',
        code: '/* The anatomy of a CSS rule */\n\n/* selector  */   /* declaration block */\n.card         {   background: white; padding: 16px; }\n\n/* selector      property   value  */\nh1           {   color:     #1a1a2e; }\n\n/* Multiple selectors share one block */\nh1, h2, h3 {\n  font-weight: 700;\n  line-height: 1.2;\n}',
        codeLang: 'css',
      },
      {
        sectionId: 'basic',
        heading_ru: 'Тег, класс и ID',
        heading_en: 'Tag, Class, and ID',
        text_ru: 'Тег-селектор (`p`, `h1`, `div`) применяется ко всем элементам данного типа — удобно для базовых стилей. Класс (`.имя`) — основной инструмент: он многоразовый и имеет умеренную специфичность. ID (`#имя`) уникален на странице, поэтому его лучше оставить для якорей и JavaScript-хуков.',
        text_en: 'A tag selector (`p`, `h1`, `div`) targets every element of that type — handy for baseline styles. A class (`.name`) is the workhorse: reusable and moderately specific. An ID (`#name`) is unique per page, so it is best reserved for anchor links and JavaScript hooks.',
        code: '/* Tag */\np { margin-bottom: 1rem; }\n\n/* Class */\n.btn {\n  display: inline-block;\n  padding: 8px 16px;\n  border-radius: 6px;\n}\n\n/* ID */\n#main-nav { position: sticky; top: 0; }',
        codeLang: 'css',
      },
      {
        sectionId: 'combinators',
        heading_ru: 'Потомки и дети',
        heading_en: 'Descendants and Children',
        text_ru: 'Пробел между селекторами означает «любой потомок», символ `>` — только прямой дочерний элемент. Используйте `>` осознанно: он защищает от нечаянного попадания во вложенные структуры.',
        text_en: 'A space between selectors means "any descendant", while `>` means only a direct child. Use `>` intentionally: it guards against accidentally reaching into nested structures.',
        code: '/* All <a> anywhere inside .nav */\n.nav a { color: inherit; }\n\n/* Only direct <li> of <ul> */\nul > li { padding: 4px 0; }',
        codeLang: 'css',
      },
      {
        sectionId: 'pseudo',
        heading_ru: 'Псевдоклассы и псевдоэлементы',
        heading_en: 'Pseudo-classes and Pseudo-elements',
        text_ru: 'Псевдоклассы описывают состояние элемента (`:hover`, `:focus`, `:first-child`, `:nth-child(n)`). Псевдоэлементы (`::before`, `::after`, `::placeholder`) создают виртуальные части элемента. Запомните: псевдоклассы — одно двоеточие, псевдоэлементы — два.',
        text_en: 'Pseudo-classes describe an element\'s state (`:hover`, `:focus`, `:first-child`, `:nth-child(n)`). Pseudo-elements (`::before`, `::after`, `::placeholder`) create virtual parts of the element. Remember: pseudo-classes use one colon, pseudo-elements use two.',
        code: 'li:first-child { font-weight: bold; }\nli:nth-child(even) { background: #f9f9f9; }\ninput:focus { outline: 2px solid #4dabf7; }\n\n.quote::before { content: "\\201C"; }\n.quote::after  { content: "\\201D"; }',
        codeLang: 'css',
      },
      {
        sectionId: 'specificity',
        heading_ru: 'Специфичность (Specificity)',
        heading_en: 'Specificity',
        text_ru: 'Когда несколько правил претендуют на один элемент, побеждает более специфичное. Считайте очки по формуле (ID, классы/псевдоклассы/атрибуты, теги/псевдоэлементы): ID даёт 1-0-0, класс — 0-1-0, тег — 0-0-1. `!important` переопределяет всё, но используйте его в крайнем случае.',
        text_en: 'When multiple rules target the same element, the most specific one wins. Count points as (ID, class/pseudo-class/attribute, tag/pseudo-element): an ID scores 1-0-0, a class 0-1-0, a tag 0-0-1. `!important` overrides everything, but use it as a last resort.',
        code: '/* Specificity: 0-0-1 */\np { color: black; }\n\n/* Specificity: 0-1-0 — wins */\n.intro { color: navy; }\n\n/* Specificity: 1-0-0 — wins over class */\n#hero { color: crimson; }',
        codeLang: 'css',
      },
    ],
  },
  editorTask: {
    title_ru: 'Карточка товара',
    title_en: 'Product Card',
    instructions_ru: 'Создайте карточку товара. Используйте тег-селектор для `h2` и `p`, класс `.card` для контейнера, `.card:hover` для тени, а `::before` — чтобы добавить перед ценой символ «₸».',
    instructions_en: 'Build a product card. Use a tag selector for `h2` and `p`, the class `.card` for the container, `.card:hover` for a shadow, and `::before` to prepend a "₸" symbol before the price.',
    activeTabs: ['html', 'css'],
    starterCode: {
      html: '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <title>Product Card</title>\n  <link rel="stylesheet" href="style.css">\n</head>\n<body>\n  <div class="card">\n    <h2>Wireless Headphones</h2>\n    <p class="desc">Premium sound, 30-hour battery life.</p>\n    <p class="price">4500</p>\n    <button class="btn">Add to Cart</button>\n  </div>\n</body>\n</html>',
      css: '/* Style the card container */\n.card {\n  \n}\n\n/* Style headings and paragraphs */\nh2 {\n  \n}\n\n/* Hover state */\n.card:hover {\n  \n}\n\n/* Add currency symbol before price */\n.price::before {\n  content: "";\n}\n\n/* Style the button */\n.btn {\n  \n}',
    },
    hints_ru: [
      'Попробуйте `border-radius: 12px` и `box-shadow` для карточки',
      'Для hover-эффекта: `transition: box-shadow 0.2s ease`',
      '`.price::before { content: "₸ "; }`',
      'Используйте `cursor: pointer` для кнопки',
    ],
    hints_en: [
      'Try `border-radius: 12px` and `box-shadow` for the card',
      'For the hover effect: `transition: box-shadow 0.2s ease`',
      '`.price::before { content: "₸ "; }`',
      'Use `cursor: pointer` on the button',
    ],
  },
  keyTerms: [
    {
      term_ru: 'Селектор',
      term_en: 'Selector',
      definition_ru: 'Шаблон CSS, указывающий, к каким HTML-элементам применить правила стилей.',
      definition_en: 'A CSS pattern that specifies which HTML elements a set of style rules applies to.',
      example_ru: '`.card` выбирает все элементы с классом "card"',
      example_en: '`.card` targets every element with the class "card"',
    },
    {
      term_ru: 'Специфичность',
      term_en: 'Specificity',
      definition_ru: 'Числовое значение, определяющее, какое CSS-правило имеет приоритет при конфликте.',
      definition_en: 'A numeric weight that determines which CSS rule takes priority when rules conflict.',
      example_ru: '`#id` (1-0-0) побеждает `.class` (0-1-0)',
      example_en: '`#id` (1-0-0) beats `.class` (0-1-0)',
    },
    {
      term_ru: 'Псевдокласс',
      term_en: 'Pseudo-class',
      definition_ru: 'Ключевое слово с одним двоеточием, стилизующее элемент в определённом состоянии.',
      definition_en: 'A keyword with one colon that styles an element in a particular state.',
      example_ru: '`a:hover` — ссылка при наведении курсора',
      example_en: '`a:hover` — a link when the cursor hovers over it',
    },
    {
      term_ru: 'Псевдоэлемент',
      term_en: 'Pseudo-element',
      definition_ru: 'Ключевое слово с двумя двоеточиями, создающее виртуальную часть элемента.',
      definition_en: 'A keyword with two colons that creates a virtual part of an element.',
      example_ru: '`p::first-line` стилизует первую строку абзаца',
      example_en: '`p::first-line` styles the first line of a paragraph',
    },
    {
      term_ru: 'Комбинатор',
      term_en: 'Combinator',
      definition_ru: 'Символ между двумя селекторами, описывающий структурную связь между элементами.',
      definition_en: 'A symbol between two selectors that describes the structural relationship between elements.',
      example_ru: '`ul > li` — прямой дочерний комбинатор',
      example_en: '`ul > li` — child combinator',
    },
  ],
  didYouKnow: [
    {
      text_ru: 'Селектор `*` (универсальный) выбирает абсолютно все элементы на странице. Его часто используют для сброса `box-sizing: border-box` сразу у всех элементов.',
      text_en: 'The `*` (universal) selector matches every single element on the page. It is commonly used to reset `box-sizing: border-box` for all elements at once.',
    },
    {
      text_ru: 'CSS-селекторы читаются браузером справа налево. Правило `.nav a` сначала находит все `<a>`, а затем проверяет, есть ли среди предков элемент с классом `.nav`. Это важно для оптимизации производительности.',
      text_en: 'CSS selectors are evaluated by the browser right to left. The rule `.nav a` first finds all `<a>` elements, then checks if any ancestor has the class `.nav`. This matters for performance optimisation.',
    },
  ],
  quiz: [
    {
      id: 'q1',
      text_ru: 'Какой селектор выбирает только прямых дочерних `<li>` элемента `<ul>`?',
      text_en: 'Which selector targets only direct child `<li>` elements of a `<ul>`?',
      options_ru: ['ul li', 'ul + li', 'ul > li', 'ul ~ li'],
      options_en: ['ul li', 'ul + li', 'ul > li', 'ul ~ li'],
      correctIndex: 2,
      explanation_ru: '`ul > li` — комбинатор прямого потомка (`>`). `ul li` выбрал бы все `<li>` на любой глубине вложенности.',
      explanation_en: '`ul > li` uses the child combinator (`>`). `ul li` would select all `<li>` elements at any nesting depth.',
    },
    {
      id: 'q2',
      text_ru: 'Какова специфичность селектора `#header .nav a`?',
      text_en: 'What is the specificity of the selector `#header .nav a`?',
      options_ru: ['0-2-1', '1-1-1', '1-1-0', '2-1-0'],
      options_en: ['0-2-1', '1-1-1', '1-1-0', '2-1-0'],
      correctIndex: 1,
      explanation_ru: '`#header` даёт 1-0-0, `.nav` даёт 0-1-0, `a` даёт 0-0-1. Итого: 1-1-1.',
      explanation_en: '`#header` contributes 1-0-0, `.nav` contributes 0-1-0, `a` contributes 0-0-1. Total: 1-1-1.',
    },
    {
      id: 'q3',
      text_ru: 'Какой синтаксис правильный для псевдоэлемента?',
      text_en: 'Which syntax is correct for a pseudo-element?',
      options_ru: ['p:before', 'p::before', 'p#before', 'p.before'],
      options_en: ['p:before', 'p::before', 'p#before', 'p.before'],
      correctIndex: 1,
      explanation_ru: 'Псевдоэлементы используют двойное двоеточие `::`. Одинарное `:before` работает в старых браузерах, но `::before` — стандарт CSS3.',
      explanation_en: 'Pseudo-elements use a double colon `::`. Single `:before` works in older browsers but `::before` is the CSS3 standard.',
    },
    {
      id: 'q4',
      text_ru: 'Что выберет селектор `p:first-child`?',
      text_en: 'What does the selector `p:first-child` target?',
      options_ru: ['Первый дочерний элемент любого `<p>`', 'Любой `<p>`, который является первым дочерним элементом своего родителя', 'Первую букву любого `<p>`', 'Первую строку любого `<p>`'],
      options_en: ['The first child element of any `<p>`', 'Any `<p>` that is the first child of its parent', 'The first letter of any `<p>`', 'The first line of any `<p>`'],
      correctIndex: 1,
      explanation_ru: '`:first-child` выбирает элемент, если он является первым дочерним элементом своего родителя. Тег `p` уточняет, что это должен быть именно `<p>`.',
      explanation_en: '`:first-child` selects an element if it is the first child of its parent. The `p` type qualifier means it must also be a `<p>` element.',
    },
    {
      id: 'q5',
      text_ru: 'Почему рекомендуется предпочитать классы ID в CSS?',
      text_en: 'Why is it recommended to prefer classes over IDs in CSS?',
      options_ru: ['Классы быстрее парсятся браузером', 'Классы можно использовать повторно и имеют меньшую специфичность', 'ID не поддерживают псевдоклассы', 'Классы поддерживают больше свойств CSS'],
      options_en: ['Classes are parsed faster by the browser', 'Classes are reusable and have lower specificity', 'IDs do not support pseudo-classes', 'Classes support more CSS properties'],
      correctIndex: 1,
      explanation_ru: 'Классы многоразовые (можно применять к нескольким элементам) и имеют меньшую специфичность (0-1-0 против 1-0-0), что упрощает переопределение стилей.',
      explanation_en: 'Classes are reusable (applicable to multiple elements) and have lower specificity (0-1-0 vs 1-0-0), making it easier to override styles when needed.',
    },
  ],
}
