import type { Lesson } from '@/types/lesson'

export const cssPositioning: Lesson = {
  slug: 'css-positioning',
  category: 'CSS',
  readTime: 11,
  icon: '📍',
  title_ru: 'Позиционирование в CSS',
  title_en: 'CSS Positioning',
  description_ru: 'Освойте все виды позиционирования CSS: static, relative, absolute, fixed и sticky — с пониманием потока документа и z-index.',
  description_en: 'Master all CSS position types: static, relative, absolute, fixed, and sticky — with a solid understanding of document flow and z-index.',
  sections: [
    { id: 'intro', title_ru: 'Поток документа', title_en: 'Document Flow' },
    { id: 'relative', title_ru: 'Relative и Absolute', title_en: 'Relative & Absolute' },
    { id: 'fixed-sticky', title_ru: 'Fixed и Sticky', title_en: 'Fixed & Sticky' },
    { id: 'offsets', title_ru: 'Смещения и z-index', title_en: 'Offsets & z-index' },
    { id: 'patterns', title_ru: 'Типовые паттерны', title_en: 'Common Patterns' },
  ],
  slides: [
    {
      id: 'slide-1',
      type: 'title',
      title_ru: 'Позиционирование в CSS',
      title_en: 'CSS Positioning',
      body_ru: 'Свойство `position` определяет, как элемент размещается в документе. Освоив пять значений — `static`, `relative`, `absolute`, `fixed`, `sticky` — вы сможете создавать любые UI-паттерны: от прилипающих шапок до всплывающих подсказок.',
      body_en: 'The `position` property defines how an element is placed in the document. Master five values — `static`, `relative`, `absolute`, `fixed`, `sticky` — and you can build any UI pattern: from sticky headers to tooltips.',
      visual: { kind: 'emoji', emojis: ['📍', '🗺️', '🧭'], caption_ru: 'Знать своё место в документе', caption_en: 'Knowing your place in the document' },
    },
    {
      id: 'slide-2',
      type: 'analogy',
      title_ru: 'Аналогия: стикеры на доске',
      title_en: 'Analogy: Sticky Notes on a Board',
      body_ru: '`static` — обычная заметка в строке текста. `relative` — заметка, слегка смещённая, но занимающая своё исходное место. `absolute` — наклейка, прикреплённая к конкретному углу доски. `fixed` — наклейка на стекло поверх доски: не двигается при прокрутке. `sticky` — магнит: едет вместе с доской, но «прилипает» к краю при достижении нужной позиции.',
      body_en: '`static` is a normal note in line with the text. `relative` is a note nudged slightly, but still holding its original spot. `absolute` is a sticker pinned to a specific corner of the board. `fixed` is a sticker on the glass in front of the board: it never scrolls. `sticky` is a magnet: it travels with the board but "sticks" to the edge when it reaches a set position.',
      visual: { kind: 'emoji', emojis: ['📝', '📌', '🪟'], caption_ru: 'Пять характеров, пять способов располагаться', caption_en: 'Five personalities, five ways to sit' },
    },
    {
      id: 'slide-3',
      type: 'concept',
      title_ru: 'Пять значений position',
      title_en: 'Five Values of position',
      body_ru: 'Каждое значение по-своему взаимодействует с потоком документа.',
      body_en: 'Each value interacts with the document flow differently.',
      bullets: [
        { text_ru: '`static` (по умолчанию) — элемент в нормальном потоке, смещения (`top`, `left`) игнорируются', text_en: '`static` (default) — element in normal flow; offsets (`top`, `left`) are ignored' },
        { text_ru: '`relative` — элемент в потоке, смещается визуально, место сохраняется', text_en: '`relative` — element stays in flow, visually offset; original space is preserved' },
        { text_ru: '`absolute` — выходит из потока, позиционируется относительно ближайшего не-static предка', text_en: '`absolute` — removed from flow, positioned relative to the nearest non-static ancestor' },
        { text_ru: '`fixed` — выходит из потока, позиционируется относительно вьюпорта', text_en: '`fixed` — removed from flow, positioned relative to the viewport' },
        { text_ru: '`sticky` — гибрид: `relative` до достижения порога, затем `fixed`', text_en: '`sticky` — hybrid: `relative` until the threshold, then `fixed`' },
      ],
    },
    {
      id: 'slide-4',
      type: 'code-anim',
      title_ru: 'Sticky-шапка шаг за шагом',
      title_en: 'Building a Sticky Header Step by Step',
      body_ru: 'Создадим классическую прилипающую шапку сайта.',
      body_en: 'Let\'s build a classic sticky site header.',
      codeLang: 'css',
      animMode: 'preview',
      animSteps: [
        {
          code: 'header {\n  background: #1c7ed6;\n  color: white;\n  padding: 16px 24px;\n}',
          comment_ru: 'Базовая шапка в нормальном потоке (position: static)',
          comment_en: 'Basic header in normal flow (position: static)',
          preview: '<header style="background:#1c7ed6;color:white;padding:16px 24px;font-family:sans-serif">My Website</header><div style="padding:16px;font-family:sans-serif">Page content scrolls here...</div>',
        },
        {
          code: 'header {\n  background: #1c7ed6;\n  color: white;\n  padding: 16px 24px;\n  position: sticky;\n  top: 0;\n}',
          comment_ru: 'position: sticky + top: 0 — шапка прилипает при прокрутке',
          comment_en: 'position: sticky + top: 0 — header sticks when scrolling',
          preview: '<div style="height:120px;overflow-y:auto;font-family:sans-serif"><header style="background:#1c7ed6;color:white;padding:16px 24px;position:sticky;top:0">My Website (sticky)</header><div style="padding:16px">Scroll me down... more content... more content...</div></div>',
        },
        {
          code: 'header {\n  background: #1c7ed6;\n  color: white;\n  padding: 16px 24px;\n  position: sticky;\n  top: 0;\n  z-index: 100;\n  box-shadow: 0 2px 8px rgba(0,0,0,0.2);\n}',
          comment_ru: 'z-index: 100 — шапка поверх всего; тень подчёркивает прилипание',
          comment_en: 'z-index: 100 — header above everything; shadow emphasises sticking',
          preview: '<div style="height:120px;overflow-y:auto;font-family:sans-serif"><header style="background:#1c7ed6;color:white;padding:16px 24px;position:sticky;top:0;z-index:100;box-shadow:0 2px 8px rgba(0,0,0,0.2)">My Website (sticky + shadow)</header><div style="padding:16px">Scroll me down... more content... more content...</div></div>',
        },
        {
          code: 'header {\n  background: #1c7ed6;\n  color: white;\n  padding: 16px 24px;\n  position: sticky;\n  top: 0;\n  z-index: 100;\n  box-shadow: 0 2px 8px rgba(0,0,0,0.2);\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n}',
          comment_ru: 'Добавляем Flexbox для внутренней компоновки (логотип слева, меню справа)',
          comment_en: 'Add Flexbox for internal layout (logo left, nav right)',
          preview: '<div style="height:120px;overflow-y:auto;font-family:sans-serif"><header style="background:#1c7ed6;color:white;padding:16px 24px;position:sticky;top:0;z-index:100;box-shadow:0 2px 8px rgba(0,0,0,0.2);display:flex;justify-content:space-between;align-items:center"><span>Logo</span><nav>Home | About | Contact</nav></header><div style="padding:16px">Scroll me down... more content...</div></div>',
        },
      ],
    },
    {
      id: 'slide-5',
      type: 'concept',
      title_ru: 'Контекст позиционирования',
      title_en: 'Positioning Context',
      body_ru: '`absolute`-элемент позиционируется относительно ближайшего предка с `position` отличным от `static`. Если такого нет — относительно `<html>`. Это ключевой паттерн: дайте родителю `position: relative`, чтобы управлять положением `absolute`-потомка.',
      body_en: 'An `absolute` element is positioned relative to its nearest ancestor with a `position` other than `static`. If none exists, it is positioned relative to `<html>`. This is the key pattern: give the parent `position: relative` to control the `absolute` child\'s placement.',
      code: '.card {\n  position: relative; /* establishes context */\n}\n\n.card__badge {\n  position: absolute;\n  top: 12px;\n  right: 12px;  /* 12px from card\'s top-right corner */\n}',
      codeLang: 'css',
    },
    {
      id: 'slide-6',
      type: 'code',
      title_ru: 'Типовые паттерны позиционирования',
      title_en: 'Common Positioning Patterns',
      body_ru: 'Несколько повсеместно используемых паттернов с `position`.',
      body_en: 'Several widely used patterns built with `position`.',
      code: '/* 1. Badge on a card */\n.card { position: relative; }\n.card__badge {\n  position: absolute;\n  top: 8px; right: 8px;\n}\n\n/* 2. Centered overlay */\n.modal-backdrop {\n  position: fixed;\n  inset: 0; /* shorthand for top/right/bottom/left: 0 */\n  background: rgba(0,0,0,0.5);\n  display: grid;\n  place-items: center;\n}\n\n/* 3. Sticky sidebar */\n.sidebar {\n  position: sticky;\n  top: 80px; /* below the sticky header */\n  align-self: start;\n}\n\n/* 4. Tooltip */\n.tooltip {\n  position: absolute;\n  bottom: calc(100% + 8px);\n  left: 50%;\n  transform: translateX(-50%);\n}',
      codeLang: 'css',
    },
    {
      id: 'slide-7',
      type: 'compare',
      title_ru: 'absolute vs fixed',
      title_en: 'absolute vs fixed',
      body_ru: 'Когда выбрать `absolute`, а когда `fixed`?',
      body_en: 'When should you choose `absolute` vs `fixed`?',
      compareLeft: {
        label_ru: 'absolute — относительно предка',
        label_en: 'absolute — relative to ancestor',
        items_ru: ['Позиционируется внутри родителя с `position: relative`', 'Прокручивается вместе со страницей', 'Для бейджей, тултипов, выпадающих меню', 'Выходит из потока — другие элементы его игнорируют'],
        items_en: ['Positioned inside a parent with `position: relative`', 'Scrolls along with the page', 'Good for badges, tooltips, dropdowns', 'Removed from flow — other elements ignore it'],
        color: 'blue',
      },
      compareRight: {
        label_ru: 'fixed — относительно экрана',
        label_en: 'fixed — relative to the screen',
        items_ru: ['Позиционируется относительно вьюпорта', 'Не прокручивается — всегда на экране', 'Для модальных окон, cookie-баннеров, чата', 'Может перекрывать контент — нужен z-index'],
        items_en: ['Positioned relative to the viewport', 'Does not scroll — always on screen', 'Good for modals, cookie banners, chat widgets', 'May overlap content — needs z-index'],
        color: 'red',
      },
    },
    {
      id: 'slide-8',
      type: 'tip',
      title_ru: 'Совет: свойство inset',
      title_en: 'Tip: The inset Property',
      body_ru: 'Вместо четырёх отдельных свойств `top: 0; right: 0; bottom: 0; left: 0` используйте шортхенд `inset: 0`. Поддерживает те же синтаксисы, что `margin` и `padding`: `inset: 10px 20px` (вертикаль горизонталь).',
      body_en: 'Instead of four separate properties `top: 0; right: 0; bottom: 0; left: 0`, use the shorthand `inset: 0`. It supports the same syntax as `margin` and `padding`: `inset: 10px 20px` (vertical horizontal).',
      code: '/* Old way */\n.overlay {\n  position: fixed;\n  top: 0; right: 0; bottom: 0; left: 0;\n}\n\n/* Modern shorthand */\n.overlay {\n  position: fixed;\n  inset: 0;\n}',
      codeLang: 'css',
      visual: { kind: 'emoji', emojis: ['✨', '🧹'], caption_ru: 'Меньше кода — та же функция', caption_en: 'Less code — same result' },
    },
    {
      id: 'slide-9',
      type: 'practice-cta',
      title_ru: 'Время практиковаться!',
      title_en: 'Time to Practice!',
      body_ru: 'Создайте карточку с прилипающей шапкой, бейджем (`absolute`) и модальным оверлеем (`fixed`). Поэкспериментируйте с `z-index`.',
      body_en: 'Build a page with a sticky header, a card badge (`absolute`), and a modal overlay (`fixed`). Experiment with `z-index`.',
      visual: { kind: 'emoji', emojis: ['💻', '📍'], caption_ru: 'Откройте редактор и расставьте элементы', caption_en: 'Open the editor and place your elements' },
    },
  ],
  content: {
    intro_ru: 'Понимание позиционирования — один из главных навыков верстальщика. Пять значений свойства `position` дают разные режимы взаимодействия с потоком документа и другими элементами. В этом уроке вы разберёте каждый из них на практических примерах.',
    intro_en: 'Understanding positioning is one of the most important layout skills. The five values of the `position` property offer different modes of interaction with the document flow and other elements. In this lesson you will explore each of them through practical examples.',
    blocks: [
      {
        sectionId: 'intro',
        heading_ru: 'Нормальный поток документа',
        heading_en: 'Normal Document Flow',
        text_ru: 'По умолчанию браузер размещает элементы в «нормальном потоке»: блочные элементы (`div`, `p`, `h1`) идут один за другим сверху вниз, строчные (`span`, `a`, `strong`) — слева направо в строке. `position: static` — это дефолтный режим. Смещения `top`, `right`, `bottom`, `left` при `static` игнорируются. Любое другое значение `position` переводит элемент в «позиционированный» режим, открывая доступ к смещениям.',
        text_en: 'By default the browser places elements in "normal flow": block elements (`div`, `p`, `h1`) stack top to bottom, inline elements (`span`, `a`, `strong`) flow left to right within a line. `position: static` is this default mode. The offsets `top`, `right`, `bottom`, `left` are ignored when `position` is `static`. Any other value activates "positioned" mode, enabling the offset properties.',
        code: '/* Static — default, offsets ignored */\np { position: static; top: 20px; } /* top has no effect */\n\n/* Relative — offset works, space preserved */\n.nudged {\n  position: relative;\n  top: 10px; /* shifts down 10px visually */\n}',
        codeLang: 'css',
      },
      {
        sectionId: 'relative',
        heading_ru: 'relative и absolute: рабочая пара',
        heading_en: 'relative and absolute: A Working Pair',
        text_ru: '`position: relative` сдвигает элемент визуально, но его пространство в потоке остаётся занятым. Главная роль `relative` — создать **контекст позиционирования** для дочерних `absolute`-элементов. Элемент с `position: absolute` выходит из потока полностью: остальные элементы его не замечают. Он позиционируется относительно ближайшего позиционированного (не `static`) предка.',
        text_en: '`position: relative` shifts the element visually, but its space in the flow is still reserved. The main purpose of `relative` is to create a **positioning context** for child `absolute` elements. An element with `position: absolute` is removed from the flow entirely — other elements ignore it. It is positioned relative to the nearest positioned (non-`static`) ancestor.',
        code: '.parent {\n  position: relative; /* create context */\n  width: 300px;\n  height: 200px;\n  background: #e8f4ff;\n}\n\n.child {\n  position: absolute;\n  bottom: 12px;\n  right: 12px;\n  background: #1c7ed6;\n  color: white;\n  padding: 4px 10px;\n  border-radius: 4px;\n}',
        codeLang: 'css',
      },
      {
        sectionId: 'fixed-sticky',
        heading_ru: 'fixed и sticky',
        heading_en: 'fixed and sticky',
        text_ru: '`position: fixed` прикрепляет элемент к вьюпорту: он всегда на экране, даже при прокрутке. Используется для шапок, подвалов, кнопок «вверх», чат-виджетов. `position: sticky` — гибрид: элемент ведёт себя как `relative`, пока не достигает заданного смещения (`top`, `left` и т. д.), затем становится `fixed` в пределах родительского контейнера. Родитель должен быть выше порогового значения, иначе sticky не сработает.',
        text_en: '`position: fixed` attaches an element to the viewport: it is always on screen even when scrolling. Used for headers, footers, back-to-top buttons, and chat widgets. `position: sticky` is a hybrid: the element behaves like `relative` until it reaches a specified offset (`top`, `left`, etc.), then becomes `fixed` within its parent container. The parent must be taller than the threshold or sticky will not activate.',
        code: '/* Always visible in the bottom-right corner */\n.chat-button {\n  position: fixed;\n  bottom: 24px;\n  right: 24px;\n  z-index: 999;\n}\n\n/* Sticks below the fixed header (height 60px) */\n.section-title {\n  position: sticky;\n  top: 60px;\n  background: white;\n  z-index: 10;\n}',
        codeLang: 'css',
      },
      {
        sectionId: 'offsets',
        heading_ru: 'Смещения и z-index',
        heading_en: 'Offsets and z-index',
        text_ru: 'Для позиционированных элементов (`relative`, `absolute`, `fixed`, `sticky`) работают свойства `top`, `right`, `bottom`, `left`. Они задают расстояние от соответствующего края контейнера. `z-index` управляет порядком отображения по оси Z: больший z-index = выше. Работает только у позиционированных элементов. Без явного `z-index` порядок определяется порядком в HTML.',
        text_en: 'For positioned elements (`relative`, `absolute`, `fixed`, `sticky`), the properties `top`, `right`, `bottom`, `left` take effect. They set the distance from the corresponding edge of the containing block. `z-index` controls the stacking order on the Z axis: higher z-index = in front. It only works on positioned elements. Without an explicit `z-index`, order is determined by HTML source order.',
        code: '.dropdown {\n  position: absolute;\n  top: calc(100% + 8px); /* 8px below the parent */\n  left: 0;\n  z-index: 50; /* above most content */\n  min-width: 200px;\n  background: white;\n  border: 1px solid #ddd;\n  border-radius: 8px;\n  box-shadow: 0 8px 24px rgba(0,0,0,0.12);\n}',
        codeLang: 'css',
      },
      {
        sectionId: 'patterns',
        heading_ru: 'Типовые паттерны позиционирования',
        heading_en: 'Common Positioning Patterns',
        text_ru: 'Знание пяти значений `position` само по себе мало что даёт — важно уметь применять их в реальных ситуациях. Несколько паттернов встречаются в любом интерфейсе. Бейдж на карточке: родитель получает `position: relative`, бейдж — `position: absolute` с нужными отступами от угла. Модальное окно: затемнённый оверлей через `position: fixed; inset: 0`, само окно центрируется внутри с помощью Flexbox или Grid.\n\nПрилипающий сайдбар — ещё один частый паттерн: `position: sticky; top: 80px` (с учётом высоты фиксированной шапки) и `align-self: start`, чтобы сайдбар не растягивался на всю высоту колонки. Тултип над элементом: `position: absolute; bottom: calc(100% + 8px); left: 50%; transform: translateX(-50%)` — позиционируется выше родителя и центрируется по горизонтали.\n\nОбщий принцип всех паттернов: начинайте с `position: relative` на контейнере, затем дочерние элементы управляются через `absolute`. Для наложения всегда выставляйте `z-index` явно, чтобы не зависеть от порядка в HTML.',
        text_en: 'Knowing the five `position` values is not enough on its own — what matters is being able to apply them in real situations. Several patterns appear in virtually every interface. A card badge: the parent gets `position: relative`, the badge gets `position: absolute` with the desired offset from the corner. A modal overlay: a darkened backdrop via `position: fixed; inset: 0`, with the dialog centered inside using Flexbox or Grid.\n\nA sticky sidebar is another common pattern: `position: sticky; top: 80px` (accounting for the fixed header height) and `align-self: start` so the sidebar does not stretch to the full column height. A tooltip above an element: `position: absolute; bottom: calc(100% + 8px); left: 50%; transform: translateX(-50%)` — positioned above the parent and centered horizontally.\n\nThe common principle across all patterns: start with `position: relative` on the container, then manage child elements with `absolute`. Always set `z-index` explicitly on overlapping elements so stacking does not depend on HTML source order.',
        code: '/* 1. Badge pinned to card corner */\n.card { position: relative; }\n.badge {\n  position: absolute;\n  top: 10px; right: 10px;\n}\n\n/* 2. Full-screen modal backdrop */\n.backdrop {\n  position: fixed;\n  inset: 0;\n  background: rgba(0,0,0,0.5);\n  display: grid;\n  place-items: center;\n  z-index: 200;\n}\n\n/* 3. Tooltip above trigger */\n.tooltip {\n  position: absolute;\n  bottom: calc(100% + 8px);\n  left: 50%;\n  transform: translateX(-50%);\n  white-space: nowrap;\n  background: #333;\n  color: #fff;\n  padding: 4px 10px;\n  border-radius: 4px;\n  font-size: 0.75rem;\n}\n\n/* 4. Sticky sidebar */\n.sidebar {\n  position: sticky;\n  top: 80px;        /* clear fixed header */\n  align-self: start;\n}',
        codeLang: 'css',
      },
    ],
  },
  editorTask: {
    title_ru: 'Карточка с бейджем и прилипающей шапкой',
    title_en: 'Card with Badge and Sticky Header',
    instructions_ru: 'Создайте страницу с прилипающей шапкой (`position: sticky; top: 0`), карточкой товара с бейджем «NEW» в правом верхнем углу (`position: absolute`) и кнопкой «В корзину» (`position: fixed`) в правом нижнем углу.',
    instructions_en: 'Build a page with a sticky header (`position: sticky; top: 0`), a product card with a "NEW" badge in the top-right corner (`position: absolute`), and an "Add to Cart" button (`position: fixed`) in the bottom-right corner.',
    activeTabs: ['html', 'css'],
    starterCode: {
      html: '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <title>Positioning Demo</title>\n  <link rel="stylesheet" href="style.css">\n</head>\n<body>\n  <header class="site-header">\n    <span class="logo">ShopApp</span>\n    <nav>Home | Products | About</nav>\n  </header>\n\n  <main class="main">\n    <div class="card">\n      <span class="badge">NEW</span>\n      <img class="card__img" src="https://picsum.photos/seed/shoes/400/250" alt="Product">\n      <div class="card__body">\n        <h2>Premium Sneakers</h2>\n        <p>Comfort meets style. Available in 5 colors.</p>\n        <p class="price">₸ 24 900</p>\n      </div>\n    </div>\n  </main>\n\n  <button class="cart-btn">🛒 Add to Cart</button>\n</body>\n</html>',
      css: '*, *::before, *::after { box-sizing: border-box; }\n\nbody {\n  margin: 0;\n  font-family: system-ui, sans-serif;\n  background: #f8fafc;\n}\n\n/* Sticky header */\n.site-header {\n  /* add position: sticky */\n  background: #1c7ed6;\n  color: white;\n  padding: 16px 24px;\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n}\n\n.logo { font-weight: 700; font-size: 1.25rem; }\n\n.main {\n  padding: 40px 20px;\n  display: flex;\n  justify-content: center;\n}\n\n/* Card: must have position: relative for badge */\n.card {\n  /* add position: relative */\n  max-width: 400px;\n  background: white;\n  border-radius: 16px;\n  overflow: hidden;\n  box-shadow: 0 4px 20px rgba(0,0,0,0.08);\n}\n\n.card__img { width: 100%; display: block; }\n.card__body { padding: 20px; }\n.price { font-size: 1.25rem; font-weight: 700; color: #1c7ed6; }\n\n/* Badge: positioned in top-right of card */\n.badge {\n  /* add position: absolute and offsets */\n  background: #f03e3e;\n  color: white;\n  font-size: 0.75rem;\n  font-weight: 700;\n  padding: 4px 10px;\n  border-radius: 999px;\n}\n\n/* Fixed cart button */\n.cart-btn {\n  /* add position: fixed and offsets */\n  background: #1c7ed6;\n  color: white;\n  border: none;\n  padding: 14px 24px;\n  border-radius: 999px;\n  font-size: 1rem;\n  cursor: pointer;\n  box-shadow: 0 4px 16px rgba(28,126,214,0.4);\n}',
    },
    hints_ru: [
      'Шапка: `position: sticky; top: 0; z-index: 100;`',
      'Карточка: `position: relative;` — это создаст контекст для бейджа',
      'Бейдж: `position: absolute; top: 12px; right: 12px;`',
      'Кнопка корзины: `position: fixed; bottom: 24px; right: 24px; z-index: 50;`',
    ],
    hints_en: [
      'Header: `position: sticky; top: 0; z-index: 100;`',
      'Card: `position: relative;` — this creates the context for the badge',
      'Badge: `position: absolute; top: 12px; right: 12px;`',
      'Cart button: `position: fixed; bottom: 24px; right: 24px; z-index: 50;`',
    ],
  },
  keyTerms: [
    {
      term_ru: 'position: relative',
      term_en: 'position: relative',
      definition_ru: 'Элемент остаётся в нормальном потоке, но может быть визуально смещён. Создаёт контекст позиционирования для потомков.',
      definition_en: 'The element stays in normal flow but can be visually offset. Creates a positioning context for descendants.',
      example_ru: '`.parent { position: relative; }` позволяет дочернему `absolute` привязаться к нему',
      example_en: '`.parent { position: relative; }` lets a child `absolute` anchor to it',
    },
    {
      term_ru: 'position: absolute',
      term_en: 'position: absolute',
      definition_ru: 'Элемент выходит из нормального потока и позиционируется относительно ближайшего позиционированного предка.',
      definition_en: 'The element is removed from normal flow and positioned relative to its nearest positioned ancestor.',
      example_ru: 'Бейдж в правом верхнем углу карточки',
      example_en: 'A badge in the top-right corner of a card',
    },
    {
      term_ru: 'position: fixed',
      term_en: 'position: fixed',
      definition_ru: 'Элемент выходит из потока и позиционируется относительно вьюпорта. Не прокручивается вместе со страницей.',
      definition_en: 'The element is removed from flow and positioned relative to the viewport. It does not scroll with the page.',
      example_ru: 'Фиксированная шапка сайта, кнопка «Наверх»',
      example_en: 'Fixed site header, back-to-top button',
    },
    {
      term_ru: 'position: sticky',
      term_en: 'position: sticky',
      definition_ru: 'Гибрид relative и fixed: ведёт себя как relative до достижения порогового смещения, затем фиксируется.',
      definition_en: 'A hybrid of relative and fixed: behaves like relative until the threshold offset is reached, then sticks.',
      example_ru: '`position: sticky; top: 0` — шапка прилипает при прокрутке',
      example_en: '`position: sticky; top: 0` — header sticks on scroll',
    },
    {
      term_ru: 'z-index',
      term_en: 'z-index',
      definition_ru: 'Порядок элементов по оси Z (глубина). Работает только у позиционированных элементов. Большее значение = ближе к пользователю.',
      definition_en: 'The stacking order of elements along the Z axis. Only works on positioned elements. Higher value = closer to the viewer.',
      example_ru: '`z-index: 100` поместит элемент поверх элементов с `z-index: 10`',
      example_en: '`z-index: 100` places an element in front of elements with `z-index: 10`',
    },
  ],
  didYouKnow: [
    {
      text_ru: 'Некоторые CSS-свойства создают новый контекст наложения (stacking context) помимо `position + z-index`. Например: `transform`, `opacity < 1`, `filter`, `will-change`. Это объясняет, почему иногда `z-index: 9999` не помогает — элемент «заперт» внутри контекста родителя.',
      text_en: 'Some CSS properties create a new stacking context beyond `position + z-index`. For example: `transform`, `opacity < 1`, `filter`, `will-change`. This explains why sometimes `z-index: 9999` still does not help — the element is "trapped" inside its parent\'s stacking context.',
    },
    {
      text_ru: '`position: sticky` поддерживается всеми современными браузерами, но у него есть важное условие: родительский элемент не должен иметь `overflow: hidden` или `overflow: auto` — иначе прилипание не сработает.',
      text_en: '`position: sticky` is supported in all modern browsers, but there is an important catch: the parent element must not have `overflow: hidden` or `overflow: auto` — otherwise sticky will not work.',
    },
  ],
  quiz: [
    {
      id: 'q1',
      text_ru: 'Относительно чего позиционируется элемент с `position: absolute`?',
      text_en: 'Relative to what is an element with `position: absolute` positioned?',
      options_ru: ['Всегда относительно `<body>`', 'Относительно вьюпорта', 'Относительно ближайшего позиционированного предка', 'Относительно своего предыдущего соседа'],
      options_en: ['Always relative to `<body>`', 'Relative to the viewport', 'Relative to the nearest positioned ancestor', 'Relative to its previous sibling'],
      correctIndex: 2,
      explanation_ru: '`absolute` ищет ближайшего предка с `position` отличным от `static`. Если не находит — позиционируется относительно `<html>`.',
      explanation_en: '`absolute` finds the nearest ancestor with a `position` other than `static`. If none exists, it positions relative to `<html>`.',
    },
    {
      id: 'q2',
      text_ru: 'Какое значение `position` прокручивается вместе со страницей, но «прилипает» при достижении заданного смещения?',
      text_en: 'Which `position` value scrolls with the page but "sticks" when a specified offset is reached?',
      options_ru: ['fixed', 'absolute', 'relative', 'sticky'],
      options_en: ['fixed', 'absolute', 'relative', 'sticky'],
      correctIndex: 3,
      explanation_ru: '`sticky` — гибрид: ведёт себя как `relative` до достижения порога (например, `top: 0`), затем прилипает как `fixed`.',
      explanation_en: '`sticky` is a hybrid: it behaves like `relative` until the threshold (e.g. `top: 0`) is reached, then sticks like `fixed`.',
    },
    {
      id: 'q3',
      text_ru: 'Что произойдёт, если задать `z-index: 999` элементу с `position: static`?',
      text_en: 'What happens if you set `z-index: 999` on an element with `position: static`?',
      options_ru: ['Элемент окажется поверх всего', 'z-index не сработает', 'Элемент станет полупрозрачным', 'Элемент выйдет из потока'],
      options_en: ['The element appears on top of everything', 'z-index has no effect', 'The element becomes semi-transparent', 'The element leaves the flow'],
      correctIndex: 1,
      explanation_ru: '`z-index` работает только у позиционированных элементов (с `position` отличным от `static`). Без этого свойство игнорируется.',
      explanation_en: '`z-index` only works on positioned elements (with `position` other than `static`). Without it, the property is ignored.',
    },
    {
      id: 'q4',
      text_ru: 'Зачем родительскому элементу нужен `position: relative` при работе с `absolute`-потомком?',
      text_en: 'Why does a parent element need `position: relative` when working with an `absolute` child?',
      options_ru: ['Чтобы ускорить рендеринг', 'Чтобы создать контекст позиционирования и привязать absolute к себе', 'Чтобы потомок не выходил за пределы страницы', 'Relative автоматически скрывает overflow'],
      options_en: ['To speed up rendering', 'To create a positioning context and anchor the absolute child to itself', 'To prevent the child from leaving the page', 'Relative automatically hides overflow'],
      correctIndex: 1,
      explanation_ru: 'Без `position: relative` на родителе, `absolute`-потомок будет позиционироваться относительно следующего позиционированного предка или `<html>`.',
      explanation_en: 'Without `position: relative` on the parent, the `absolute` child will position itself relative to the next positioned ancestor or `<html>`.',
    },
    {
      id: 'q5',
      text_ru: 'Почему `position: sticky` может не сработать?',
      text_en: 'Why might `position: sticky` fail to work?',
      options_ru: ['Не указан `z-index`', 'Родитель имеет `overflow: hidden`', 'Не указан `display: block`', 'Элемент внутри `<table>`'],
      options_en: ['No `z-index` is specified', 'The parent has `overflow: hidden`', 'No `display: block` is set', 'The element is inside a `<table>`'],
      correctIndex: 1,
      explanation_ru: '`overflow: hidden` или `overflow: auto` на родителе создаёт новый блочный контекст, который блокирует работу `sticky`.',
      explanation_en: '`overflow: hidden` or `overflow: auto` on the parent creates a new block formatting context that prevents `sticky` from working.',
    },
  ],
}
