import type { Lesson } from '@/types/lesson'

export const cssSizingUnits: Lesson = {
  slug: 'css-sizing-units',
  category: 'CSS',
  readTime: 10,
  icon: '📐',
  title_ru: 'Единицы и размеры в CSS',
  title_en: 'CSS Sizing & Units',
  description_ru: 'Изучите единицы CSS — от абсолютных px до адаптивных vw/vh — и научитесь создавать гибкие, масштабируемые макеты.',
  description_en: 'Learn CSS units — from absolute px to responsive vw/vh — and build flexible, scalable layouts.',
  sections: [
    { id: 'intro', title_ru: 'Зачем нужны разные единицы', title_en: 'Why Different Units Exist' },
    { id: 'absolute', title_ru: 'Абсолютные единицы', title_en: 'Absolute Units' },
    { id: 'relative', title_ru: 'Относительные единицы', title_en: 'Relative Units' },
    { id: 'viewport', title_ru: 'Единицы вьюпорта', title_en: 'Viewport Units' },
    { id: 'box-sizing', title_ru: 'box-sizing и min/max', title_en: 'box-sizing & min/max' },
  ],
  slides: [
    {
      id: 'slide-1',
      type: 'title',
      title_ru: 'Единицы и размеры в CSS',
      title_en: 'CSS Sizing & Units',
      body_ru: 'CSS предлагает богатый набор единиц для задания размеров. Выбор правильной единицы — ключ к адаптивному дизайну, доступности и предсказуемому поведению макета на любом экране.',
      body_en: 'CSS offers a rich set of units for specifying sizes. Choosing the right unit is the key to responsive design, accessibility, and predictable layout behavior on any screen.',
      visual: { kind: 'emoji', emojis: ['📐', '📏', '🖥️'], caption_ru: 'Правильная единица — правильный размер', caption_en: 'Right unit — right size' },
    },
    {
      id: 'slide-2',
      type: 'analogy',
      title_ru: 'Аналогия: разные линейки',
      title_en: 'Analogy: Different Rulers',
      body_ru: '`px` — это линейка в сантиметрах: абсолютна, одинакова везде. `%` — резинка: растягивается вместе с родителем. `rem` — шаг взрослого человека: всегда пропорционален базовому росту. `vw` — доля ширины окна: адаптируется под любой экран автоматически.',
      body_en: '`px` is a centimeter ruler: absolute, same everywhere. `%` is a rubber band: stretches with the parent. `rem` is an adult\'s stride: always proportional to a baseline height. `vw` is a fraction of the window width: adapts to any screen automatically.',
      visual: { kind: 'emoji', emojis: ['📏', '🔗', '🪟'], caption_ru: 'Каждая единица — свой инструмент', caption_en: 'Every unit is its own tool' },
    },
    {
      id: 'slide-3',
      type: 'concept',
      title_ru: 'Абсолютные vs Относительные',
      title_en: 'Absolute vs Relative',
      body_ru: 'Главное отличие: абсолютные единицы не меняются при масштабировании, относительные — меняются.',
      body_en: 'The key difference: absolute units do not change when scaled; relative units do.',
      bullets: [
        { text_ru: '**Абсолютные**: `px`, `pt`, `cm` — фиксированный размер, не зависящий от контекста', text_en: '**Absolute**: `px`, `pt`, `cm` — fixed size, independent of context' },
        { text_ru: '**Относительные к шрифту**: `em`, `rem`, `ch` — зависят от font-size', text_en: '**Font-relative**: `em`, `rem`, `ch` — depend on font-size' },
        { text_ru: '**Относительные к родителю**: `%` — доля размера родительского элемента', text_en: '**Parent-relative**: `%` — fraction of the parent element\'s size' },
        { text_ru: '**Относительные к вьюпорту**: `vw`, `vh`, `vmin`, `vmax` — доля окна браузера', text_en: '**Viewport-relative**: `vw`, `vh`, `vmin`, `vmax` — fraction of the browser window' },
      ],
    },
    {
      id: 'slide-4',
      type: 'code-anim',
      title_ru: 'Адаптивный блок с разными единицами',
      title_en: 'Responsive Box with Different Units',
      body_ru: 'Наблюдайте, как выбор единицы меняет поведение элемента.',
      body_en: 'Watch how the choice of unit changes the element\'s behaviour.',
      codeLang: 'css',
      animMode: 'preview',
      animSteps: [
        {
          code: '.box {\n  width: 300px;\n  height: 200px;\n  background: #4dabf7;\n}',
          comment_ru: 'px: фиксированный размер — одинаков на любом экране',
          comment_en: 'px: fixed size — the same on every screen',
          preview: '<div style="width:300px;height:200px;background:#4dabf7;border-radius:8px;display:flex;align-items:center;justify-content:center;color:#fff">300px × 200px</div>',
        },
        {
          code: '.box {\n  width: 80%;\n  height: 200px;\n  background: #4dabf7;\n}',
          comment_ru: '% ширины: блок растягивается вместе с родителем',
          comment_en: '% width: the box stretches with its parent',
          preview: '<div style="width:80%;height:200px;background:#4dabf7;border-radius:8px;display:flex;align-items:center;justify-content:center;color:#fff">80% × 200px</div>',
        },
        {
          code: '.box {\n  width: 80%;\n  height: 20vh;\n  background: #4dabf7;\n}',
          comment_ru: 'vh: высота привязана к высоте вьюпорта, а не к родителю',
          comment_en: 'vh: height tied to the viewport height, not the parent',
          preview: '<div style="width:80%;height:20vh;background:#4dabf7;border-radius:8px;display:flex;align-items:center;justify-content:center;color:#fff">80% × 20vh</div>',
        },
        {
          code: '.box {\n  width: min(600px, 90%);\n  height: 20vh;\n  background: #4dabf7;\n  padding: 1.5rem;\n  box-sizing: border-box;\n}',
          comment_ru: 'min() + box-sizing: не шире 600px и не шире экрана, padding включён в размер',
          comment_en: 'min() + box-sizing: no wider than 600px or 90%, padding included in size',
          preview: '<div style="width:min(600px,90%);height:20vh;background:#4dabf7;border-radius:8px;padding:1.5rem;box-sizing:border-box;display:flex;align-items:center;justify-content:center;color:#fff">min(600px, 90%) × 20vh</div>',
        },
      ],
    },
    {
      id: 'slide-5',
      type: 'concept',
      title_ru: 'em vs rem: в чём разница',
      title_en: 'em vs rem: The Difference',
      body_ru: 'Обе единицы относительны к font-size, но от разных источников.',
      body_en: 'Both units are relative to a font-size, but from different sources.',
      bullets: [
        { text_ru: '`em`: 1em = `font-size` **родительского** элемента. Вложенность накапливает масштаб!', text_en: '`em`: 1em = `font-size` of the **parent** element. Nesting compounds the scale!' },
        { text_ru: '`rem`: 1rem = `font-size` **корневого** элемента (`<html>`). Всегда предсказуем.', text_en: '`rem`: 1rem = `font-size` of the **root** element (`<html>`). Always predictable.' },
        { text_ru: 'em полезен для `padding`/`margin` внутри компонента — масштабируется вместе со шрифтом', text_en: 'em is useful for `padding`/`margin` inside a component — scales with the font' },
        { text_ru: 'rem идеален для `font-size` и глобальных размеров — легко управлять одним значением', text_en: 'rem is ideal for `font-size` and global sizes — easy to control from one value' },
      ],
    },
    {
      id: 'slide-6',
      type: 'code',
      title_ru: 'min-width, max-width, auto',
      title_en: 'min-width, max-width, auto',
      body_ru: '`min-width`, `max-width` и `auto` — мощные инструменты для создания адаптивных контейнеров.',
      body_en: '`min-width`, `max-width`, and `auto` are powerful tools for responsive containers.',
      code: '.container {\n  width: 100%;         /* fill available space */\n  max-width: 1200px;   /* but no wider than 1200px */\n  margin: 0 auto;      /* center horizontally */\n}\n\n.sidebar {\n  min-width: 200px;    /* never narrower than 200px */\n  max-width: 320px;    /* never wider than 320px */\n  width: 25%;          /* try 25% first */\n}\n\n.image {\n  width: 100%;         /* fill its container */\n  max-width: 800px;    /* cap for large screens */\n  height: auto;        /* maintain aspect ratio */\n}',
      codeLang: 'css',
    },
    {
      id: 'slide-7',
      type: 'compare',
      title_ru: 'em vs rem',
      title_en: 'em vs rem',
      body_ru: 'Когда использовать каждую из единиц?',
      body_en: 'When should you use each unit?',
      compareLeft: {
        label_ru: 'em — для локального масштаба',
        label_en: 'em — for local scaling',
        items_ru: ['Padding и margin внутри компонента', 'Иконки рядом с текстом (1.2em = чуть крупнее)', 'Масштабируется вместе с font-size элемента', 'Осторожно: вложенность умножает значение'],
        items_en: ['Padding and margin inside a component', 'Icons next to text (1.2em = slightly larger)', 'Scales with the element\'s font-size', 'Caution: nesting multiplies the value'],
        color: 'amber',
      },
      compareRight: {
        label_ru: 'rem — для глобального масштаба',
        label_en: 'rem — for global scaling',
        items_ru: ['font-size всех текстовых элементов', 'Глобальные отступы и размеры', 'Не накапливается при вложенности', 'Меняя html font-size — масштабируете всё'],
        items_en: ['font-size of all text elements', 'Global spacing and sizing', 'Does not compound with nesting', 'Change html font-size to scale everything'],
        color: 'green',
      },
    },
    {
      id: 'slide-8',
      type: 'tip',
      title_ru: 'Совет: box-sizing: border-box',
      title_en: 'Tip: box-sizing: border-box',
      body_ru: 'По умолчанию `width` не включает `padding` и `border`. `box-sizing: border-box` меняет это: итоговый размер элемента ровно `width`, а padding и border вычитаются изнутри. Подключите это правило глобально — и расчёты станут намного проще.',
      body_en: 'By default, `width` excludes `padding` and `border`. `box-sizing: border-box` changes this: the element\'s total size equals exactly `width`, and padding and border are subtracted from inside. Apply it globally and layout math becomes much simpler.',
      code: '*, *::before, *::after {\n  box-sizing: border-box;\n}',
      codeLang: 'css',
      visual: { kind: 'emoji', emojis: ['📦', '✅'], caption_ru: 'Размер = то, что вы написали', caption_en: 'Size = what you wrote' },
    },
    {
      id: 'slide-9',
      type: 'practice-cta',
      title_ru: 'Время практиковаться!',
      title_en: 'Time to Practice!',
      body_ru: 'Создайте адаптивный контейнер, используя `max-width`, `%`, `rem` и `vh`. Проверьте, как он выглядит при разной ширине окна.',
      body_en: 'Build a responsive container using `max-width`, `%`, `rem`, and `vh`. Test how it looks at different window widths.',
      visual: { kind: 'emoji', emojis: ['💻', '📐'], caption_ru: 'Откройте редактор и поэкспериментируйте', caption_en: 'Open the editor and experiment' },
    },
  ],
  content: {
    intro_ru: 'Единицы измерения CSS определяют, как элементы реагируют на изменение контекста — будь то другой экран, другой шрифт или другой родительский блок. Освоив эти единицы, вы сможете создавать макеты, которые выглядят правильно везде — от смартфона до широкого монитора.',
    intro_en: 'CSS units define how elements respond to changes in context — whether that is a different screen, a different font, or a different parent element. Once you master these units, you can build layouts that look correct everywhere — from a smartphone to a wide desktop monitor.',
    blocks: [
      {
        sectionId: 'absolute',
        heading_ru: 'Пиксели: надёжный абсолют',
        heading_en: 'Pixels: The Reliable Absolute',
        text_ru: 'Пиксель (`px`) — наиболее знакомая единица. Он абсолютен в том смысле, что не зависит от родителя или корня. Однако на дисплеях с высокой плотностью (`devicePixelRatio > 1`) один CSS-пиксель соответствует нескольким физическим пикселям — поэтому изображения нужно делать в 2–3× разрешении. `px` отлично подходит для границ (`border: 1px solid`), теней и других деталей, где важна точность до пикселя.',
        text_en: 'The pixel (`px`) is the most familiar unit. It is absolute in the sense that it does not depend on the parent or root. However, on high-density displays (`devicePixelRatio > 1`) one CSS pixel maps to multiple physical pixels — which is why images need to be 2–3× resolution. `px` is great for borders (`border: 1px solid`), shadows, and other details where pixel-perfect accuracy matters.',
        code: 'button {\n  border: 2px solid #3B5BDB;\n  border-radius: 6px;\n  box-shadow: 0 2px 8px rgba(0,0,0,0.12);\n}',
        codeLang: 'css',
      },
      {
        sectionId: 'relative',
        heading_ru: 'em и rem: относительные к шрифту',
        heading_en: 'em and rem: Font-relative Units',
        text_ru: '`em` вычисляется относительно `font-size` ближайшего родителя. Если у `div` размер шрифта 20px, то `padding: 1em` = 20px. При вложенности `em` накапливается: `div (20px) > p (1.2em = 24px) > span (1.2em = 28.8px)`. `rem` всегда опирается на корень (`<html>`), что делает его предсказуемым вне зависимости от глубины вложенности.',
        text_en: '`em` is computed relative to the nearest parent\'s `font-size`. If a `div` has `font-size: 20px`, then `padding: 1em` equals 20px. With nesting, `em` compounds: `div (20px) > p (1.2em = 24px) > span (1.2em = 28.8px)`. `rem` always refers to the root (`<html>`), making it predictable regardless of nesting depth.',
        code: 'html { font-size: 16px; } /* 1rem = 16px */\n\n.card {\n  font-size: 1.125rem; /* 18px */\n  padding: 1.5rem;    /* 24px — from root */\n}\n\n.card__icon {\n  font-size: 1.5em;   /* 27px — from .card */\n  margin-right: 0.5em; /* 13.5px — from .card__icon */\n}',
        codeLang: 'css',
      },
      {
        sectionId: 'viewport',
        heading_ru: 'Единицы вьюпорта',
        heading_en: 'Viewport Units',
        text_ru: '`vw` (viewport width) и `vh` (viewport height) — 1vw = 1% ширины окна, 1vh = 1% высоты окна. Используйте `100vh` для секций на весь экран. `vmin` = меньшее из vw/vh, `vmax` — большее. Современные браузеры поддерживают `dvh` (dynamic viewport height) — он корректно учитывает адресную строку мобильного браузера.',
        text_en: '`vw` (viewport width) and `vh` (viewport height) — 1vw = 1% of the window width, 1vh = 1% of the window height. Use `100vh` for full-screen sections. `vmin` = the smaller of vw/vh, `vmax` = the larger. Modern browsers support `dvh` (dynamic viewport height) — it correctly accounts for the mobile browser address bar.',
        code: '.hero {\n  min-height: 100vh; /* full screen */\n  width: 100%;\n}\n\n.fluid-title {\n  /* clamp(min, preferred, max) */\n  font-size: clamp(1.5rem, 5vw, 4rem);\n}',
        codeLang: 'css',
      },
      {
        sectionId: 'box-sizing',
        heading_ru: 'box-sizing и модель блока',
        heading_en: 'box-sizing and the Box Model',
        text_ru: 'По умолчанию (`content-box`) ширина элемента не включает padding и border. Это контринтуитивно: элемент с `width: 300px; padding: 20px; border: 2px solid` занимает 344px. `border-box` меняет правило: итоговый размер = width. Это гораздо проще при вёрстке. `min-content` и `max-content` — ключевые слова, задающие ширину по содержимому.',
        text_en: 'By default (`content-box`) an element\'s width excludes padding and border. This is counterintuitive: an element with `width: 300px; padding: 20px; border: 2px solid` occupies 344px. `border-box` changes the rule: total size = width. This is much simpler when laying out. `min-content` and `max-content` are keywords that size an element by its content.',
        code: '/* Global reset — apply before anything else */\n*, *::before, *::after {\n  box-sizing: border-box;\n}\n\n/* Now this is exactly 300px wide, including padding */\n.box {\n  width: 300px;\n  padding: 20px;\n  border: 2px solid #aaa;\n}',
        codeLang: 'css',
      },
    ],
  },
  editorTask: {
    title_ru: 'Адаптивная карточка-профиль',
    title_en: 'Responsive Profile Card',
    instructions_ru: 'Создайте профильную карточку с `max-width: 400px`, центрированием через `margin: auto`, размерами шрифтов в `rem`, отступами в `em` и высотой аватара в `vh`. Используйте `box-sizing: border-box`.',
    instructions_en: 'Build a profile card with `max-width: 400px`, centered via `margin: auto`, font sizes in `rem`, padding in `em`, and avatar height in `vh`. Use `box-sizing: border-box`.',
    activeTabs: ['html', 'css'],
    starterCode: {
      html: '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <title>Profile Card</title>\n  <link rel="stylesheet" href="style.css">\n</head>\n<body>\n  <div class="card">\n    <div class="avatar">JD</div>\n    <h2 class="name">Jane Doe</h2>\n    <p class="title-text">UI Designer & Developer</p>\n    <div class="stats">\n      <div class="stat">\n        <span class="stat__number">142</span>\n        <span class="stat__label">Projects</span>\n      </div>\n      <div class="stat">\n        <span class="stat__number">8k</span>\n        <span class="stat__label">Followers</span>\n      </div>\n      <div class="stat">\n        <span class="stat__number">24</span>\n        <span class="stat__label">Awards</span>\n      </div>\n    </div>\n  </div>\n</body>\n</html>',
      css: '*, *::before, *::after {\n  box-sizing: border-box;\n}\n\nbody {\n  display: flex;\n  justify-content: center;\n  padding: 2rem;\n  background: #f0f4ff;\n}\n\n/* Card: max-width in px, width in % */\n.card {\n  width: 100%;\n  /* add max-width */\n  background: white;\n  border-radius: 16px;\n  padding: 2rem;\n  text-align: center;\n}\n\n/* Avatar: use vh for height */\n.avatar {\n  /* set width and height using vh */\n  border-radius: 50%;\n  background: #3B5BDB;\n  color: white;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  margin: 0 auto 1rem;\n}\n\n/* Name: rem for font-size */\n.name {\n  /* font-size in rem */\n  margin-bottom: 0.5rem;\n}\n\n/* Stats row */\n.stats {\n  display: flex;\n  justify-content: space-around;\n  margin-top: 1.5rem;\n  border-top: 1px solid #eee;\n  padding-top: 1.5rem;\n}\n\n.stat__number {\n  display: block;\n  font-weight: 700;\n}\n\n.stat__label {\n  font-size: 0.75rem;\n  color: #888;\n}',
    },
    hints_ru: [
      '`max-width: 400px; margin: 0 auto;` для центрирования карточки',
      'Аватар: `width: 12vw; height: 12vw;` (но добавьте `min-width: 80px; max-width: 120px` для ограничений)',
      'Имя: `font-size: 1.5rem; font-weight: 700;`',
      'Размер иконки аватара: `font-size: 1.5em` — масштабируется вместе с размером аватара',
    ],
    hints_en: [
      '`max-width: 400px; margin: 0 auto;` to center the card',
      'Avatar: `width: 12vw; height: 12vw;` (add `min-width: 80px; max-width: 120px` for constraints)',
      'Name: `font-size: 1.5rem; font-weight: 700;`',
      'Avatar font size: `font-size: 1.5em` — scales with the avatar size',
    ],
  },
  keyTerms: [
    {
      term_ru: 'px (пиксель)',
      term_en: 'px (pixel)',
      definition_ru: 'Абсолютная единица CSS. Один CSS-пиксель может соответствовать нескольким физическим пикселям на дисплеях высокой плотности.',
      definition_en: 'An absolute CSS unit. One CSS pixel may map to multiple physical pixels on high-density displays.',
      example_ru: '`border: 1px solid #ccc` — тонкая граница',
      example_en: '`border: 1px solid #ccc` — a thin border',
    },
    {
      term_ru: 'rem',
      term_en: 'rem',
      definition_ru: 'Root em — единица, равная font-size корневого элемента HTML. Предсказуема и не накапливается при вложенности.',
      definition_en: 'Root em — a unit equal to the font-size of the HTML root element. Predictable and does not compound with nesting.',
      example_ru: '`font-size: 1.25rem` при html{font-size:16px} = 20px',
      example_en: '`font-size: 1.25rem` with html{font-size:16px} = 20px',
    },
    {
      term_ru: 'em',
      term_en: 'em',
      definition_ru: 'Единица, равная font-size ближайшего родителя. При вложенности значения перемножаются.',
      definition_en: 'A unit equal to the font-size of the nearest parent. Values multiply when nested.',
      example_ru: 'Если родитель 20px, `padding: 1em` = 20px',
      example_en: 'If the parent is 20px, `padding: 1em` = 20px',
    },
    {
      term_ru: 'vw / vh',
      term_en: 'vw / vh',
      definition_ru: '1vw = 1% ширины вьюпорта, 1vh = 1% высоты вьюпорта. Используются для элементов на весь экран.',
      definition_en: '1vw = 1% of the viewport width, 1vh = 1% of the viewport height. Used for full-screen elements.',
      example_ru: '`min-height: 100vh` делает секцию высотой на весь экран',
      example_en: '`min-height: 100vh` makes a section full-screen height',
    },
    {
      term_ru: 'box-sizing: border-box',
      term_en: 'box-sizing: border-box',
      definition_ru: 'Режим расчёта размеров, при котором padding и border включены в заданные width/height.',
      definition_en: 'A sizing mode where padding and border are included in the specified width/height.',
      example_ru: 'Элемент с `width:200px; padding:20px` занимает ровно 200px',
      example_en: 'An element with `width:200px; padding:20px` occupies exactly 200px',
    },
  ],
  didYouKnow: [
    {
      text_ru: 'CSS-функция `clamp(min, preferred, max)` позволяет создавать плавно масштабируемые значения без медиазапросов: `font-size: clamp(1rem, 2.5vw, 2rem)` — никогда не меньше 1rem и не больше 2rem.',
      text_en: 'The CSS function `clamp(min, preferred, max)` lets you create smoothly scaling values without media queries: `font-size: clamp(1rem, 2.5vw, 2rem)` — never smaller than 1rem or larger than 2rem.',
    },
    {
      text_ru: 'На мобильных устройствах `100vh` часто включает высоту адресной строки браузера, что вызывает нежелательный скролл. Новые единицы `svh` (small), `lvh` (large) и `dvh` (dynamic) решают эту проблему.',
      text_en: 'On mobile devices `100vh` often includes the height of the browser address bar, causing unwanted scroll. The new units `svh` (small), `lvh` (large), and `dvh` (dynamic) solve this problem.',
    },
  ],
  quiz: [
    {
      id: 'q1',
      text_ru: 'Чему равен `2em`, если родительский элемент имеет `font-size: 20px`?',
      text_en: 'What is `2em` if the parent element has `font-size: 20px`?',
      options_ru: ['16px', '20px', '32px', '40px'],
      options_en: ['16px', '20px', '32px', '40px'],
      correctIndex: 3,
      explanation_ru: '`em` умножается на `font-size` родителя: 2 × 20px = 40px.',
      explanation_en: '`em` multiplies the parent\'s `font-size`: 2 × 20px = 40px.',
    },
    {
      id: 'q2',
      text_ru: 'Какой размер будет у элемента с `width: 300px; padding: 30px` при `box-sizing: border-box`?',
      text_en: 'What is the total rendered width of an element with `width: 300px; padding: 30px` using `box-sizing: border-box`?',
      options_ru: ['240px', '300px', '360px', '330px'],
      options_en: ['240px', '300px', '360px', '330px'],
      correctIndex: 1,
      explanation_ru: 'При `border-box` итоговая ширина = width = 300px. Padding вычитается изнутри, уменьшая область контента до 240px.',
      explanation_en: 'With `border-box` total width = width = 300px. The padding is subtracted from inside, reducing the content area to 240px.',
    },
    {
      id: 'q3',
      text_ru: 'Что делает `max-width: 1200px` вместе с `width: 100%`?',
      text_en: 'What does `max-width: 1200px` combined with `width: 100%` do?',
      options_ru: ['Фиксирует ширину 1200px', 'Заполняет экран, но не шире 1200px', 'Задаёт минимальную ширину', 'Ограничивает высоту'],
      options_en: ['Fixes the width at 1200px', 'Fills the screen but no wider than 1200px', 'Sets a minimum width', 'Limits the height'],
      correctIndex: 1,
      explanation_ru: '`width: 100%` растягивает элемент на всю доступную ширину. `max-width: 1200px` не даёт ему стать шире 1200px — идеальный паттерн для отзывчивых контейнеров.',
      explanation_en: '`width: 100%` stretches the element to the available width. `max-width: 1200px` prevents it from exceeding 1200px — the ideal pattern for responsive containers.',
    },
    {
      id: 'q4',
      text_ru: 'Почему `rem` предпочтительнее `em` для `font-size` текстовых элементов?',
      text_en: 'Why is `rem` preferred over `em` for text element `font-size`?',
      options_ru: ['rem работает быстрее', 'rem не накапливается при вложенности', 'rem поддерживается в большем числе браузеров', 'rem автоматически добавляет медиазапросы'],
      options_en: ['rem renders faster', 'rem does not compound with nesting', 'rem has broader browser support', 'rem automatically adds media queries'],
      correctIndex: 1,
      explanation_ru: 'При вложенных элементах `em` перемножается, что быстро становится непредсказуемым. `rem` всегда относится к корню, поэтому значения остаются управляемыми.',
      explanation_en: 'With nested elements `em` multiplies, quickly becoming unpredictable. `rem` always refers to the root, so values stay manageable.',
    },
    {
      id: 'q5',
      text_ru: 'Какая единица измерения равна 1% ширины окна браузера?',
      text_en: 'Which unit equals 1% of the browser window\'s width?',
      options_ru: ['1%', '1vh', '1vw', '1em'],
      options_en: ['1%', '1vh', '1vw', '1em'],
      correctIndex: 2,
      explanation_ru: '`1vw` = 1% ширины вьюпорта. `1vh` = 1% высоты вьюпорта. `1%` зависит от родительского элемента.',
      explanation_en: '`1vw` = 1% of the viewport width. `1vh` = 1% of the viewport height. `1%` depends on the parent element.',
    },
  ],
}
