import type { Lesson } from '@/types/lesson'

export const cssTextFonts: Lesson = {
  slug: 'css-text-fonts',
  category: 'CSS',
  readTime: 9,
  icon: '✍️',
  title_ru: 'Шрифты и текст в CSS',
  title_en: 'CSS Text & Fonts',
  description_ru: 'Освойте типографику в вебе: семейства шрифтов, размеры, насыщенность, выравнивание и межстрочный интервал.',
  description_en: 'Master web typography: font families, sizes, weights, alignment, and line spacing.',
  sections: [
    { id: 'intro', title_ru: 'Типографика в вебе', title_en: 'Web Typography' },
    { id: 'font-family', title_ru: 'Шрифтовые семейства', title_en: 'Font Families' },
    { id: 'size-weight', title_ru: 'Размер и насыщенность', title_en: 'Size & Weight' },
    { id: 'spacing', title_ru: 'Интервалы', title_en: 'Spacing' },
    { id: 'decoration', title_ru: 'Оформление текста', title_en: 'Text Decoration' },
  ],
  slides: [
    {
      id: 'slide-1',
      type: 'title',
      title_ru: 'Шрифты и текст в CSS',
      title_en: 'CSS Text & Fonts',
      body_ru: 'Более 95% информации на сайтах — это текст. Хорошая типографика повышает читаемость, создаёт иерархию и отражает характер бренда. CSS предоставляет мощные инструменты для управления каждым аспектом шрифта.',
      body_en: 'More than 95% of the information on the web is text. Good typography improves readability, creates hierarchy, and reflects brand character. CSS provides powerful tools to control every aspect of how text looks.',
      visual: { kind: 'emoji', emojis: ['✍️', '📖', '🔤'], caption_ru: 'Текст — основа веб-дизайна', caption_en: 'Text is the foundation of web design' },
    },
    {
      id: 'slide-2',
      type: 'analogy',
      title_ru: 'Аналогия: настройка печатной машинки',
      title_en: 'Analogy: Configuring a Typewriter',
      body_ru: 'Представьте CSS-типографику как настройку профессиональной печатной машинки: `font-family` — выбор гарнитуры, `font-size` — кегль, `font-weight` — толщина насечки, `line-height` — расстояние между строками на барабане. Каждый параметр влияет на комфорт чтения.',
      body_en: 'Think of CSS typography as configuring a professional typewriter: `font-family` selects the typeface, `font-size` sets the point size, `font-weight` controls stroke width, `line-height` sets the drum spacing between lines. Each parameter affects reading comfort.',
      visual: { kind: 'emoji', emojis: ['⌨️', '📏', '🎚️'], caption_ru: 'Каждая настройка — часть комфортного чтения', caption_en: 'Every setting contributes to reading comfort' },
    },
    {
      id: 'slide-3',
      type: 'concept',
      title_ru: 'font-family: стек шрифтов',
      title_en: 'font-family: The Font Stack',
      body_ru: 'Свойство `font-family` принимает список шрифтов через запятую — браузер использует первый доступный. Список всегда заканчивается общим семейством (`serif`, `sans-serif`, `monospace`).',
      body_en: 'The `font-family` property takes a comma-separated list of fonts — the browser uses the first one available. The list always ends with a generic family (`serif`, `sans-serif`, `monospace`).',
      bullets: [
        { text_ru: 'Системные шрифты: `"Segoe UI", Arial, sans-serif` — быстро, без загрузки', text_en: 'System fonts: `"Segoe UI", Arial, sans-serif` — fast, no download needed' },
        { text_ru: 'Google Fonts: подключаются через `<link>` в `<head>`', text_en: 'Google Fonts: linked via `<link>` in `<head>`' },
        { text_ru: '`@font-face`: самостоятельная загрузка файлов шрифта', text_en: '`@font-face`: self-hosted font files' },
      ],
      code: 'body {\n  font-family: "Inter", "Segoe UI", Arial, sans-serif;\n}',
      codeLang: 'css',
    },
    {
      id: 'slide-4',
      type: 'code-anim',
      title_ru: 'Стилизуем текст шаг за шагом',
      title_en: 'Styling Text Step by Step',
      body_ru: 'Смотрите, как последовательное добавление свойств преображает обычный текст в профессиональную типографику.',
      body_en: 'Watch how adding properties one by one transforms plain text into professional typography.',
      codeLang: 'css',
      animMode: 'preview',
      animSteps: [
        {
          code: 'h1 {\n  font-family: "Georgia", serif;\n}',
          comment_ru: 'Начинаем с выбора шрифтового семейства',
          comment_en: 'Start by choosing a font family',
          preview: '<h1 style="font-family:Georgia,serif">Welcome to CSS Typography</h1>',
        },
        {
          code: 'h1 {\n  font-family: "Georgia", serif;\n  font-size: 2.5rem;\n  font-weight: 700;\n}',
          comment_ru: 'Задаём размер в rem и насыщенность 700 (Bold)',
          comment_en: 'Set the size in rem and weight to 700 (Bold)',
          preview: '<h1 style="font-family:Georgia,serif;font-size:2.5rem;font-weight:700">Welcome to CSS Typography</h1>',
        },
        {
          code: 'h1 {\n  font-family: "Georgia", serif;\n  font-size: 2.5rem;\n  font-weight: 700;\n  line-height: 1.2;\n  letter-spacing: -0.02em;\n}',
          comment_ru: 'Поджимаем межстрочный интервал и убираем лишнее расстояние между буквами',
          comment_en: 'Tighten the line height and reduce letter spacing',
          preview: '<h1 style="font-family:Georgia,serif;font-size:2.5rem;font-weight:700;line-height:1.2;letter-spacing:-0.02em">Welcome to CSS Typography</h1>',
        },
        {
          code: 'h1 {\n  font-family: "Georgia", serif;\n  font-size: 2.5rem;\n  font-weight: 700;\n  line-height: 1.2;\n  letter-spacing: -0.02em;\n  text-align: center;\n  text-transform: uppercase;\n  color: #1a1a2e;\n}',
          comment_ru: 'Центрируем, переводим в верхний регистр и задаём цвет',
          comment_en: 'Center, uppercase, and color the heading',
          preview: '<h1 style="font-family:Georgia,serif;font-size:2.5rem;font-weight:700;line-height:1.2;letter-spacing:-0.02em;text-align:center;text-transform:uppercase;color:#1a1a2e">Welcome to CSS Typography</h1>',
        },
      ],
    },
    {
      id: 'slide-5',
      type: 'concept',
      title_ru: 'font-size: единицы измерения',
      title_en: 'font-size: Units',
      body_ru: 'Выбор единицы измерения шрифта влияет на доступность и адаптивность.',
      body_en: 'Choosing the right font-size unit affects accessibility and responsiveness.',
      bullets: [
        { text_ru: '`px` — абсолютный, предсказуемый, но игнорирует настройки браузера', text_en: '`px` — absolute, predictable, but ignores browser settings' },
        { text_ru: '`rem` — относительно корневого элемента (`html`), масштабируется', text_en: '`rem` — relative to the root (`html`) element, scales properly' },
        { text_ru: '`em` — относительно родительского элемента, накапливается', text_en: '`em` — relative to the parent, compounds with nesting' },
        { text_ru: '`vw`/`vh` — относительно вьюпорта, для fluid-типографики', text_en: '`vw`/`vh` — relative to the viewport, for fluid typography' },
      ],
    },
    {
      id: 'slide-6',
      type: 'code',
      title_ru: 'Оформление текста',
      title_en: 'Text Decoration & Transform',
      body_ru: '`text-decoration`, `text-transform` и `font-style` дают контроль над стилем начертания.',
      body_en: '`text-decoration`, `text-transform`, and `font-style` give control over text styling.',
      code: '/* Underline a link, remove default decoration */\na {\n  text-decoration: none;\n  border-bottom: 1px solid currentColor;\n}\n\n/* All caps for label */\n.label {\n  text-transform: uppercase;\n  letter-spacing: 0.1em;\n  font-size: 0.75rem;\n}\n\n/* Italic quote */\nblockquote {\n  font-style: italic;\n  color: #555;\n}',
      codeLang: 'css',
    },
    {
      id: 'slide-7',
      type: 'compare',
      title_ru: 'px vs rem для font-size',
      title_en: 'px vs rem for font-size',
      body_ru: 'Какую единицу выбрать для размера шрифта?',
      body_en: 'Which unit should you choose for font sizes?',
      compareLeft: {
        label_ru: 'px — простой, но жёсткий',
        label_en: 'px — simple but rigid',
        items_ru: ['Предсказуемый, легко отлаживать', 'Игнорирует пользовательские настройки браузера', 'Проблемы с доступностью (a11y)', 'Нужно менять каждое значение при масштабировании'],
        items_en: ['Predictable, easy to debug', 'Ignores the user\'s browser font preferences', 'Accessibility (a11y) issues', 'Must change every value to scale text'],
        color: 'amber',
      },
      compareRight: {
        label_ru: 'rem — гибкий и доступный',
        label_en: 'rem — flexible and accessible',
        items_ru: ['Масштабируется вместе с настройками браузера', 'Изменив `html { font-size }` — масштабируется всё', 'Рекомендован WCAG для доступности', 'Один источник истины для базового размера'],
        items_en: ['Scales with the user\'s browser preferences', 'Change `html { font-size }` to scale everything', 'Recommended by WCAG for accessibility', 'Single source of truth for the base size'],
        color: 'green',
      },
    },
    {
      id: 'slide-8',
      type: 'tip',
      title_ru: 'Совет: типографическая шкала',
      title_en: 'Tip: Use a Type Scale',
      body_ru: 'Вместо произвольных размеров шрифтов используйте типографическую шкалу: набор предопределённых размеров с коэффициентом масштаба (1.25, 1.333 и т. д.). Это создаёт визуальную гармонию. Инструменты: typescale.com, Tailwind CSS утилиты.',
      body_en: 'Instead of arbitrary font sizes, use a type scale: a set of predefined sizes with a scale ratio (1.25, 1.333, etc.). This creates visual harmony. Tools: typescale.com, Tailwind CSS utilities.',
      code: ':root {\n  --text-xs:   0.75rem;  /* 12px */\n  --text-sm:   0.875rem; /* 14px */\n  --text-base: 1rem;     /* 16px */\n  --text-lg:   1.125rem; /* 18px */\n  --text-xl:   1.25rem;  /* 20px */\n  --text-2xl:  1.5rem;   /* 24px */\n  --text-4xl:  2.25rem;  /* 36px */\n}',
      codeLang: 'css',
      visual: { kind: 'emoji', emojis: ['📐', '🎵'], caption_ru: 'Масштаб создаёт ритм', caption_en: 'Scale creates rhythm' },
    },
    {
      id: 'slide-9',
      type: 'practice-cta',
      title_ru: 'Время практиковаться!',
      title_en: 'Time to Practice!',
      body_ru: 'Создайте статью с заголовком, подзаголовком, абзацем и цитатой. Используйте разные размеры, насыщенность и выравнивание текста.',
      body_en: 'Build an article with a heading, subheading, paragraph, and blockquote. Use different font sizes, weights, and text alignment.',
      visual: { kind: 'emoji', emojis: ['💻', '✍️'], caption_ru: 'Откройте редактор и создайте типографику', caption_en: 'Open the editor and craft your typography' },
    },
  ],
  content: {
    intro_ru: 'Типографика — это искусство и наука расстановки шрифтов для того, чтобы текст был не просто читаемым, но выразительным. CSS предоставляет полный набор свойств для управления каждым аспектом: от выбора гарнитуры до межбуквенного интервала.',
    intro_en: 'Typography is the art and science of arranging type so that text is not just readable but expressive. CSS provides a complete set of properties for controlling every aspect: from choosing the typeface to adjusting letter spacing.',
    blocks: [
      {
        sectionId: 'intro',
        heading_ru: 'Типографика в вебе',
        heading_en: 'Web Typography',
        text_ru: 'Типографика — это искусство работы со шрифтом. В вебе она решает сразу несколько задач: обеспечивает читаемость, создаёт визуальную иерархию и передаёт характер бренда. Исследования показывают, что более 95% информации в интернете передаётся через текст — значит, качество типографики напрямую влияет на восприятие сайта.\n\nCSS управляет типографикой через несколько групп свойств. Первая группа отвечает за шрифт: `font-family` (гарнитура), `font-size` (кегль), `font-weight` (насыщенность), `font-style` (курсив). Вторая — за ритм текста: `line-height` (межстрочный интервал), `letter-spacing` (межбуквенный интервал), `word-spacing` (межсловный интервал). Третья — за расположение и оформление: `text-align`, `text-decoration`, `text-transform`, `text-overflow`.\n\nВ этом уроке вы разберёте каждую из этих групп, поймёте, когда использовать `px` или `rem` для шрифта, как подключать Google Fonts и как выстроить гармоничную типографическую шкалу для всего сайта.',
        text_en: 'Typography is the art of working with type. On the web it serves several purposes at once: ensuring readability, creating visual hierarchy, and conveying the character of a brand. Research shows that more than 95% of information on the web is delivered through text — meaning the quality of typography directly shapes how a site is perceived.\n\nCSS controls typography through several property groups. The first covers the font itself: `font-family` (typeface), `font-size` (size), `font-weight` (thickness), `font-style` (italic). The second governs text rhythm: `line-height` (leading), `letter-spacing` (tracking), `word-spacing`. The third handles placement and decoration: `text-align`, `text-decoration`, `text-transform`, `text-overflow`.\n\nIn this lesson you will explore each of these groups, understand when to use `px` versus `rem` for font sizes, learn to load Google Fonts, and build a harmonious type scale for an entire site.',
        code: '/* The core typography properties at a glance */\nbody {\n  font-family: "Inter", system-ui, sans-serif;\n  font-size: 1rem;      /* 16px base */\n  font-weight: 400;     /* normal */\n  line-height: 1.6;     /* comfortable reading rhythm */\n  color: #1a1a2e;\n}\n\nh1 {\n  font-size: 2.5rem;\n  font-weight: 700;\n  line-height: 1.15;\n  letter-spacing: -0.02em;\n}',
        codeLang: 'css',
      },
      {
        sectionId: 'font-family',
        heading_ru: 'Подключение шрифтов Google Fonts',
        heading_en: 'Loading Google Fonts',
        text_ru: 'Google Fonts — бесплатный сервис с сотнями шрифтов. Добавьте `<link>` в `<head>` вашего HTML, затем укажите имя шрифта в `font-family`. Выбирайте только нужные начертания (400, 700) — это ускоряет загрузку страницы. Современная рекомендация: используйте `font-display: swap`, чтобы текст отображался сразу с системным шрифтом, пока загружается нужный.',
        text_en: 'Google Fonts is a free service with hundreds of typefaces. Add a `<link>` to your HTML `<head>`, then reference the font name in `font-family`. Only load the weights you need (400, 700) — this speeds up page load. The modern recommendation is to use `font-display: swap` so text renders immediately with a fallback font while the target font loads.',
        code: '<!-- In <head> -->\n<link rel="preconnect" href="https://fonts.googleapis.com">\n<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet">\n\n/* In CSS */\nbody {\n  font-family: "Inter", sans-serif;\n}',
        codeLang: 'html',
      },
      {
        sectionId: 'size-weight',
        heading_ru: 'Размер, насыщенность и стиль',
        heading_en: 'Size, Weight, and Style',
        text_ru: '`font-size` задаёт кегль. Базовый размер браузера — 16px, поэтому `1rem = 16px`. `font-weight` принимает числа (100–900) или ключевые слова (`normal` = 400, `bold` = 700). `font-style: italic` применяет курсивное начертание — если шрифт не имеет настоящего курсива, браузер сымитирует его (это хуже).',
        text_en: '`font-size` sets the type size. The browser base is 16px, so `1rem = 16px`. `font-weight` accepts numbers (100–900) or keywords (`normal` = 400, `bold` = 700). `font-style: italic` applies italic — if the font has no true italic, the browser fakes it (this looks worse).',
        code: 'h1 { font-size: 2.5rem; font-weight: 800; }\nh2 { font-size: 1.75rem; font-weight: 700; }\np  { font-size: 1rem;    font-weight: 400; }\n\n.caption {\n  font-size: 0.875rem;\n  font-style: italic;\n  color: #666;\n}',
        codeLang: 'css',
      },
      {
        sectionId: 'spacing',
        heading_ru: 'Межстрочный и межбуквенный интервал',
        heading_en: 'Line Height and Letter Spacing',
        text_ru: '`line-height` задаёт высоту строки. Рекомендуемое значение для основного текста — 1.5–1.7 (без единицы, чтобы множитель применялся к текущему `font-size`). Для заголовков можно уменьшить до 1.1–1.3. `letter-spacing` управляет межбуквенным интервалом: используйте `em` для пропорционального масштабирования. Небольшое увеличение (0.05–0.1em) улучшает читаемость капса.',
        text_en: '`line-height` sets the height of a line box. The recommended value for body text is 1.5–1.7 (unitless, so the multiplier scales with `font-size`). For headings, 1.1–1.3 often looks better. `letter-spacing` controls spacing between characters: use `em` for proportional scaling. A small increase (0.05–0.1em) improves readability for all-caps text.',
        code: 'body {\n  line-height: 1.6;\n}\n\nh1 {\n  line-height: 1.15;\n  letter-spacing: -0.02em; /* tighten large headings */\n}\n\n.label {\n  letter-spacing: 0.08em;  /* open up small caps */\n  text-transform: uppercase;\n}',
        codeLang: 'css',
      },
      {
        sectionId: 'decoration',
        heading_ru: 'Выравнивание и оформление',
        heading_en: 'Alignment and Decoration',
        text_ru: '`text-align` выравнивает текст: `left`, `center`, `right`, `justify`. Избегайте `justify` без `hyphens: auto` — это создаёт неравномерные пробелы. `text-decoration` управляет подчёркиванием: `none` убирает его у ссылок, `underline` добавляет. `text-overflow: ellipsis` обрезает длинный текст троеточием (требует `overflow: hidden` и `white-space: nowrap`).',
        text_en: '`text-align` aligns text: `left`, `center`, `right`, `justify`. Avoid `justify` without `hyphens: auto` — it creates uneven word spacing. `text-decoration` controls underlines: `none` removes the default link underline, `underline` adds one. `text-overflow: ellipsis` truncates long text with "…" (requires `overflow: hidden` and `white-space: nowrap`).',
        code: '.truncate {\n  white-space: nowrap;\n  overflow: hidden;\n  text-overflow: ellipsis;\n  max-width: 200px;\n}\n\n.centered-section {\n  text-align: center;\n}\n\na {\n  text-decoration: none;\n  text-decoration-line: underline;\n  text-underline-offset: 3px;\n}',
        codeLang: 'css',
      },
    ],
  },
  editorTask: {
    title_ru: 'Статья с типографикой',
    title_en: 'Typographic Article',
    instructions_ru: 'Создайте карточку статьи с заголовком (2rem, bold), категорией (0.75rem, uppercase, letter-spacing), двумя абзацами (1rem, line-height 1.6) и цитатой (italic, border-left). Подключите Google Fonts.',
    instructions_en: 'Build an article card with a heading (2rem, bold), a category label (0.75rem, uppercase, letter-spacing), two body paragraphs (1rem, line-height 1.6), and a blockquote (italic, border-left). Load a Google Font.',
    activeTabs: ['html', 'css'],
    starterCode: {
      html: '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <title>Article</title>\n  <!-- Add Google Fonts link here -->\n  <link rel="stylesheet" href="style.css">\n</head>\n<body>\n  <article class="post">\n    <span class="category">Technology</span>\n    <h1 class="title">The Future of Web Design</h1>\n    <p class="lead">Web design is evolving faster than ever. New CSS features ship every year, changing how we build interfaces.</p>\n    <blockquote class="quote">\n      "Good design is as little design as possible." — Dieter Rams\n    </blockquote>\n    <p>Typography is the backbone of great design. When text is set well, readers barely notice it — they simply absorb the content.</p>\n  </article>\n</body>\n</html>',
      css: '/* Import font from Google Fonts or use system stack */\nbody {\n  font-family: system-ui, sans-serif;\n}\n\n.post {\n  max-width: 640px;\n  margin: 40px auto;\n  padding: 0 20px;\n}\n\n.category {\n  /* uppercase label with letter spacing */\n}\n\n.title {\n  /* large bold heading */\n}\n\n.lead {\n  /* slightly larger intro paragraph */\n}\n\n.quote {\n  /* italic blockquote with left border */\n}',
    },
    hints_ru: [
      'Подключите Inter: добавьте `<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet">` в `<head>`',
      'Для категории: `text-transform: uppercase; letter-spacing: 0.1em; font-size: 0.75rem;`',
      'Для цитаты: `border-left: 3px solid #3B5BDB; padding-left: 16px; font-style: italic;`',
      'Для заголовка: `font-size: 2rem; font-weight: 700; line-height: 1.2;`',
    ],
    hints_en: [
      'Load Inter: add `<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet">` to `<head>`',
      'For the category: `text-transform: uppercase; letter-spacing: 0.1em; font-size: 0.75rem;`',
      'For the blockquote: `border-left: 3px solid #3B5BDB; padding-left: 16px; font-style: italic;`',
      'For the heading: `font-size: 2rem; font-weight: 700; line-height: 1.2;`',
    ],
  },
  keyTerms: [
    {
      term_ru: 'font-family',
      term_en: 'font-family',
      definition_ru: 'CSS-свойство, задающее шрифтовое семейство (стек шрифтов). Браузер использует первый доступный шрифт из списка.',
      definition_en: 'A CSS property that specifies the font family (font stack). The browser uses the first available font from the list.',
      example_ru: '`font-family: "Inter", Arial, sans-serif`',
      example_en: '`font-family: "Inter", Arial, sans-serif`',
    },
    {
      term_ru: 'rem',
      term_en: 'rem',
      definition_ru: 'Единица длины CSS, равная `font-size` корневого элемента (`<html>`). По умолчанию 1rem = 16px.',
      definition_en: 'A CSS length unit equal to the `font-size` of the root (`<html>`) element. By default 1rem = 16px.',
      example_ru: '`font-size: 1.25rem` = 20px при базовом 16px',
      example_en: '`font-size: 1.25rem` = 20px with a 16px base',
    },
    {
      term_ru: 'line-height',
      term_en: 'line-height',
      definition_ru: 'Высота строки. Безразмерное значение (например, 1.5) умножается на `font-size` элемента.',
      definition_en: 'The height of a line box. A unitless value (e.g. 1.5) multiplies the element\'s `font-size`.',
      example_ru: '`line-height: 1.6` — стандарт для читаемого основного текста',
      example_en: '`line-height: 1.6` — standard for readable body text',
    },
    {
      term_ru: 'font-weight',
      term_en: 'font-weight',
      definition_ru: 'Насыщенность шрифта. Числа от 100 до 900, где 400 — Normal, 700 — Bold.',
      definition_en: 'The weight (thickness) of the font. Numbers from 100 to 900, where 400 is Normal and 700 is Bold.',
      example_ru: '`font-weight: 700` — жирное начертание',
      example_en: '`font-weight: 700` — bold weight',
    },
    {
      term_ru: 'letter-spacing',
      term_en: 'letter-spacing',
      definition_ru: 'Межбуквенный интервал. Положительное значение увеличивает, отрицательное — уменьшает расстояние между символами.',
      definition_en: 'Spacing between characters. A positive value increases it, a negative value tightens it.',
      example_ru: '`letter-spacing: 0.05em` — слегка разреженный текст',
      example_en: '`letter-spacing: 0.05em` — slightly open tracking',
    },
  ],
  didYouKnow: [
    {
      text_ru: 'Оптимальная длина строки для комфортного чтения — 45–75 символов. В CSS это легко реализовать с помощью `max-width: 65ch`, где `ch` — ширина символа "0" в текущем шрифте.',
      text_en: 'The optimal line length for comfortable reading is 45–75 characters. In CSS this is easily achieved with `max-width: 65ch`, where `ch` equals the width of the "0" character in the current font.',
    },
    {
      text_ru: 'Свойство `font-variant-numeric: tabular-nums` заставляет цифры занимать одинаковую ширину. Это незаменимо в таблицах и интерфейсах с числовыми данными — столбцы выравниваются идеально.',
      text_en: 'The property `font-variant-numeric: tabular-nums` forces digits to have equal width. This is invaluable in tables and numeric UI — columns line up perfectly.',
    },
  ],
  quiz: [
    {
      id: 'q1',
      text_ru: 'Чему равен `1rem` по умолчанию в большинстве браузеров?',
      text_en: 'What does `1rem` equal by default in most browsers?',
      options_ru: ['10px', '12px', '16px', '20px'],
      options_en: ['10px', '12px', '16px', '20px'],
      correctIndex: 2,
      explanation_ru: 'По умолчанию браузеры устанавливают `font-size` корневого элемента в 16px, поэтому 1rem = 16px.',
      explanation_en: 'Browsers set the root element `font-size` to 16px by default, so 1rem = 16px.',
    },
    {
      id: 'q2',
      text_ru: 'Какое значение `font-weight` соответствует ключевому слову `bold`?',
      text_en: 'Which `font-weight` numeric value corresponds to the keyword `bold`?',
      options_ru: ['400', '600', '700', '900'],
      options_en: ['400', '600', '700', '900'],
      correctIndex: 2,
      explanation_ru: '`bold` — это сокращение для `font-weight: 700`. `normal` соответствует 400.',
      explanation_en: '`bold` is shorthand for `font-weight: 700`. `normal` corresponds to 400.',
    },
    {
      id: 'q3',
      text_ru: 'Почему рекомендуется `line-height` без единицы измерения (например, 1.5 вместо 1.5em)?',
      text_en: 'Why is a unitless `line-height` (e.g. 1.5 instead of 1.5em) recommended?',
      options_ru: ['Это быстрее работает', 'Значение масштабируется пропорционально у дочерних элементов', 'Единица em не поддерживается', 'Нет разницы'],
      options_en: ['It renders faster', 'The value scales proportionally for child elements', 'The em unit is not supported', 'There is no difference'],
      correctIndex: 1,
      explanation_ru: 'Безразмерное значение наследуется как множитель и применяется к `font-size` каждого потомка. `1.5em` вычисляется сразу и наследуется как фиксированное значение в пикселях.',
      explanation_en: 'A unitless value is inherited as a multiplier and applied to each descendant\'s `font-size`. `1.5em` is computed immediately and inherited as a fixed pixel value.',
    },
    {
      id: 'q4',
      text_ru: 'Какое свойство CSS обрезает длинный текст троеточием?',
      text_en: 'Which CSS property truncates long text with an ellipsis?',
      options_ru: ['text-wrap: truncate', 'text-overflow: ellipsis', 'overflow: ellipsis', 'white-space: ellipsis'],
      options_en: ['text-wrap: truncate', 'text-overflow: ellipsis', 'overflow: ellipsis', 'white-space: ellipsis'],
      correctIndex: 1,
      explanation_ru: '`text-overflow: ellipsis` должно сочетаться с `overflow: hidden` и `white-space: nowrap`, чтобы работать.',
      explanation_en: '`text-overflow: ellipsis` must be combined with `overflow: hidden` and `white-space: nowrap` to take effect.',
    },
    {
      id: 'q5',
      text_ru: 'Как правильно задать заглавные буквы через CSS (не изменяя HTML)?',
      text_en: 'How do you correctly display text in uppercase using CSS (without changing the HTML)?',
      options_ru: ['font-variant: uppercase', 'text-transform: uppercase', 'font-style: uppercase', 'text-decoration: uppercase'],
      options_en: ['font-variant: uppercase', 'text-transform: uppercase', 'font-style: uppercase', 'text-decoration: uppercase'],
      correctIndex: 1,
      explanation_ru: '`text-transform: uppercase` преобразует текст в верхний регистр визуально, не изменяя DOM. Также существуют значения `lowercase` и `capitalize`.',
      explanation_en: '`text-transform: uppercase` visually converts text to upper case without changing the DOM. `lowercase` and `capitalize` are also valid values.',
    },
  ],
}
