import type { Lesson } from '@/types/lesson'

export const cssColorBackground: Lesson = {
  slug: 'css-color-background',
  category: 'CSS',
  readTime: 9,
  icon: '🖌️',
  title_ru: 'Цвет и фон в CSS',
  title_en: 'CSS Color & Background',
  description_ru: 'Изучите форматы цветов (HEX, RGB, HSL) и способы задания фонов: сплошные цвета, изображения, градиенты.',
  description_en: 'Master color formats (HEX, RGB, HSL) and background techniques: solid colors, images, and gradients.',
  sections: [
    { id: 'intro', title_ru: 'Цвет в CSS', title_en: 'Color in CSS' },
    { id: 'formats', title_ru: 'Форматы цвета', title_en: 'Color Formats' },
    { id: 'opacity', title_ru: 'Прозрачность', title_en: 'Opacity & Alpha' },
    { id: 'background', title_ru: 'Фон элемента', title_en: 'Element Background' },
    { id: 'gradient', title_ru: 'Градиенты', title_en: 'Gradients' },
  ],
  slides: [
    {
      id: 'slide-1',
      type: 'title',
      title_ru: 'Цвет и фон в CSS',
      title_en: 'CSS Color & Background',
      body_ru: 'Цвет — первое, что замечает пользователь. CSS предлагает множество форматов для точного описания любого оттенка, а свойство `background` открывает мир градиентов и изображений.',
      body_en: 'Color is the first thing a user notices. CSS offers multiple formats for describing any shade precisely, and the `background` property opens up a world of gradients and images.',
      visual: { kind: 'emoji', emojis: ['🎨', '🖌️', '🌈'], caption_ru: 'Миллионы цветов — к вашим услугам', caption_en: 'Millions of colors at your fingertips' },
    },
    {
      id: 'slide-2',
      type: 'analogy',
      title_ru: 'Аналогия: палитра художника',
      title_en: 'Analogy: Painter\'s Palette',
      body_ru: 'HEX — это код краски на тюбике: точный и лаконичный. RGB похож на смешивание красного, зелёного и синего прожекторов: добавляйте света, чтобы получить любой оттенок. HSL — колесо цветов: выберите тон, насыщенность и яркость интуитивно.',
      body_en: 'HEX is like the paint code on a tube: precise and compact. RGB is like mixing red, green, and blue spotlights: add light to get any color. HSL is a color wheel: choose hue, saturation, and lightness intuitively.',
      visual: { kind: 'emoji', emojis: ['🎨', '💡', '🔵'], caption_ru: 'Три способа описать один цвет', caption_en: 'Three ways to describe the same color' },
    },
    {
      id: 'slide-3',
      type: 'concept',
      title_ru: 'Форматы цвета',
      title_en: 'Color Formats',
      body_ru: 'CSS поддерживает несколько форматов. Каждый удобен в своей ситуации.',
      body_en: 'CSS supports several color formats. Each shines in its own situation.',
      bullets: [
        { text_ru: '**Имена**: `red`, `coral`, `steelblue` — удобно для прототипов', text_en: '**Names**: `red`, `coral`, `steelblue` — handy for prototyping' },
        { text_ru: '**HEX**: `#3B5BDB` — компактный, популярный в дизайн-системах', text_en: '**HEX**: `#3B5BDB` — compact, popular in design systems' },
        { text_ru: '**RGB**: `rgb(59,91,219)` — понятен при программной генерации', text_en: '**RGB**: `rgb(59,91,219)` — clear when generating colors programmatically' },
        { text_ru: '**HSL**: `hsl(228,68%,55%)` — удобен для создания палитр и вариаций', text_en: '**HSL**: `hsl(228,68%,55%)` — convenient for building palettes and variants' },
      ],
    },
    {
      id: 'slide-4',
      type: 'code-anim',
      title_ru: 'Строим цветную карточку',
      title_en: 'Building a Colorful Card',
      body_ru: 'Шаг за шагом добавляем цвет и фон к простой карточке.',
      body_en: 'Step by step, we add color and background to a simple card.',
      codeLang: 'css',
      animMode: 'preview',
      animSteps: [
        {
          code: '.card {\n  padding: 24px;\n  border-radius: 12px;\n}',
          comment_ru: 'Начинаем с базовой карточки без цвета',
          comment_en: 'Start with a basic card — no color yet',
          preview: '<div style="padding:24px;border-radius:12px;border:1px dashed #ccc">Карточка / Card</div>',
        },
        {
          code: '.card {\n  padding: 24px;\n  border-radius: 12px;\n  background-color: #3B5BDB;\n  color: #ffffff;\n}',
          comment_ru: 'Добавляем насыщенный HEX-фон и белый текст',
          comment_en: 'Add a vivid HEX background and white text',
          preview: '<div style="padding:24px;border-radius:12px;background:#3B5BDB;color:#fff">Карточка / Card</div>',
        },
        {
          code: '.card {\n  padding: 24px;\n  border-radius: 12px;\n  background-color: #3B5BDB;\n  color: #ffffff;\n}\n\n.card__tag {\n  background-color: rgba(255,255,255,0.2);\n  padding: 4px 10px;\n  border-radius: 999px;\n  font-size: 0.75rem;\n}',
          comment_ru: 'RGBA для полупрозрачного тега — фон просвечивает',
          comment_en: 'RGBA for a translucent tag — the card background shows through',
          preview: '<div style="padding:24px;border-radius:12px;background:#3B5BDB;color:#fff"><span style="background:rgba(255,255,255,0.2);padding:4px 10px;border-radius:999px;font-size:0.75rem">NEW</span><p>Карточка / Card</p></div>',
        },
        {
          code: '.card {\n  padding: 24px;\n  border-radius: 12px;\n  background: linear-gradient(135deg, #3B5BDB 0%, #7048E8 100%);\n  color: #ffffff;\n}\n\n.card__tag {\n  background-color: rgba(255,255,255,0.2);\n  padding: 4px 10px;\n  border-radius: 999px;\n  font-size: 0.75rem;\n}',
          comment_ru: 'Финал: заменяем сплошной фон на градиент',
          comment_en: 'Final: replace the solid background with a gradient',
          preview: '<div style="padding:24px;border-radius:12px;background:linear-gradient(135deg,#3B5BDB 0%,#7048E8 100%);color:#fff"><span style="background:rgba(255,255,255,0.2);padding:4px 10px;border-radius:999px;font-size:0.75rem">NEW</span><p>Карточка с градиентом / Gradient Card</p></div>',
        },
      ],
    },
    {
      id: 'slide-5',
      type: 'concept',
      title_ru: 'Прозрачность: opacity и rgba',
      title_en: 'Transparency: opacity and rgba',
      body_ru: 'Два способа управлять прозрачностью — с разными эффектами.',
      body_en: 'Two ways to control transparency — with different effects.',
      bullets: [
        { text_ru: '`opacity: 0.5` — делает **весь** элемент (включая дочерние) полупрозрачным', text_en: '`opacity: 0.5` — makes the **entire** element (including children) semi-transparent' },
        { text_ru: '`rgba(0,0,0,0.5)` — только фон/цвет, дочерние элементы остаются непрозрачными', text_en: '`rgba(0,0,0,0.5)` — only the background/color; children remain opaque' },
        { text_ru: '`hsla(228,68%,55%,0.8)` — HSL с альфа-каналом', text_en: '`hsla(228,68%,55%,0.8)` — HSL with an alpha channel' },
      ],
    },
    {
      id: 'slide-6',
      type: 'code',
      title_ru: 'Фоновое изображение',
      title_en: 'Background Image',
      body_ru: '`background-image`, `background-size`, `background-position` и `background-repeat` — полный контроль над фоновой картинкой.',
      body_en: '`background-image`, `background-size`, `background-position`, and `background-repeat` give you full control over background images.',
      code: '.hero {\n  background-image: url("hero.jpg");\n  background-size: cover;      /* fill the element */\n  background-position: center; /* keep focal point visible */\n  background-repeat: no-repeat;\n  min-height: 400px;\n}\n\n/* Overlay: gradient on top of image */\n.hero::after {\n  content: "";\n  inset: 0;\n  position: absolute;\n  background: linear-gradient(\n    to bottom,\n    transparent 40%,\n    rgba(0,0,0,0.7) 100%\n  );\n}',
      codeLang: 'css',
    },
    {
      id: 'slide-7',
      type: 'compare',
      title_ru: 'HEX vs RGB vs HSL',
      title_en: 'HEX vs RGB vs HSL',
      body_ru: 'Когда выбрать каждый формат?',
      body_en: 'When should you choose each format?',
      compareLeft: {
        label_ru: 'HEX & RGB — для точности',
        label_en: 'HEX & RGB — for precision',
        items_ru: ['HEX: компактный, копируется из Figma/Sketch', 'RGB: легко генерировать программно (JS)', 'Оба: ровно тот цвет, что задумал дизайнер', 'Популярны в дизайн-токенах и брендбуках'],
        items_en: ['HEX: compact, copied from Figma/Sketch', 'RGB: easy to generate in JavaScript', 'Both: the exact color a designer intended', 'Common in design tokens and brand guides'],
        color: 'blue',
      },
      compareRight: {
        label_ru: 'HSL — для палитр и вариаций',
        label_en: 'HSL — for palettes and variants',
        items_ru: ['Легко создавать светлый/тёмный вариант', 'Интуитивно: тон → насыщенность → яркость', 'Удобно для CSS-переменных и тем', 'Легко читается и правится вручную'],
        items_en: ['Easy to create light/dark variants', 'Intuitive: hue → saturation → lightness', 'Great for CSS variables and themes', 'Human-readable and easy to tweak by hand'],
        color: 'green',
      },
    },
    {
      id: 'slide-8',
      type: 'tip',
      title_ru: 'Совет: используйте CSS-переменные для палитры',
      title_en: 'Tip: Use CSS Variables for Your Palette',
      body_ru: 'Определите цвета один раз в `:root` как переменные и переиспользуйте их повсюду. При смене бренда достаточно поправить одно место.',
      body_en: 'Define colors once in `:root` as variables and reuse them everywhere. When the brand changes, you only update one place.',
      code: ':root {\n  --color-primary: #3B5BDB;\n  --color-primary-light: hsl(228, 68%, 75%);\n  --color-surface: #f8fafc;\n}\n\n.btn { background: var(--color-primary); }\n.card { background: var(--color-surface); }',
      codeLang: 'css',
      visual: { kind: 'emoji', emojis: ['🧩', '♻️'], caption_ru: 'Одно изменение — везде обновляется', caption_en: 'Change once — update everywhere' },
    },
    {
      id: 'slide-9',
      type: 'practice-cta',
      title_ru: 'Время практиковаться!',
      title_en: 'Time to Practice!',
      body_ru: 'Создайте красочный профильный баннер с градиентным фоном, полупрозрачным тегом и правильным цветом текста.',
      body_en: 'Build a colorful profile banner with a gradient background, a translucent tag, and proper text color contrast.',
      visual: { kind: 'emoji', emojis: ['💻', '🌈'], caption_ru: 'Откройте редактор и раскрасьте страницу', caption_en: 'Open the editor and paint the page' },
    },
  ],
  content: {
    intro_ru: 'Цвет — один из мощнейших инструментов дизайна. В CSS для его описания существует несколько форматов, каждый со своими плюсами. В этом уроке вы разберёте HEX, RGB, HSL и научитесь создавать фоны любой сложности — от однотонных до многослойных градиентов.',
    intro_en: 'Color is one of the most powerful tools in design. CSS provides several formats for specifying it, each with its own strengths. In this lesson you will explore HEX, RGB, HSL, and learn to create backgrounds of any complexity — from solid fills to layered gradients.',
    blocks: [
      {
        sectionId: 'formats',
        heading_ru: 'Три главных формата',
        heading_en: 'Three Main Formats',
        text_ru: 'HEX — шестнадцатеричная запись в формате `#RRGGBB`. Пары цифр описывают красный, зелёный и синий каналы от 00 (0) до FF (255). RGB расшифровывает то же самое в понятных числах: `rgb(59, 91, 219)`. HSL предлагает другую точку зрения: тон (0–360°), насыщенность (0–100%) и светлота (0–100%). Хотите осветлить цвет? Просто увеличьте L.',
        text_en: 'HEX is hexadecimal notation in the form `#RRGGBB`. Each pair of digits describes the red, green, and blue channel from 00 (0) to FF (255). RGB spells out the same values in plain numbers: `rgb(59, 91, 219)`. HSL offers a different perspective: hue (0–360°), saturation (0–100%), and lightness (0–100%). Want a lighter shade? Just raise the L.',
        code: 'color: red;                   /* named */\ncolor: #3B5BDB;               /* HEX */\ncolor: rgb(59, 91, 219);      /* RGB */\ncolor: hsl(228, 68%, 55%);    /* HSL */\n/* All four represent roughly the same blue */\n',
        codeLang: 'css',
      },
      {
        sectionId: 'opacity',
        heading_ru: 'Работа с прозрачностью',
        heading_en: 'Working with Transparency',
        text_ru: 'Альфа-канал добавляется буквой `a`: `rgba(59,91,219,0.5)` или `hsla(228,68%,55%,0.5)`. Значение 0 — полностью прозрачный, 1 — полностью непрозрачный. Современный CSS поддерживает и `rgb(59 91 219 / 50%)` — нотацию с пробелами через косую черту. Не путайте с `opacity`: оно делает полупрозрачным сам элемент вместе с содержимым.',
        text_en: 'The alpha channel is added with an "a": `rgba(59,91,219,0.5)` or `hsla(228,68%,55%,0.5)`. A value of 0 is fully transparent, 1 is fully opaque. Modern CSS also supports `rgb(59 91 219 / 50%)` — the space-separated slash notation. Do not confuse this with `opacity`, which makes the whole element including its children semi-transparent.',
        code: '/* Alpha in color value — children stay opaque */\n.overlay { background: rgba(0, 0, 0, 0.5); }\n\n/* opacity — affects element AND all children */\n.faded { opacity: 0.5; }',
        codeLang: 'css',
      },
      {
        sectionId: 'background',
        heading_ru: 'Свойства фона',
        heading_en: 'Background Properties',
        text_ru: 'Свойство `background` — это сокращение (шортхенд), объединяющее цвет, изображение, позицию, размер и повторение. Для фоновых изображений ключевые настройки: `background-size: cover` (заполнить контейнер сохраняя пропорции) и `background-position: center` (центрировать). Можно комбинировать несколько фонов через запятую — например, градиент поверх изображения.',
        text_en: 'The `background` property is a shorthand that combines color, image, position, size, and repeat. For background images, key settings are `background-size: cover` (fill the container while preserving aspect ratio) and `background-position: center` (keep it centered). You can stack multiple backgrounds with commas — for example a gradient overlay on top of an image.',
        code: '.card {\n  background:\n    linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)),\n    url("photo.jpg") center/cover no-repeat;\n}',
        codeLang: 'css',
      },
      {
        sectionId: 'gradient',
        heading_ru: 'Градиенты',
        heading_en: 'Gradients',
        text_ru: '`linear-gradient` создаёт плавный переход между цветами вдоль прямой линии. Укажите угол (`135deg`) или направление (`to right`, `to bottom right`), затем перечислите цвета с необязательными стоп-позициями. `radial-gradient` создаёт градиент, расходящийся из точки. Для анимированных фонов используют `background-size` больше 100% и `@keyframes`.',
        text_en: '`linear-gradient` creates a smooth transition between colors along a straight line. Specify an angle (`135deg`) or a direction (`to right`, `to bottom right`), then list colors with optional stop positions. `radial-gradient` radiates from a central point. For animated backgrounds, use a `background-size` larger than 100% and `@keyframes`.',
        code: '/* Two-color diagonal */\n.btn { background: linear-gradient(135deg, #667eea, #764ba2); }\n\n/* Three-color with positions */\n.rainbow {\n  background: linear-gradient(\n    90deg,\n    #ff6b6b 0%,\n    #ffd93d 50%,\n    #6bcb77 100%\n  );\n}',
        codeLang: 'css',
      },
    ],
  },
  editorTask: {
    title_ru: 'Профильный баннер',
    title_en: 'Profile Banner',
    instructions_ru: 'Создайте профильный баннер с градиентным фоном (от `#3B5BDB` до `#7048E8`), аватаром-кругом, именем пользователя и полупрозрачной подписью. Используйте RGBA для overlay-эффекта.',
    instructions_en: 'Build a profile banner with a gradient background (from `#3B5BDB` to `#7048E8`), a circular avatar, a username, and a translucent subtitle. Use RGBA for an overlay effect.',
    activeTabs: ['html', 'css'],
    starterCode: {
      html: '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <title>Profile Banner</title>\n  <link rel="stylesheet" href="style.css">\n</head>\n<body>\n  <div class="banner">\n    <div class="avatar">AK</div>\n    <h2 class="name">Alex Kim</h2>\n    <p class="role">Front-End Developer</p>\n    <span class="badge">Open to work</span>\n  </div>\n</body>\n</html>',
      css: '/* Banner with gradient background */\n.banner {\n  \n}\n\n/* Circular avatar */\n.avatar {\n  width: 72px;\n  height: 72px;\n  border-radius: 50%;\n  \n}\n\n/* Name and role text */\n.name { }\n.role { }\n\n/* Translucent badge using rgba */\n.badge {\n  \n}',
    },
    hints_ru: [
      '`background: linear-gradient(135deg, #3B5BDB, #7048E8)` для фона баннера',
      'Для аватара: `background: rgba(255,255,255,0.2)` и `color: #fff`',
      'Для бейджа: `background: rgba(255,255,255,0.15)` и `border: 1px solid rgba(255,255,255,0.3)`',
      'Добавьте `text-align: center` и `padding: 40px 20px` к баннеру',
    ],
    hints_en: [
      '`background: linear-gradient(135deg, #3B5BDB, #7048E8)` for the banner background',
      'For the avatar: `background: rgba(255,255,255,0.2)` and `color: #fff`',
      'For the badge: `background: rgba(255,255,255,0.15)` and `border: 1px solid rgba(255,255,255,0.3)`',
      'Add `text-align: center` and `padding: 40px 20px` to the banner',
    ],
  },
  keyTerms: [
    {
      term_ru: 'HEX-цвет',
      term_en: 'HEX color',
      definition_ru: 'Шестнадцатеричная запись цвета в формате #RRGGBB, где каждая пара — значение канала от 00 до FF.',
      definition_en: 'Hexadecimal color notation in the form #RRGGBB, where each pair is a channel value from 00 to FF.',
      example_ru: '`#FF5733` — насыщенный оранжево-красный',
      example_en: '`#FF5733` — a vivid orange-red',
    },
    {
      term_ru: 'RGB',
      term_en: 'RGB',
      definition_ru: 'Цветовая модель, описывающая цвет через интенсивность красного (R), зелёного (G) и синего (B) каналов от 0 до 255.',
      definition_en: 'A color model describing color via the intensity of Red, Green, and Blue channels, each from 0 to 255.',
      example_ru: '`rgb(255, 87, 51)` — тот же оранжево-красный',
      example_en: '`rgb(255, 87, 51)` — the same orange-red',
    },
    {
      term_ru: 'HSL',
      term_en: 'HSL',
      definition_ru: 'Цветовая модель: тон (Hue, 0–360°), насыщенность (Saturation, 0–100%), светлота (Lightness, 0–100%).',
      definition_en: 'Color model: Hue (0–360°), Saturation (0–100%), Lightness (0–100%).',
      example_ru: '`hsl(11, 100%, 60%)` — тот же оранжево-красный через HSL',
      example_en: '`hsl(11, 100%, 60%)` — the same orange-red expressed in HSL',
    },
    {
      term_ru: 'linear-gradient',
      term_en: 'linear-gradient',
      definition_ru: 'CSS-функция, создающая плавный переход между двумя и более цветами вдоль прямой линии.',
      definition_en: 'A CSS function that creates a smooth transition between two or more colors along a straight line.',
      example_ru: '`linear-gradient(to right, #3B5BDB, #7048E8)`',
      example_en: '`linear-gradient(to right, #3B5BDB, #7048E8)`',
    },
    {
      term_ru: 'rgba / alpha-канал',
      term_en: 'rgba / alpha channel',
      definition_ru: 'Расширение RGB с четвёртым параметром — прозрачностью (0 = полностью прозрачный, 1 = непрозрачный).',
      definition_en: 'An extension of RGB with a fourth alpha parameter — transparency (0 = fully transparent, 1 = fully opaque).',
      example_ru: '`rgba(0, 0, 0, 0.5)` — чёрный с 50% прозрачностью',
      example_en: '`rgba(0, 0, 0, 0.5)` — black at 50% transparency',
    },
  ],
  didYouKnow: [
    {
      text_ru: 'CSS поддерживает более 140 именованных цветов — от классических `red` и `blue` до экзотических `rebeccapurple`. Последний был добавлен в честь Ребекки Мейер, дочери веб-разработчика Эрика Мейера.',
      text_en: 'CSS supports more than 140 named colors — from classic `red` and `blue` to exotic `rebeccapurple`. The last one was added in honor of Rebecca Meyer, the daughter of web developer Eric Meyer.',
    },
    {
      text_ru: 'Браузеры поддерживают относительно новый формат `color-mix(in oklch, red 50%, blue)`, который позволяет смешивать цвета прямо в CSS без JavaScript. OKLCH — более перцептивно равномерное пространство, чем sRGB.',
      text_en: 'Browsers support the relatively new `color-mix(in oklch, red 50%, blue)` function, which mixes colors directly in CSS without JavaScript. OKLCH is a perceptually more uniform color space than sRGB.',
    },
  ],
  quiz: [
    {
      id: 'q1',
      text_ru: 'Какое значение alpha в `rgba(0,0,0,0.3)` означает?',
      text_en: 'What does the alpha value in `rgba(0,0,0,0.3)` mean?',
      options_ru: ['Элемент на 30% непрозрачен', 'Элемент на 70% непрозрачен', 'Элемент полностью непрозрачен', 'Элемент полностью прозрачен'],
      options_en: ['The element is 30% opaque', 'The element is 70% opaque', 'The element is fully opaque', 'The element is fully transparent'],
      correctIndex: 0,
      explanation_ru: 'Альфа 0.3 означает 30% непрозрачности (70% прозрачности). 0 — полностью прозрачный, 1 — полностью непрозрачный.',
      explanation_en: 'An alpha of 0.3 means 30% opaque (70% transparent). 0 is fully transparent, 1 is fully opaque.',
    },
    {
      id: 'q2',
      text_ru: 'Чем отличается `opacity: 0.5` от `rgba(..., 0.5)` для фона?',
      text_en: 'How does `opacity: 0.5` differ from `rgba(..., 0.5)` for backgrounds?',
      options_ru: ['Нет разницы', '`opacity` делает прозрачным весь элемент включая дочерние', '`rgba` делает прозрачным весь элемент включая дочерние', '`opacity` работает только для текста'],
      options_en: ['There is no difference', '`opacity` makes the whole element including children transparent', '`rgba` makes the whole element including children transparent', '`opacity` only works on text'],
      correctIndex: 1,
      explanation_ru: '`opacity` применяется ко всему элементу, включая вложенные. `rgba` влияет только на конкретное свойство (цвет фона, текста), не затрагивая дочерние элементы.',
      explanation_en: '`opacity` applies to the entire element including its descendants. `rgba` affects only the specific property (background, text color) without touching child elements.',
    },
    {
      id: 'q3',
      text_ru: 'Какая CSS-функция создаёт радиальный градиент?',
      text_en: 'Which CSS function creates a radial gradient?',
      options_ru: ['linear-gradient()', 'radial-gradient()', 'conic-gradient()', 'circle-gradient()'],
      options_en: ['linear-gradient()', 'radial-gradient()', 'conic-gradient()', 'circle-gradient()'],
      correctIndex: 1,
      explanation_ru: '`radial-gradient()` создаёт градиент, расходящийся из центральной точки по кругу или эллипсу.',
      explanation_en: '`radial-gradient()` creates a gradient that radiates from a central point in a circular or elliptical shape.',
    },
    {
      id: 'q4',
      text_ru: 'Что означает второй параметр в `hsl(200, 80%, 50%)`?',
      text_en: 'What does the second parameter in `hsl(200, 80%, 50%)` represent?',
      options_ru: ['Тон (оттенок)', 'Насыщенность', 'Светлота', 'Прозрачность'],
      options_en: ['Hue', 'Saturation', 'Lightness', 'Alpha'],
      correctIndex: 1,
      explanation_ru: 'В HSL: первый параметр — тон (0–360°), второй — насыщенность (0–100%), третий — светлота (0–100%).',
      explanation_en: 'In HSL: the first parameter is hue (0–360°), the second is saturation (0–100%), the third is lightness (0–100%).',
    },
    {
      id: 'q5',
      text_ru: 'Как наложить градиент поверх фонового изображения?',
      text_en: 'How do you layer a gradient on top of a background image?',
      options_ru: ['Использовать два отдельных элемента', 'Перечислить фоны через запятую: градиент, затем изображение', 'CSS не поддерживает несколько фонов', 'Использовать `opacity` на изображении'],
      options_en: ['Use two separate elements', 'List backgrounds with a comma: gradient first, then image', 'CSS does not support multiple backgrounds', 'Use `opacity` on the image'],
      correctIndex: 1,
      explanation_ru: 'CSS поддерживает несколько значений `background` через запятую. Первый слой рисуется сверху: `background: linear-gradient(...), url("img.jpg")`.',
      explanation_en: 'CSS supports multiple `background` values separated by commas. The first layer is drawn on top: `background: linear-gradient(...), url("img.jpg")`.',
    },
  ],
}
