import type { Lesson } from '@/types/lesson'

export const htmlTextHeadings: Lesson = {
  slug: 'html-text-headings',
  category: 'HTML',
  readTime: 7,
  icon: '📝',
  title_ru: 'Текст и заголовки HTML',
  title_en: 'HTML Text & Headings',
  description_ru: 'Изучите теги заголовков h1–h6, абзацы, форматирование текста и цитаты для правильной структуры контента.',
  description_en: 'Learn heading tags h1–h6, paragraphs, text formatting, and blockquotes for proper content structure.',

  sections: [
    { id: 'headings', title_ru: 'Заголовки h1–h6', title_en: 'Headings h1–h6' },
    { id: 'paragraphs', title_ru: 'Абзацы', title_en: 'Paragraphs' },
    { id: 'text-formatting', title_ru: 'Форматирование текста', title_en: 'Text Formatting' },
    { id: 'blockquote', title_ru: 'Цитаты', title_en: 'Blockquotes' },
    { id: 'key-terms', title_ru: 'Ключевые термины', title_en: 'Key Terms' },
  ],

  slides: [
    {
      id: 'slide-1',
      type: 'title',
      title_ru: 'Текст и заголовки HTML',
      title_en: 'HTML Text & Headings',
      body_ru: 'Правильная структура текста — основа любого сайта. Заголовки, абзацы и форматирование делают контент понятным для людей и поисковиков.',
      body_en: 'Proper text structure is the foundation of any website. Headings, paragraphs, and formatting make content clear for both people and search engines.',
    },
    {
      id: 'slide-2',
      type: 'analogy',
      title_ru: 'Заголовки — как оглавление книги',
      title_en: 'Headings are like a book\'s table of contents',
      body_ru: 'Представьте книгу: название — самый крупный текст, главы чуть меньше, подразделы ещё меньше. Так же работают заголовки в HTML: h1 — самый важный, h6 — наименее значимый.',
      body_en: 'Imagine a book: the title is the largest text, chapters a bit smaller, subsections smaller still. HTML headings work the same way: h1 is the most important, h6 the least.',
      visual: {
        kind: 'emoji',
        emojis: ['📚', '📖', '🔖'],
        caption_ru: 'Иерархия заголовков как структура книги',
        caption_en: 'Heading hierarchy mirrors a book\'s structure',
      },
      bullets: [
        { text_ru: 'h1 — название страницы, только один на странице', text_en: 'h1 — page title, only one per page' },
        { text_ru: 'h2 — основные разделы', text_en: 'h2 — main sections' },
        { text_ru: 'h3–h6 — подразделы разного уровня', text_en: 'h3–h6 — subsections of varying depth' },
      ],
    },
    {
      id: 'slide-3',
      type: 'concept',
      title_ru: 'Шесть уровней заголовков',
      title_en: 'Six Levels of Headings',
      body_ru: 'HTML предоставляет шесть уровней заголовков. Каждый уровень имеет меньший визуальный размер и меньший вес для SEO.',
      body_en: 'HTML provides six heading levels. Each level has a smaller visual size and lower SEO weight.',
      code: '<h1>Главный заголовок страницы</h1>\n<h2>Название раздела</h2>\n<h3>Название подраздела</h3>\n<h4>Подпункт</h4>\n<h5>Мелкий подпункт</h5>\n<h6>Самый мелкий заголовок</h6>',
      codeLang: 'html',
    },
    {
      id: 'slide-4',
      type: 'compare',
      title_ru: 'h1 против h6: в чём разница?',
      title_en: 'h1 vs h6: What is the Difference?',
      body_ru: 'Заголовки отличаются не только размером, но и смысловой важностью для поисковых систем.',
      body_en: 'Headings differ not only in size but also in their semantic importance for search engines.',
      compareLeft: {
        label_ru: 'h1 — главный заголовок',
        label_en: 'h1 — Main Heading',
        items_ru: ['Один на всю страницу', 'Самый крупный визуально', 'Максимальный вес в SEO', 'Описывает тему страницы целиком'],
        items_en: ['One per page', 'Largest visually', 'Maximum SEO weight', 'Describes the entire page topic'],
        color: 'green',
      },
      compareRight: {
        label_ru: 'h6 — самый мелкий',
        label_en: 'h6 — Smallest Heading',
        items_ru: ['Можно использовать много раз', 'Самый мелкий визуально', 'Минимальный вес в SEO', 'Для деталей глубокой вложенности'],
        items_en: ['Can be used many times', 'Smallest visually', 'Minimal SEO weight', 'For deeply nested details'],
        color: 'amber',
      },
    },
    {
      id: 'slide-5',
      type: 'concept',
      title_ru: 'Абзацы и перенос строк',
      title_en: 'Paragraphs and Line Breaks',
      body_ru: 'Тег <p> создаёт абзац с отступом сверху и снизу. <br> делает перенос строки внутри текста без создания нового абзаца.',
      body_en: 'The <p> tag creates a paragraph with top and bottom margins. <br> creates a line break within text without starting a new paragraph.',
      code: '<p>Первый абзац текста. Браузер добавит\nотступ автоматически.</p>\n\n<p>Второй абзац.<br>Эта строка начнётся\nс новой строки, но в том же абзаце.</p>',
      codeLang: 'html',
    },
    {
      id: 'slide-6',
      type: 'code-anim',
      title_ru: 'Строим структуру блога',
      title_en: 'Building a Blog Post Structure',
      body_ru: 'Посмотрите, как шаг за шагом собирается типичная структура статьи в блоге.',
      body_en: 'Watch how a typical blog post structure is assembled step by step.',
      animMode: 'preview',
      animSteps: [
        {
          code: '<h1>Как научиться программировать</h1>',
          comment_ru: 'Начинаем с главного заголовка страницы — h1',
          comment_en: 'Start with the main page heading — h1',
          preview: '<h1>Как научиться программировать</h1>',
        },
        {
          code: '<h1>Как научиться программировать</h1>\n<p>Программирование — это навык, который доступен каждому. В этой статье мы расскажем, с чего начать.</p>',
          comment_ru: 'Добавляем вводный абзац с тегом p',
          comment_en: 'Add an introductory paragraph with the p tag',
          preview: '<h1>Как научиться программировать</h1><p>Программирование — это навык, который доступен каждому.</p>',
        },
        {
          code: '<h1>Как научиться программировать</h1>\n<p>Программирование — навык, доступный каждому.</p>\n\n<h2>Шаг 1: Выберите язык</h2>\n<p>Для начала подойдут Python или JavaScript.</p>',
          comment_ru: 'Добавляем раздел с заголовком h2',
          comment_en: 'Add a section with an h2 heading',
          preview: '<h1>Как научиться программировать</h1><p>Введение...</p><h2>Шаг 1: Выберите язык</h2><p>Для начала...</p>',
        },
        {
          code: '<h1>Как научиться программировать</h1>\n<p>Программирование — навык, доступный каждому.</p>\n\n<h2>Шаг 1: Выберите язык</h2>\n<p>Для начала подойдут Python или JavaScript.</p>\n\n<h3>Почему JavaScript?</h3>\n<p>JavaScript работает прямо в браузере — <strong>идеально для веба</strong>.</p>',
          comment_ru: 'Добавляем подраздел h3 и выделяем важное слово через strong',
          comment_en: 'Add an h3 subsection and highlight a key word with strong',
          preview: 'Полная структура блога с h1, h2, h3 и форматированием',
        },
      ],
    },
    {
      id: 'slide-7',
      type: 'concept',
      title_ru: 'Форматирование текста',
      title_en: 'Text Formatting',
      body_ru: 'HTML предлагает несколько тегов для смыслового выделения текста. Они несут семантический смысл, а не просто визуальный эффект.',
      body_en: 'HTML offers several tags for semantic text emphasis. They carry meaning, not just a visual effect.',
      code: '<!-- Важное / Important -->\n<strong>Очень важно!</strong>\n\n<!-- Акцент / Emphasis -->\n<em>Это интересно</em>\n\n<!-- Цитата в строке / Inline quote -->\n<q>Мир прекрасен</q>\n\n<!-- Код / Code -->\n<code>console.log("Привет")</code>',
      codeLang: 'html',
    },
    {
      id: 'slide-8',
      type: 'tip',
      title_ru: 'Blockquote — оформление цитат',
      title_en: 'Blockquote — Formatting Quotes',
      body_ru: 'Тег <blockquote> используется для длинных цитат. Браузер добавляет отступ. Атрибут cite указывает источник.',
      body_en: 'The <blockquote> tag is used for long quotations. The browser adds an indent. The cite attribute specifies the source.',
      code: '<blockquote cite="https://ru.wikipedia.org">\n  <p>Знание — сила.</p>\n</blockquote>\n<p>— Фрэнсис Бэкон</p>',
      codeLang: 'html',
      bullets: [
        { text_ru: 'Используйте blockquote для цитат от других авторов', text_en: 'Use blockquote for quotes from other authors' },
        { text_ru: 'Атрибут cite — URL источника цитаты', text_en: 'The cite attribute holds the source URL' },
        { text_ru: 'Имя автора можно добавить через <cite> или <footer>', text_en: 'Author name can be added via <cite> or <footer>' },
      ],
    },
    {
      id: 'slide-9',
      type: 'practice-cta',
      title_ru: 'Создайте свою статью!',
      title_en: 'Create Your Own Article!',
      body_ru: 'Напишите HTML-разметку небольшой статьи с заголовками, абзацами, выделением текста и цитатой.',
      body_en: 'Write the HTML markup for a short article with headings, paragraphs, text emphasis, and a blockquote.',
    },
  ],

  content: {
    intro_ru: 'Текст — главный контент большинства сайтов. HTML предоставляет богатый набор тегов для структурирования текста: от заголовков разного уровня до выделения важных слов. Правильная разметка помогает не только пользователям, но и поисковым системам понять вашу страницу.',
    intro_en: 'Text is the main content of most websites. HTML provides a rich set of tags for structuring text: from multi-level headings to highlighting important words. Proper markup helps not only users but also search engines understand your page.',
    blocks: [
      {
        sectionId: 'headings',
        heading_ru: 'Заголовки h1–h6',
        heading_en: 'Headings h1–h6',
        text_ru: 'HTML имеет шесть уровней заголовков — от h1 до h6. h1 — самый важный, используется один раз для обозначения темы страницы. h2 делит страницу на разделы, h3 — на подразделы. Поисковые системы придают большое значение содержимому заголовков при индексации.',
        text_en: 'HTML has six heading levels — h1 through h6. h1 is the most important, used once to describe the page topic. h2 divides the page into sections, h3 into subsections. Search engines place great importance on heading content during indexing.',
        code: '<h1>Путеводитель по Токио</h1>\n<h2>Где поесть</h2>\n<h3>Суши-рестораны</h3>\n<h3>Рамен-лавки</h3>\n<h2>Достопримечательности</h2>',
        codeLang: 'html',
      },
      {
        sectionId: 'paragraphs',
        heading_ru: 'Абзацы и перенос строк',
        heading_en: 'Paragraphs and Line Breaks',
        text_ru: 'Тег <p> создаёт абзац — блочный элемент с вертикальными отступами. Браузер автоматически «схлопывает» пробелы и переносы строк внутри HTML. Чтобы принудительно перенести строку внутри абзаца — используйте <br>. Не злоупотребляйте <br>: для разделения смысловых блоков лучше использовать новый <p>.',
        text_en: 'The <p> tag creates a paragraph — a block element with vertical margins. The browser automatically collapses spaces and line breaks within HTML. To force a line break inside a paragraph, use <br>. Do not overuse <br>: for separating meaningful blocks, a new <p> is better.',
        code: '<p>Токио — крупнейший город мира.\nЕго население превышает 13 миллионов человек.</p>\n\n<p>Адрес: ул. Сакура, 5<br>Токио, Япония</p>',
        codeLang: 'html',
      },
      {
        sectionId: 'text-formatting',
        heading_ru: 'Семантическое форматирование',
        heading_en: 'Semantic Text Formatting',
        text_ru: 'Для выделения текста используйте семантические теги: <strong> — для критически важной информации (выводится жирным), <em> — для акцента (выводится курсивом). Не используйте <b> и <i> — они несут чисто визуальный смысл без семантики.',
        text_en: 'For text emphasis, use semantic tags: <strong> for critically important information (renders bold), <em> for stress emphasis (renders italic). Avoid <b> and <i> — they carry only visual meaning without semantics.',
        code: '<p>Рейс вылетает в <strong>14:30</strong>.\nПожалуйста, прибудьте <em>заранее</em>.</p>',
        codeLang: 'html',
      },
      {
        sectionId: 'blockquote',
        heading_ru: 'Цитаты: blockquote и q',
        heading_en: 'Quotes: blockquote and q',
        text_ru: '<blockquote> используется для длинных цитат — браузер делает отступ. <q> — для коротких цитат внутри строки (браузер добавляет кавычки автоматически). Оба тега поддерживают атрибут cite с URL источника.',
        text_en: '<blockquote> is used for long quotations — the browser adds an indent. <q> is for short inline quotes (the browser adds quotation marks automatically). Both tags support the cite attribute with the source URL.',
        code: '<blockquote cite="https://example.com/source">\n  <p>Лучший способ предсказать будущее — создать его.</p>\n</blockquote>\n<p>Как сказал <q>великий учёный</q>, наука — сила.</p>',
        codeLang: 'html',
      },
    ],
  },

  editorTask: {
    title_ru: 'Напишите статью о любимом городе',
    title_en: 'Write an Article About Your Favourite City',
    instructions_ru: 'Создайте HTML-страницу статьи о городе. Используйте h1 для названия, h2 для разделов (история, достопримечательности, еда), p для текста, strong и em для выделений, blockquote для цитаты о городе.',
    instructions_en: 'Create an HTML article page about a city. Use h1 for the title, h2 for sections (history, sights, food), p for text, strong and em for emphasis, and blockquote for a quote about the city.',
    activeTabs: ['html'],
    starterCode: {
      html: '<!-- Статья о городе / Article about a city -->\n\n<!-- Заголовок страницы (h1) / Page title (h1) -->\n\n<!-- Вводный абзац (p) / Intro paragraph (p) -->\n\n<!-- Раздел: История (h2 + p) / Section: History (h2 + p) -->\n\n<!-- Раздел: Достопримечательности (h2 + p) / Section: Sights (h2 + p) -->\n\n<!-- Цитата о городе (blockquote) / Quote about the city (blockquote) -->\n',
    },
    hints_ru: [
      'Начните с <h1>Название города</h1>',
      'Для каждого раздела используйте <h2>Название раздела</h2>',
      'Выделите важные факты тегом <strong>, например, год основания',
      'Добавьте цитату: <blockquote><p>текст цитаты</p></blockquote>',
    ],
    hints_en: [
      'Start with <h1>City Name</h1>',
      'For each section, use <h2>Section Name</h2>',
      'Highlight key facts with <strong>, e.g. the founding year',
      'Add a quote: <blockquote><p>quote text</p></blockquote>',
    ],
  },

  keyTerms: [
    {
      term_ru: 'h1–h6',
      term_en: 'h1–h6',
      definition_ru: 'Теги заголовков шести уровней. h1 — самый важный, h6 — наименее значимый.',
      definition_en: 'Heading tags of six levels. h1 is the most important, h6 the least.',
      example_ru: '<h1>Заголовок страницы</h1>',
      example_en: '<h1>Page Title</h1>',
    },
    {
      term_ru: 'Абзац',
      term_en: 'Paragraph',
      definition_ru: 'Блочный элемент <p>, создающий смысловой блок текста с вертикальными отступами.',
      definition_en: 'A block element <p> that creates a meaningful text block with vertical margins.',
      example_ru: '<p>Текст абзаца.</p>',
      example_en: '<p>Paragraph text.</p>',
    },
    {
      term_ru: 'strong',
      term_en: 'strong',
      definition_ru: 'Тег для обозначения критически важной информации. Отображается жирным шрифтом.',
      definition_en: 'Tag for marking critically important information. Renders as bold text.',
      example_ru: '<strong>Важно!</strong>',
      example_en: '<strong>Important!</strong>',
    },
    {
      term_ru: 'em',
      term_en: 'em',
      definition_ru: 'Тег акцента, выделяет слово с интонационным ударением. Отображается курсивом.',
      definition_en: 'Emphasis tag marking a word with stress accent. Renders as italic text.',
      example_ru: '<em>именно это</em>',
      example_en: '<em>exactly this</em>',
    },
    {
      term_ru: 'blockquote',
      term_en: 'blockquote',
      definition_ru: 'Блочный тег для оформления длинных цитат из внешних источников.',
      definition_en: 'Block tag for formatting long quotations from external sources.',
      example_ru: '<blockquote><p>Цитата.</p></blockquote>',
      example_en: '<blockquote><p>A quote.</p></blockquote>',
    },
  ],

  didYouKnow: [
    {
      text_ru: 'Google использует тег h1 как один из главных сигналов при определении темы страницы. Страница без h1 хуже ранжируется в поиске.',
      text_en: 'Google uses the h1 tag as one of the main signals when determining a page\'s topic. A page without h1 ranks worse in search results.',
    },
    {
      text_ru: 'В HTML 5.2 была попытка разрешить несколько h1 в разных секциях, но идею отменили. Сегодня рекомендуется использовать только один h1 на странице.',
      text_en: 'HTML 5.2 attempted to allow multiple h1 elements in different sections, but the idea was reversed. Today the recommendation is to use only one h1 per page.',
    },
  ],

  quiz: [
    {
      id: 'q1',
      text_ru: 'Сколько тегов h1 рекомендуется использовать на одной странице?',
      text_en: 'How many h1 tags are recommended on a single page?',
      options_ru: ['Сколько угодно', 'Ровно шесть', 'Только один', 'Не более трёх'],
      options_en: ['As many as you like', 'Exactly six', 'Only one', 'No more than three'],
      correctIndex: 2,
      explanation_ru: 'На странице рекомендуется один h1 — он описывает главную тему страницы и важен для SEO.',
      explanation_en: 'One h1 per page is recommended — it describes the main page topic and is important for SEO.',
    },
    {
      id: 'q2',
      text_ru: 'Какой тег используется для создания абзаца?',
      text_en: 'Which tag is used to create a paragraph?',
      options_ru: ['<br>', '<para>', '<p>', '<div>'],
      options_en: ['<br>', '<para>', '<p>', '<div>'],
      correctIndex: 2,
      explanation_ru: '<p> — тег абзаца. Он создаёт блочный элемент с вертикальными отступами.',
      explanation_en: '<p> is the paragraph tag. It creates a block element with vertical margins.',
    },
    {
      id: 'q3',
      text_ru: 'В чём семантическая разница между <strong> и <b>?',
      text_en: 'What is the semantic difference between <strong> and <b>?',
      options_ru: ['Никакой разницы нет', '<strong> обозначает важность, <b> — только визуальный жирный', '<b> обозначает важность, <strong> — визуальный', 'Они используются для разных браузеров'],
      options_en: ['There is no difference', '<strong> marks importance, <b> is only visual bold', '<b> marks importance, <strong> is visual', 'They are used for different browsers'],
      correctIndex: 1,
      explanation_ru: '<strong> несёт семантику важности (скринридеры делают акцент), <b> — только визуальный жирный шрифт без смысла.',
      explanation_en: '<strong> carries the semantics of importance (screen readers emphasise it), <b> is only visual bold text without meaning.',
    },
    {
      id: 'q4',
      text_ru: 'Что делает тег <br>?',
      text_en: 'What does the <br> tag do?',
      options_ru: ['Создаёт новый абзац', 'Добавляет горизонтальную линию', 'Делает перенос строки внутри текста', 'Выделяет текст жирным'],
      options_en: ['Creates a new paragraph', 'Adds a horizontal line', 'Creates a line break within text', 'Makes text bold'],
      correctIndex: 2,
      explanation_ru: '<br> — пустой элемент, который принудительно переносит текст на новую строку без создания нового абзаца.',
      explanation_en: '<br> is a void element that forces a line break without creating a new paragraph.',
    },
    {
      id: 'q5',
      text_ru: 'Какой тег используется для длинных цитат?',
      text_en: 'Which tag is used for long quotations?',
      options_ru: ['<quote>', '<q>', '<blockquote>', '<cite>'],
      options_en: ['<quote>', '<q>', '<blockquote>', '<cite>'],
      correctIndex: 2,
      explanation_ru: '<blockquote> — блочный тег для длинных цитат. <q> используется для коротких цитат внутри строки.',
      explanation_en: '<blockquote> is a block tag for long quotations. <q> is used for short inline quotes.',
    },
  ],
}
