import type { Lesson } from '@/types/lesson'

export const htmlLists: Lesson = {
  slug: 'html-lists',
  category: 'HTML',
  readTime: 7,
  icon: '📋',
  title_ru: 'Списки HTML',
  title_en: 'HTML Lists',
  description_ru: 'Освойте маркированные, нумерованные и вложенные списки, а также списки определений для структурирования данных.',
  description_en: 'Master unordered, ordered, and nested lists, as well as definition lists for structuring data.',

  sections: [
    { id: 'unordered', title_ru: 'Маркированные списки', title_en: 'Unordered Lists' },
    { id: 'ordered', title_ru: 'Нумерованные списки', title_en: 'Ordered Lists' },
    { id: 'nested', title_ru: 'Вложенные списки', title_en: 'Nested Lists' },
    { id: 'definition', title_ru: 'Списки определений', title_en: 'Definition Lists' },
    { id: 'key-terms', title_ru: 'Ключевые термины', title_en: 'Key Terms' },
  ],

  slides: [
    {
      id: 'slide-1',
      type: 'title',
      title_ru: 'Списки HTML',
      title_en: 'HTML Lists',
      body_ru: 'Списки — один из самых часто используемых элементов веба. Навигация, шаги инструкции, каталог товаров — всё это строится на HTML-списках.',
      body_en: 'Lists are among the most-used elements on the web. Navigation menus, instruction steps, product catalogues — all are built on HTML lists.',
      visual: { kind: 'emoji', emojis: ['📋', '🔢', '✅'] },
    },
    {
      id: 'slide-2',
      type: 'analogy',
      title_ru: 'Списки — как разные типы записок',
      title_en: 'Lists are like different kinds of notes',
      body_ru: 'Список покупок не требует порядка — подойдёт маркированный. Рецепт требует точного порядка шагов — нужен нумерованный. Словарь требует терминов и определений — используем список определений.',
      body_en: 'A shopping list needs no order — use an unordered list. A recipe requires exact step order — use an ordered list. A glossary needs terms and definitions — use a definition list.',
      visual: {
        kind: 'emoji',
        emojis: ['🛒', '📋', '📖'],
        caption_ru: 'Разные задачи — разные типы списков',
        caption_en: 'Different tasks call for different list types',
      },
      bullets: [
        { text_ru: 'ul — маркированный, когда порядок не важен', text_en: 'ul — unordered, when order does not matter' },
        { text_ru: 'ol — нумерованный, когда важна последовательность', text_en: 'ol — ordered, when sequence matters' },
        { text_ru: 'dl — список определений для терминов и описаний', text_en: 'dl — definition list for terms and descriptions' },
      ],
    },
    {
      id: 'slide-3',
      type: 'concept',
      title_ru: 'Маркированный список (ul)',
      title_en: 'Unordered List (ul)',
      body_ru: 'Тег <ul> создаёт маркированный список. Каждый пункт оборачивается в тег <li>. Браузер ставит маркеры (буллиты) автоматически.',
      body_en: 'The <ul> tag creates a bulleted list. Each item is wrapped in a <li> tag. The browser adds bullet markers automatically.',
      code: '<ul>\n  <li>Яблоки</li>\n  <li>Бананы</li>\n  <li>Апельсины</li>\n</ul>',
      codeLang: 'html',
    },
    {
      id: 'slide-4',
      type: 'compare',
      title_ru: 'ul против ol: когда что использовать?',
      title_en: 'ul vs ol: When to Use Which?',
      body_ru: 'Выбор между маркированным и нумерованным списком зависит от смысла: важен ли порядок пунктов.',
      body_en: 'The choice between unordered and ordered lists depends on meaning: does the order of items matter?',
      compareLeft: {
        label_ru: 'ul — маркированный',
        label_en: 'ul — Unordered',
        items_ru: ['Порядок не важен', 'Маркеры: •, ◦, ▪', 'Список покупок', 'Навигационное меню', 'Список функций продукта'],
        items_en: ['Order does not matter', 'Markers: •, ◦, ▪', 'Shopping list', 'Navigation menu', 'Product feature list'],
        color: 'blue',
      },
      compareRight: {
        label_ru: 'ol — нумерованный',
        label_en: 'ol — Ordered',
        items_ru: ['Порядок критически важен', 'Нумерация: 1, 2, 3...', 'Шаги рецепта', 'Инструкция по установке', 'Топ-10 рейтинг'],
        items_en: ['Order is critical', 'Numbers: 1, 2, 3...', 'Recipe steps', 'Installation guide', 'Top-10 ranking'],
        color: 'green',
      },
    },
    {
      id: 'slide-5',
      type: 'concept',
      title_ru: 'Нумерованный список (ol)',
      title_en: 'Ordered List (ol)',
      body_ru: 'Тег <ol> создаёт нумерованный список. Атрибут start задаёт начальный номер, type — тип нумерации.',
      body_en: 'The <ol> tag creates a numbered list. The start attribute sets the starting number; type sets the numbering style.',
      code: '<ol>\n  <li>Вскипятить воду</li>\n  <li>Засыпать макароны</li>\n  <li>Варить 8 минут</li>\n</ol>\n\n<!-- Начать с 5, буквенная нумерация -->\n<ol start="5" type="A">\n  <li>Пятый пункт</li>\n  <li>Шестой пункт</li>\n</ol>',
      codeLang: 'html',
    },
    {
      id: 'slide-6',
      type: 'code-anim',
      title_ru: 'Строим навигационное меню',
      title_en: 'Building a Navigation Menu',
      body_ru: 'Посмотрите, как шаг за шагом создаётся навигационное меню сайта с помощью ul и li.',
      body_en: 'Watch how a site navigation menu is built step by step using ul and li.',
      animMode: 'preview',
      animSteps: [
        {
          code: '<nav>',
          comment_ru: 'Оборачиваем меню в семантический тег nav',
          comment_en: 'Wrap the menu in the semantic nav tag',
          preview: '<nav></nav>',
        },
        {
          code: '<nav>\n  <ul>\n  </ul>\n</nav>',
          comment_ru: 'Внутри nav добавляем ненумерованный список ul',
          comment_en: 'Inside nav, add an unordered list ul',
          preview: '<nav><ul></ul></nav>',
        },
        {
          code: '<nav>\n  <ul>\n    <li>Главная</li>\n    <li>О нас</li>\n    <li>Услуги</li>\n  </ul>\n</nav>',
          comment_ru: 'Добавляем пункты меню через li',
          comment_en: 'Add menu items as li elements',
          preview: '<nav><ul><li>Главная</li><li>О нас</li><li>Услуги</li></ul></nav>',
        },
        {
          code: '<nav>\n  <ul>\n    <li><a href="/">Главная</a></li>\n    <li><a href="/about">О нас</a></li>\n    <li><a href="/services">Услуги</a></li>\n    <li><a href="/contact">Контакты</a></li>\n  </ul>\n</nav>',
          comment_ru: 'Оборачиваем каждый пункт в ссылку — меню готово!',
          comment_en: 'Wrap each item in a link — the menu is complete!',
          preview: 'Готовое навигационное меню со ссылками',
        },
      ],
    },
    {
      id: 'slide-7',
      type: 'concept',
      title_ru: 'Вложенные списки',
      title_en: 'Nested Lists',
      body_ru: 'Списки можно вкладывать друг в друга. Новый список помещается внутрь тега <li> родительского списка.',
      body_en: 'Lists can be nested inside each other. A new list is placed inside a parent <li> tag.',
      code: '<ul>\n  <li>Фрукты\n    <ul>\n      <li>Яблоки</li>\n      <li>Груши</li>\n    </ul>\n  </li>\n  <li>Овощи\n    <ul>\n      <li>Морковь</li>\n      <li>Капуста</li>\n    </ul>\n  </li>\n</ul>',
      codeLang: 'html',
    },
    {
      id: 'slide-8',
      type: 'tip',
      title_ru: 'Список определений (dl, dt, dd)',
      title_en: 'Definition List (dl, dt, dd)',
      body_ru: 'Тег <dl> создаёт список определений. <dt> — термин (definition term), <dd> — его описание (definition description). Идеально для глоссариев и FAQ.',
      body_en: 'The <dl> tag creates a definition list. <dt> is the term (definition term), <dd> is its description (definition description). Ideal for glossaries and FAQs.',
      code: '<dl>\n  <dt>HTML</dt>\n  <dd>Язык разметки гипертекста</dd>\n\n  <dt>CSS</dt>\n  <dd>Каскадные таблицы стилей</dd>\n\n  <dt>JavaScript</dt>\n  <dd>Язык программирования для веба</dd>\n</dl>',
      codeLang: 'html',
      bullets: [
        { text_ru: 'dl — контейнер списка определений', text_en: 'dl — definition list container' },
        { text_ru: 'dt — термин или название', text_en: 'dt — the term or name' },
        { text_ru: 'dd — описание или определение', text_en: 'dd — the description or definition' },
      ],
    },
    {
      id: 'slide-9',
      type: 'practice-cta',
      title_ru: 'Создайте своё меню!',
      title_en: 'Build Your Own Menu!',
      body_ru: 'Напишите HTML-разметку: навигационное меню сайта, список шагов и глоссарий с терминами.',
      body_en: 'Write HTML markup for a site navigation menu, a list of steps, and a glossary with terms.',
    },
  ],

  content: {
    intro_ru: 'Списки — фундаментальный элемент веб-разметки. Они встречаются повсюду: в навигации, карточках товаров, инструкциях, рейтингах и словарях. HTML предлагает три типа списков, каждый из которых решает свою задачу.',
    intro_en: 'Lists are a fundamental element of web markup. They appear everywhere: in navigation, product cards, instructions, rankings, and glossaries. HTML offers three types of lists, each solving a specific task.',
    blocks: [
      {
        sectionId: 'unordered',
        heading_ru: 'Маркированный список (ul)',
        heading_en: 'Unordered List (ul)',
        text_ru: '<ul> (unordered list) создаёт список с маркерами. Используйте его, когда порядок пунктов не имеет значения. Каждый пункт — тег <li>. Стандартный маркер — закрашенный круг, но его можно изменить через CSS. Навигационные меню традиционно вёрстаются именно через ul > li.',
        text_en: '<ul> (unordered list) creates a bulleted list. Use it when item order does not matter. Each item is an <li> tag. The default marker is a filled disc, but it can be changed with CSS. Navigation menus are traditionally marked up as ul > li.',
        code: '<ul>\n  <li>Адаптивный дизайн</li>\n  <li>Быстрая загрузка</li>\n  <li>Доступность (a11y)</li>\n</ul>',
        codeLang: 'html',
      },
      {
        sectionId: 'ordered',
        heading_ru: 'Нумерованный список (ol)',
        heading_en: 'Ordered List (ol)',
        text_ru: '<ol> (ordered list) создаёт нумерованный список. Используйте его, когда порядок шагов важен. Атрибут start позволяет начать нумерацию с произвольного числа. Атрибут type задаёт тип нумерации: 1 (цифры), A (заглавные буквы), a (строчные), I (римские цифры).',
        text_en: '<ol> (ordered list) creates a numbered list. Use it when the order of steps matters. The start attribute lets you begin numbering at any number. The type attribute sets the numbering style: 1 (numbers), A (uppercase letters), a (lowercase), I (Roman numerals).',
        code: '<ol type="1">\n  <li>Открыть редактор кода</li>\n  <li>Создать файл index.html</li>\n  <li>Написать разметку</li>\n  <li>Открыть в браузере</li>\n</ol>',
        codeLang: 'html',
      },
      {
        sectionId: 'nested',
        heading_ru: 'Вложенные списки',
        heading_en: 'Nested Lists',
        text_ru: 'Вложенные списки позволяют создавать иерархические структуры. Новый список помещается прямо внутрь элемента <li>. Можно вкладывать ul в ol и наоборот. Глубина вложенности не ограничена технически, но для читаемости не стоит идти глубже 3 уровней.',
        text_en: 'Nested lists allow you to create hierarchical structures. A new list is placed directly inside an <li> element. You can nest ul inside ol and vice versa. Nesting depth is technically unlimited, but for readability avoid going deeper than 3 levels.',
        code: '<ol>\n  <li>Фронтенд\n    <ul>\n      <li>HTML</li>\n      <li>CSS</li>\n      <li>JavaScript</li>\n    </ul>\n  </li>\n  <li>Бэкенд\n    <ul>\n      <li>Node.js</li>\n      <li>Python</li>\n    </ul>\n  </li>\n</ol>',
        codeLang: 'html',
      },
      {
        sectionId: 'definition',
        heading_ru: 'Список определений (dl)',
        heading_en: 'Definition List (dl)',
        text_ru: '<dl> (description list) — список пар «термин–описание». <dt> задаёт термин, <dd> — его определение (с отступом слева). У одного термина может быть несколько определений. Список определений подходит для глоссариев, характеристик товара, FAQ и метаданных.',
        text_en: '<dl> (description list) is a list of term–description pairs. <dt> sets the term, <dd> its definition (indented). One term can have multiple descriptions. Definition lists suit glossaries, product specs, FAQs, and metadata.',
        code: '<dl>\n  <dt>Репозиторий</dt>\n  <dd>Хранилище кода проекта с историей изменений</dd>\n  <dd>Обычно размещается на GitHub или GitLab</dd>\n\n  <dt>Коммит</dt>\n  <dd>Зафиксированный снимок состояния кода</dd>\n</dl>',
        codeLang: 'html',
      },
    ],
  },

  editorTask: {
    title_ru: 'Создайте страницу рецепта',
    title_en: 'Create a Recipe Page',
    instructions_ru: 'Напишите HTML-страницу рецепта. Используйте ul для списка ингредиентов, ol для шагов приготовления, вложенный список для подкатегорий ингредиентов и dl для питательной ценности.',
    instructions_en: 'Write an HTML recipe page. Use ul for the ingredients list, ol for the cooking steps, a nested list for ingredient subcategories, and dl for nutritional value.',
    activeTabs: ['html'],
    starterCode: {
      html: '<!-- Страница рецепта / Recipe page -->\n<h1>Название рецепта</h1>\n\n<!-- Ингредиенты (ul) / Ingredients (ul) -->\n<h2>Ингредиенты</h2>\n<!-- Добавьте маркированный список / Add an unordered list -->\n\n<!-- Шаги приготовления (ol) / Cooking steps (ol) -->\n<h2>Приготовление</h2>\n<!-- Добавьте нумерованный список / Add an ordered list -->\n\n<!-- Питательная ценность (dl) / Nutritional value (dl) -->\n<h2>Питательная ценность</h2>\n<!-- Добавьте список определений / Add a definition list -->\n',
    },
    hints_ru: [
      'Для ингредиентов: <ul><li>200г муки</li><li>2 яйца</li></ul>',
      'Для шагов: <ol><li>Смешайте ингредиенты</li></ol>',
      'Вложите ul в li, чтобы сгруппировать ингредиенты по категориям',
      'Для питательной ценности: <dl><dt>Калории</dt><dd>350 ккал</dd></dl>',
    ],
    hints_en: [
      'For ingredients: <ul><li>200g flour</li><li>2 eggs</li></ul>',
      'For steps: <ol><li>Mix the ingredients</li></ol>',
      'Nest ul inside li to group ingredients by category',
      'For nutrition: <dl><dt>Calories</dt><dd>350 kcal</dd></dl>',
    ],
  },

  keyTerms: [
    {
      term_ru: 'ul',
      term_en: 'ul',
      definition_ru: 'Unordered list — маркированный список, в котором порядок пунктов не важен.',
      definition_en: 'Unordered list — a bulleted list where item order does not matter.',
      example_ru: '<ul><li>Пункт</li></ul>',
      example_en: '<ul><li>Item</li></ul>',
    },
    {
      term_ru: 'ol',
      term_en: 'ol',
      definition_ru: 'Ordered list — нумерованный список, в котором порядок пунктов важен.',
      definition_en: 'Ordered list — a numbered list where item order matters.',
      example_ru: '<ol><li>Шаг 1</li></ol>',
      example_en: '<ol><li>Step 1</li></ol>',
    },
    {
      term_ru: 'li',
      term_en: 'li',
      definition_ru: 'List item — пункт списка. Используется внутри ul или ol.',
      definition_en: 'List item — an item in a list. Used inside ul or ol.',
      example_ru: '<li>Один пункт</li>',
      example_en: '<li>One item</li>',
    },
    {
      term_ru: 'dl',
      term_en: 'dl',
      definition_ru: 'Description list — список пар «термин–описание», используемый для глоссариев и FAQ.',
      definition_en: 'Description list — a list of term–description pairs used for glossaries and FAQs.',
      example_ru: '<dl><dt>Термин</dt><dd>Описание</dd></dl>',
      example_en: '<dl><dt>Term</dt><dd>Description</dd></dl>',
    },
    {
      term_ru: 'Вложенный список',
      term_en: 'Nested List',
      definition_ru: 'Список внутри другого списка, создающий иерархическую структуру данных.',
      definition_en: 'A list inside another list, creating a hierarchical data structure.',
      example_ru: '<ul><li>Раздел<ul><li>Подраздел</li></ul></li></ul>',
      example_en: '<ul><li>Section<ul><li>Subsection</li></ul></li></ul>',
    },
  ],

  didYouKnow: [
    {
      text_ru: 'Большинство навигационных меню в интернете — это CSS-стилизованные теги ul и li. Браузерный стиль маркеров просто скрывается через list-style: none.',
      text_en: 'Most navigation menus on the internet are CSS-styled ul and li tags. The default bullet style is simply hidden with list-style: none.',
    },
    {
      text_ru: 'У тега <ol> есть атрибут reversed, который делает нумерацию в обратном порядке. Полезно для рейтингов типа «Топ-10».',
      text_en: 'The <ol> tag has a reversed attribute that numbers items in reverse order. Handy for "Top 10" countdowns.',
    },
  ],

  quiz: [
    {
      id: 'q1',
      text_ru: 'Какой тег создаёт маркированный список?',
      text_en: 'Which tag creates an unordered list?',
      options_ru: ['<ol>', '<ul>', '<li>', '<dl>'],
      options_en: ['<ol>', '<ul>', '<li>', '<dl>'],
      correctIndex: 1,
      explanation_ru: '<ul> (unordered list) создаёт маркированный список с буллитами. <ol> — нумерованный.',
      explanation_en: '<ul> (unordered list) creates a bulleted list. <ol> creates a numbered list.',
    },
    {
      id: 'q2',
      text_ru: 'Когда лучше использовать <ol> вместо <ul>?',
      text_en: 'When is it better to use <ol> instead of <ul>?',
      options_ru: ['Когда пунктов больше пяти', 'Когда порядок элементов важен', 'Когда нужны картинки', 'Когда список вложенный'],
      options_en: ['When there are more than five items', 'When item order matters', 'When images are needed', 'When the list is nested'],
      correctIndex: 1,
      explanation_ru: '<ol> используется, когда последовательность пунктов имеет значение — например, в инструкциях или рецептах.',
      explanation_en: '<ol> is used when the sequence of items matters — for example in instructions or recipes.',
    },
    {
      id: 'q3',
      text_ru: 'Какой тег используется для пункта списка?',
      text_en: 'Which tag is used for a list item?',
      options_ru: ['<item>', '<list>', '<li>', '<point>'],
      options_en: ['<item>', '<list>', '<li>', '<point>'],
      correctIndex: 2,
      explanation_ru: '<li> (list item) — пункт списка. Он используется внутри ul, ol или menu.',
      explanation_en: '<li> (list item) is the list item tag. It is used inside ul, ol, or menu.',
    },
    {
      id: 'q4',
      text_ru: 'Какие теги используются в списке определений?',
      text_en: 'Which tags are used in a definition list?',
      options_ru: ['<list>, <term>, <def>', '<dl>, <dt>, <dd>', '<ul>, <title>, <desc>', '<def>, <item>, <desc>'],
      options_en: ['<list>, <term>, <def>', '<dl>, <dt>, <dd>', '<ul>, <title>, <desc>', '<def>, <item>, <desc>'],
      correctIndex: 1,
      explanation_ru: 'Список определений: <dl> — контейнер, <dt> — термин, <dd> — описание/определение.',
      explanation_en: 'Definition list: <dl> is the container, <dt> is the term, <dd> is the description/definition.',
    },
    {
      id: 'q5',
      text_ru: 'Где размещается вложенный список?',
      text_en: 'Where is a nested list placed?',
      options_ru: ['После закрывающего тега родительского li', 'Внутри тега ul или ol, но не в li', 'Внутри тега li родительского списка', 'В отдельном теге section'],
      options_en: ['After the closing tag of the parent li', 'Inside ul or ol but not in li', 'Inside the parent list\'s li tag', 'In a separate section tag'],
      correctIndex: 2,
      explanation_ru: 'Вложенный список помещается внутрь тега <li> родительского списка, до закрывающего </li>.',
      explanation_en: 'A nested list is placed inside the <li> tag of the parent list, before the closing </li>.',
    },
  ],
}
