export const LESSON_SLUGS = [
  'intro-to-programming',
  'intro-to-html',
  'html-tags',
  'html-structure',
  'html-elements',
  'intro-to-css',
  'css-styling',
  'css-layout',
  'css-basics',
  'css-box-model',
  'css-flexbox',
  'intro-to-js',
  'js-logic',
  'js-dom',
  'intro-to-javascript',
  'javascript-functions',
  'javascript-conditions',
  'javascript-loops',
  'javascript-arrays',
  'dom-manipulation',
  'build-your-webpage',
] as const

export type LessonSlug = (typeof LESSON_SLUGS)[number]

export const LESSON_META: Record<LessonSlug, { title: string; title_en: string; description: string; description_en: string; icon: string; category?: import('@/types/lesson').LessonCategory }> = {
  'intro-to-programming': {
    title: 'Что такое программирование',
    title_en: 'What is Programming',
    description: 'Узнай, что такое код, алгоритм и зачем вообще учиться программировать.',
    description_en: 'Find out what code and algorithms are, and why learning to program matters.',
    icon: '💡',
    category: 'BASICS',
  },
  'intro-to-html': {
    title: 'Что такое HTML',
    title_en: 'What is HTML',
    description: 'Знакомимся с языком, на котором написаны все сайты в мире.',
    description_en: 'Get to know the language that powers every website in the world.',
    icon: '🏗️',
  },
  'html-tags': {
    title: 'Основные теги HTML',
    title_en: 'Basic HTML Tags',
    description: 'Заголовки, абзацы, ссылки, картинки и списки — теги, которые строят любой сайт.',
    description_en: 'Headings, paragraphs, links, images and lists — the tags that build any site.',
    icon: '🔤',
  },
  'html-structure': {
    title: 'Структура HTML-документа',
    title_en: 'HTML Document Structure',
    description: 'Каркас любой веб-страницы: DOCTYPE, html, head, body и семантические теги.',
    description_en: 'The skeleton of any web page: DOCTYPE, html, head, body and semantic tags.',
    icon: '🏛️',
  },
  'html-elements': {
    title: 'Элементы HTML',
    title_en: 'HTML Elements',
    description: 'Заголовки, абзацы, списки, ссылки и изображения',
    description_en: 'Headings, paragraphs, lists, links and images',
    icon: '🔤',
  },
  'intro-to-css': {
    title: 'Что такое CSS',
    title_en: 'What is CSS',
    description: 'Добавляем цвета, шрифты и красоту — учимся одевать HTML-скелет.',
    description_en: 'Adding colors, fonts and beauty — learning to style the HTML skeleton.',
    icon: '🎨',
  },
  'css-styling': {
    title: 'Стили CSS: цвета, шрифты, фон',
    title_en: 'CSS Styles: Colors, Fonts, Background',
    description: 'Раскрашиваем страницу: работаем с цветами, шрифтами, фоном и рамками.',
    description_en: 'Styling the page: working with colors, fonts, backgrounds and borders.',
    icon: '🖌️',
  },
  'css-layout': {
    title: 'Раскладка CSS: блочная модель и Flexbox',
    title_en: 'CSS Layout: Box Model & Flexbox',
    description: 'Учимся расставлять элементы: блочная модель, margin, padding и Flexbox.',
    description_en: 'Arranging elements: box model, margin, padding and Flexbox.',
    icon: '📐',
  },
  'css-basics': {
    title: 'Основы CSS',
    title_en: 'CSS Basics',
    description: 'Что такое CSS, селекторы, свойства и значения',
    description_en: 'What is CSS, selectors, properties and values',
    icon: '🎨',
  },
  'css-box-model': {
    title: 'Блочная модель CSS',
    title_en: 'CSS Box Model',
    description: 'Margin, padding, border — как устроено пространство',
    description_en: 'Margin, padding, border — how spacing works',
    icon: '📦',
  },
  'css-flexbox': {
    title: 'Flexbox',
    title_en: 'Flexbox',
    description: 'Выравнивание и расположение элементов с Flexbox',
    description_en: 'Aligning and positioning elements with Flexbox',
    icon: '↔️',
  },
  'intro-to-js': {
    title: 'Введение в JavaScript',
    title_en: 'Introduction to JavaScript',
    description: 'Переменные, типы данных и первые шаги в программировании на JS.',
    description_en: 'Variables, data types and first steps in JS programming.',
    icon: '⚡',
  },
  'js-logic': {
    title: 'Условия и циклы',
    title_en: 'Conditions & Loops',
    description: 'if/else, операторы сравнения и циклы — учим JavaScript принимать решения.',
    description_en: 'if/else, comparison operators and loops — teaching JavaScript to make decisions.',
    icon: '🔀',
  },
  'js-dom': {
    title: 'Работа с DOM',
    title_en: 'Working with the DOM',
    description: 'Находи элементы, меняй содержимое и реагируй на действия пользователя.',
    description_en: 'Find elements, change content and respond to user actions.',
    icon: '🖱️',
  },
  'intro-to-javascript': {
    title: 'Введение в JavaScript',
    title_en: 'Introduction to JavaScript',
    description: 'Переменные, типы данных, console.log',
    description_en: 'Variables, data types, console.log',
    icon: '⚡',
  },
  'javascript-functions': {
    title: 'Функции JavaScript',
    title_en: 'JavaScript Functions',
    description: 'Создание функций, параметры и возврат значения',
    description_en: 'Creating functions, parameters and return values',
    icon: '🔧',
  },
  'javascript-conditions': {
    title: 'Условия в JavaScript',
    title_en: 'JavaScript Conditions',
    description: 'if/else, операторы сравнения, логические операторы',
    description_en: 'if/else, comparison operators, logical operators',
    icon: '🔀',
  },
  'javascript-loops': {
    title: 'Циклы в JavaScript',
    title_en: 'JavaScript Loops',
    description: 'for, while — повторяем действия автоматически',
    description_en: 'for, while — repeating actions automatically',
    icon: '🔁',
  },
  'javascript-arrays': {
    title: 'Массивы JavaScript',
    title_en: 'JavaScript Arrays',
    description: 'Создание массивов, методы push/pop/map/filter',
    description_en: 'Creating arrays, push/pop/map/filter methods',
    icon: '📋',
  },
  'dom-manipulation': {
    title: 'Работа с DOM',
    title_en: 'DOM Manipulation',
    description: 'Находим элементы, меняем содержимое, обрабатываем события',
    description_en: 'Finding elements, changing content, handling events',
    icon: '🖱️',
  },
  'build-your-webpage': {
    title: 'Создай свою страницу',
    title_en: 'Build Your Webpage',
    description: 'Итоговый проект: собираем полноценную веб-страницу',
    description_en: 'Final project: creating a complete web page',
    icon: '🚀',
  },
}
