export const LESSON_SLUGS = [
  // BASICS
  'intro-to-programming',
  'git-github',
  // HTML
  'intro-to-html',
  'html-tags-elements',
  'html-text-headings',
  'html-lists',
  'html-links',
  'html-images-media',
  'html-tables',
  'html-forms',
  'html-semantics',
  // CSS
  'intro-to-css',
  'css-selectors',
  'css-color-background',
  'css-text-fonts',
  'css-box-model',
  'css-sizing-units',
  'css-flexbox-basics',
  'css-flexbox-practice',
  'css-positioning',
  'css-grid',
  'css-responsive',
  'css-pseudo-animations',
  // JS
  'intro-to-js',
  'js-variables',
  'js-operators',
  'js-strings',
  'js-conditions',
  'js-loops',
  'js-functions',
  'js-arrow-functions',
  'js-arrays',
  'js-array-methods',
  'js-objects',
  'js-scope',
  'js-dom',
  'js-events',
  'js-errors-debugging',
  'js-localstorage',
  'js-async-basics',
  'js-final-project',
] as const

export type LessonSlug = (typeof LESSON_SLUGS)[number]

export const LESSON_META: Record<LessonSlug, { title: string; title_en: string; description: string; description_en: string; icon: string; category?: import('@/types/lesson').LessonCategory }> = {
  // BASICS
  'intro-to-programming': {
    title: 'Что такое программирование',
    title_en: 'What is Programming',
    description: 'Узнай, что такое код, алгоритм и зачем вообще учиться программировать.',
    description_en: 'Find out what code and algorithms are, and why learning to program matters.',
    icon: '💡',
    category: 'BASICS',
  },
  'git-github': {
    title: 'Git и GitHub',
    title_en: 'Git & GitHub',
    description: 'Контроль версий, история изменений и командная работа над проектами.',
    description_en: 'Version control, change history and team collaboration on projects.',
    icon: '🌿',
    category: 'BASICS',
  },
  // HTML
  'intro-to-html': {
    title: 'Введение в HTML',
    title_en: 'Introduction to HTML',
    description: 'Знакомимся с языком, на котором написаны все сайты в мире.',
    description_en: 'Get to know the language that powers every website in the world.',
    icon: '🏗️',
    category: 'HTML',
  },
  'html-tags-elements': {
    title: 'Теги и элементы',
    title_en: 'Tags & Elements',
    description: 'Что такое тег, элемент и атрибут. Анатомия HTML-кода.',
    description_en: 'What is a tag, element and attribute. The anatomy of HTML code.',
    icon: '🔤',
    category: 'HTML',
  },
  'html-text-headings': {
    title: 'Текст и заголовки',
    title_en: 'Text & Headings',
    description: 'Заголовки h1–h6, абзацы, жирный и курсивный текст.',
    description_en: 'Headings h1–h6, paragraphs, bold and italic text.',
    icon: '📝',
    category: 'HTML',
  },
  'html-lists': {
    title: 'Списки',
    title_en: 'Lists',
    description: 'Маркированные ul, нумерованные ol и вложенные списки.',
    description_en: 'Unordered ul, ordered ol and nested lists.',
    icon: '📋',
    category: 'HTML',
  },
  'html-links': {
    title: 'Ссылки',
    title_en: 'Links',
    description: 'Тег <a>, href, целевые окна, якорные и email-ссылки.',
    description_en: 'The <a> tag, href, target windows, anchor and email links.',
    icon: '🔗',
    category: 'HTML',
  },
  'html-images-media': {
    title: 'Изображения и медиа',
    title_en: 'Images & Media',
    description: 'Тег img, атрибуты src и alt, форматы, видео и аудио.',
    description_en: 'The img tag, src and alt attributes, formats, video and audio.',
    icon: '🖼️',
    category: 'HTML',
  },
  'html-tables': {
    title: 'Таблицы',
    title_en: 'Tables',
    description: 'Создание таблиц: table, tr, th, td — данные в строки и столбцы.',
    description_en: 'Creating tables: table, tr, th, td — data in rows and columns.',
    icon: '📊',
    category: 'HTML',
  },
  'html-forms': {
    title: 'Формы',
    title_en: 'Forms',
    description: 'Поля ввода, кнопки, чекбоксы, выпадающие списки — форма от А до Я.',
    description_en: 'Input fields, buttons, checkboxes, dropdowns — forms from A to Z.',
    icon: '📬',
    category: 'HTML',
  },
  'html-semantics': {
    title: 'Семантический HTML',
    title_en: 'Semantic HTML',
    description: 'header, nav, main, section, footer — правильная структура страницы.',
    description_en: 'header, nav, main, section, footer — the right page structure.',
    icon: '🏛️',
    category: 'HTML',
  },
  // CSS
  'intro-to-css': {
    title: 'Введение в CSS',
    title_en: 'Introduction to CSS',
    description: 'Добавляем цвета, шрифты и красоту — учимся одевать HTML-скелет.',
    description_en: 'Adding colors, fonts and beauty — learning to style the HTML skeleton.',
    icon: '🎨',
    category: 'CSS',
  },
  'css-selectors': {
    title: 'Селекторы CSS',
    title_en: 'CSS Selectors',
    description: 'Теговые, классовые, ID, псевдоклассы и комбинаторы — выбираем нужные элементы.',
    description_en: 'Tag, class, ID, pseudo-class selectors and combinators — targeting the right elements.',
    icon: '🎯',
    category: 'CSS',
  },
  'css-color-background': {
    title: 'Цвет и фон',
    title_en: 'Color & Background',
    description: 'HEX, RGB, HSL — форматы цветов, фоны и градиенты.',
    description_en: 'HEX, RGB, HSL color formats, backgrounds and gradients.',
    icon: '🖌️',
    category: 'CSS',
  },
  'css-text-fonts': {
    title: 'Текст и шрифты',
    title_en: 'Text & Fonts',
    description: 'font-family, font-size, line-height, letter-spacing и Google Fonts.',
    description_en: 'font-family, font-size, line-height, letter-spacing and Google Fonts.',
    icon: '✍️',
    category: 'CSS',
  },
  'css-box-model': {
    title: 'Блочная модель',
    title_en: 'Box Model',
    description: 'Margin, padding, border — как устроено пространство вокруг элементов.',
    description_en: 'Margin, padding, border — how spacing works around elements.',
    icon: '📦',
    category: 'CSS',
  },
  'css-sizing-units': {
    title: 'Размеры и единицы',
    title_en: 'Sizing & Units',
    description: 'px, em, rem, %, vw/vh — когда и какую единицу использовать.',
    description_en: 'px, em, rem, %, vw/vh — when and which unit to use.',
    icon: '📐',
    category: 'CSS',
  },
  'css-flexbox-basics': {
    title: 'Flexbox: основы',
    title_en: 'Flexbox Basics',
    description: 'display:flex, flex-direction, justify-content, align-items.',
    description_en: 'display:flex, flex-direction, justify-content, align-items.',
    icon: '↔️',
    category: 'CSS',
  },
  'css-flexbox-practice': {
    title: 'Flexbox: практика',
    title_en: 'Flexbox Practice',
    description: 'Flex-wrap, gap, order, flex-grow — строим реальные лейауты.',
    description_en: 'Flex-wrap, gap, order, flex-grow — building real layouts.',
    icon: '🧩',
    category: 'CSS',
  },
  'css-positioning': {
    title: 'Позиционирование',
    title_en: 'Positioning',
    description: 'static, relative, absolute, fixed, sticky — управляем положением.',
    description_en: 'static, relative, absolute, fixed, sticky — controlling position.',
    icon: '📍',
    category: 'CSS',
  },
  'css-grid': {
    title: 'CSS Grid',
    title_en: 'CSS Grid',
    description: 'Двумерная раскладка: grid-template, grid-area, gap.',
    description_en: 'Two-dimensional layout: grid-template, grid-area, gap.',
    icon: '🔲',
    category: 'CSS',
  },
  'css-responsive': {
    title: 'Адаптивный дизайн',
    title_en: 'Responsive Design',
    description: 'Media queries, viewport, mobile-first — страница на любом экране.',
    description_en: 'Media queries, viewport, mobile-first — pages on any screen.',
    icon: '📱',
    category: 'CSS',
  },
  'css-pseudo-animations': {
    title: 'Псевдоклассы и анимации',
    title_en: 'Pseudo-classes & Animations',
    description: ':hover, :focus, transition, animation и @keyframes.',
    description_en: ':hover, :focus, transition, animation and @keyframes.',
    icon: '✨',
    category: 'CSS',
  },
  // JS
  'intro-to-js': {
    title: 'Введение в JavaScript',
    title_en: 'Introduction to JavaScript',
    description: 'Переменные, типы данных и первые шаги в программировании на JS.',
    description_en: 'Variables, data types and first steps in JS programming.',
    icon: '⚡',
    category: 'JS',
  },
  'js-variables': {
    title: 'Переменные',
    title_en: 'Variables',
    description: 'let, const, var — объявление, именование и область видимости.',
    description_en: 'let, const, var — declaration, naming and scope.',
    icon: '📦',
    category: 'JS',
  },
  'js-operators': {
    title: 'Операторы',
    title_en: 'Operators',
    description: 'Арифметические, сравнения, логические и присваивающие операторы.',
    description_en: 'Arithmetic, comparison, logical and assignment operators.',
    icon: '➕',
    category: 'JS',
  },
  'js-strings': {
    title: 'Строки',
    title_en: 'Strings',
    description: 'Создание, методы, шаблонные строки и работа с текстом.',
    description_en: 'Creating, methods, template literals and working with text.',
    icon: '📝',
    category: 'JS',
  },
  'js-conditions': {
    title: 'Условия',
    title_en: 'Conditions',
    description: 'if/else, else if, тернарный оператор — программа принимает решения.',
    description_en: 'if/else, else if, ternary operator — the program makes decisions.',
    icon: '🔀',
    category: 'JS',
  },
  'js-loops': {
    title: 'Циклы',
    title_en: 'Loops',
    description: 'for, while, for..of, break и continue — повторяем автоматически.',
    description_en: 'for, while, for..of, break and continue — repeating automatically.',
    icon: '🔄',
    category: 'JS',
  },
  'js-functions': {
    title: 'Функции',
    title_en: 'Functions',
    description: 'Объявление, параметры, return и области видимости функции.',
    description_en: 'Declaration, parameters, return and function scope.',
    icon: '🔧',
    category: 'JS',
  },
  'js-arrow-functions': {
    title: 'Стрелочные функции',
    title_en: 'Arrow Functions',
    description: 'Синтаксис =>, краткая запись, отличия от function и this.',
    description_en: 'Arrow => syntax, shorthand form, differences from function and this.',
    icon: '➡️',
    category: 'JS',
  },
  'js-arrays': {
    title: 'Массивы',
    title_en: 'Arrays',
    description: 'Создание, доступ по индексу, push/pop и перебор массивов.',
    description_en: 'Creating, index access, push/pop and iterating arrays.',
    icon: '📋',
    category: 'JS',
  },
  'js-array-methods': {
    title: 'Методы массивов',
    title_en: 'Array Methods',
    description: 'map, filter, reduce, find, some, every — мощный набор инструментов.',
    description_en: 'map, filter, reduce, find, some, every — a powerful toolkit.',
    icon: '🔍',
    category: 'JS',
  },
  'js-objects': {
    title: 'Объекты',
    title_en: 'Objects',
    description: 'Ключ-значение, методы объектов, деструктуризация и spread.',
    description_en: 'Key-value pairs, object methods, destructuring and spread.',
    icon: '🗂️',
    category: 'JS',
  },
  'js-scope': {
    title: 'Область видимости',
    title_en: 'Scope & Closure',
    description: 'Глобальная, локальная, блочная область — что где доступно.',
    description_en: 'Global, local, block scope — what is accessible where.',
    icon: '🔭',
    category: 'JS',
  },
  'js-dom': {
    title: 'Работа с DOM',
    title_en: 'DOM Manipulation',
    description: 'Находи элементы, меняй содержимое и реагируй на действия пользователя.',
    description_en: 'Find elements, change content and respond to user actions.',
    icon: '🖱️',
    category: 'JS',
  },
  'js-events': {
    title: 'События',
    title_en: 'Events',
    description: 'addEventListener, объект события, делегирование и встроенные события.',
    description_en: 'addEventListener, event object, delegation and built-in events.',
    icon: '👆',
    category: 'JS',
  },
  'js-errors-debugging': {
    title: 'Ошибки и отладка',
    title_en: 'Errors & Debugging',
    description: 'try/catch, типы ошибок, console и DevTools — находим и исправляем баги.',
    description_en: 'try/catch, error types, console and DevTools — finding and fixing bugs.',
    icon: '🐛',
    category: 'JS',
  },
  'js-localstorage': {
    title: 'localStorage',
    title_en: 'localStorage',
    description: 'Хранение данных в браузере: setItem, getItem, JSON и sessionStorage.',
    description_en: 'Storing data in the browser: setItem, getItem, JSON and sessionStorage.',
    icon: '💾',
    category: 'JS',
  },
  'js-async-basics': {
    title: 'Асинхронность',
    title_en: 'Async Basics',
    description: 'setTimeout, Promise, fetch и async/await — работаем с сетью.',
    description_en: 'setTimeout, Promise, fetch and async/await — working with the network.',
    icon: '⏱️',
    category: 'JS',
  },
  'js-final-project': {
    title: 'Финальный проект',
    title_en: 'Final Project',
    description: 'Собираем всё вместе: HTML + CSS + JS — твой первый настоящий сайт.',
    description_en: 'Putting it all together: HTML + CSS + JS — your first real website.',
    icon: '🌐',
    category: 'JS',
  },
}
