import type { Lesson } from '@/types/lesson'

export const jsErrorsDebugging: Lesson = {
  slug: 'js-errors-debugging',
  category: 'JS',
  icon: '🐛',
  readTime: 10,
  title_ru: 'Ошибки и отладка',
  title_en: 'Errors and Debugging',
  description_ru: 'Научитесь понимать типы ошибок, использовать try/catch, методы console и инструменты DevTools.',
  description_en: 'Learn to understand error types, use try/catch, console methods and DevTools.',
  sections: [
    { id: 'error-types', title_ru: 'Типы ошибок', title_en: 'Error types' },
    { id: 'try-catch', title_ru: 'try / catch / finally', title_en: 'try / catch / finally' },
    { id: 'throw', title_ru: 'throw new Error()', title_en: 'throw new Error()' },
    { id: 'console', title_ru: 'Методы console', title_en: 'Console methods' },
    { id: 'devtools', title_ru: 'Брейкпоинты DevTools', title_en: 'DevTools breakpoints' },
    { id: 'common-mistakes', title_ru: 'Частые ошибки', title_en: 'Common mistakes' },
  ],
  slides: [
    {
      id: 'title-slide',
      type: 'title',
      title_ru: 'Ошибки и отладка',
      title_en: 'Errors and Debugging',
      body_ru: 'Ошибки — неизбежная часть программирования. Важно не избегать их, а уметь находить, понимать и обрабатывать.',
      body_en: 'Errors are an inevitable part of programming. The important thing is not to avoid them, but to find, understand and handle them.',
      visual: { kind: 'emoji', emojis: ['🐛', '🔍', '✅'], caption_ru: 'Найди, пойми, исправь', caption_en: 'Find, understand, fix' },
    },
    {
      id: 'concept-error-types',
      type: 'concept',
      title_ru: 'Типы ошибок JavaScript',
      title_en: 'JavaScript error types',
      body_ru: 'JavaScript имеет несколько встроенных типов ошибок, каждый из которых указывает на разную проблему.',
      body_en: 'JavaScript has several built-in error types, each indicating a different problem.',
      code: `// SyntaxError — неправильный синтаксис (до выполнения)\n// const x = { ; // SyntaxError: Unexpected token\n\n// ReferenceError — обращение к несуществующей переменной\ntry {\n  console.log(undeclaredVar); // ReferenceError\n} catch(e) { console.log(e.name); } // 'ReferenceError'\n\n// TypeError — неправильный тип операции\ntry {\n  null.toString(); // TypeError\n} catch(e) { console.log(e.name); } // 'TypeError'\n\n// RangeError — значение вне допустимого диапазона\ntry {\n  new Array(-1); // RangeError\n} catch(e) { console.log(e.name); } // 'RangeError'`,
      codeLang: 'javascript',
    },
    {
      id: 'concept-try-catch',
      type: 'concept',
      title_ru: 'try / catch / finally',
      title_en: 'try / catch / finally',
      body_ru: 'try — блок рискованного кода. catch — перехватывает ошибку. finally — выполняется всегда (успех или ошибка).',
      body_en: 'try — the risky code block. catch — catches the error. finally — always executes (success or error).',
      code: `function parseJSON(jsonString) {\n  try {\n    const data = JSON.parse(jsonString);\n    console.log('Parsed:', data);\n    return data;\n  } catch (error) {\n    console.error('Invalid JSON:', error.message);\n    return null;\n  } finally {\n    console.log('parseJSON finished'); // always runs\n  }\n}\n\nparseJSON('{"name":"Alice"}'); // works\nparseJSON('not valid json');  // caught gracefully`,
      codeLang: 'javascript',
    },
    {
      id: 'compare-no-try-vs-try',
      type: 'compare',
      title_ru: 'Без обработки ошибок vs с try/catch',
      title_en: 'No error handling vs try/catch',
      body_ru: 'Необработанная ошибка останавливает весь дальнейший код на странице.',
      body_en: 'An unhandled error stops all subsequent code on the page.',
      compareLeft: {
        label_ru: 'Без обработки — сбой',
        label_en: 'No handling — crash',
        items_ru: ['Ошибка останавливает скрипт', 'Пользователь видит сломанную страницу', 'Невозможно показать сообщение', 'Остальной код не выполняется'],
        items_en: ['Error stops the script', 'User sees a broken page', 'Cannot show an error message', 'Remaining code does not run'],
        color: 'red',
      },
      compareRight: {
        label_ru: 'try/catch — контроль',
        label_en: 'try/catch — control',
        items_ru: ['Ошибка перехвачена', 'Пользователь видит нормальное сообщение', 'Можно логировать ошибку', 'Остальной код продолжает работать'],
        items_en: ['Error is caught', 'User sees a proper message', 'Error can be logged', 'Remaining code keeps running'],
        color: 'green',
      },
    },
    {
      id: 'concept-throw',
      type: 'concept',
      title_ru: 'throw — бросить собственную ошибку',
      title_en: 'throw — throw your own error',
      body_ru: 'throw позволяет вручную генерировать ошибки для валидации или нарушений бизнес-логики.',
      body_en: 'throw lets you manually generate errors for validation or business logic violations.',
      code: `function divide(a, b) {\n  if (typeof a !== 'number' || typeof b !== 'number') {\n    throw new TypeError('Both arguments must be numbers');\n  }\n  if (b === 0) {\n    throw new RangeError('Division by zero is not allowed');\n  }\n  return a / b;\n}\n\ntry {\n  console.log(divide(10, 2));  // 5\n  console.log(divide(10, 0)); // throws RangeError\n} catch (e) {\n  console.error(e.name + ': ' + e.message);\n  // 'RangeError: Division by zero is not allowed'\n}`,
      codeLang: 'javascript',
    },
    {
      id: 'concept-console',
      type: 'concept',
      title_ru: 'Методы console',
      title_en: 'Console methods',
      body_ru: 'console имеет множество методов помимо log. Каждый имеет своё назначение и уровень важности.',
      body_en: 'console has many methods beyond log. Each has its own purpose and severity level.',
      code: `console.log('Info message');         // standard output\nconsole.warn('Something odd');      // yellow warning\nconsole.error('Something broke!');  // red error\n\nconsole.table([                     // table format\n  { name: 'Alice', age: 25 },\n  { name: 'Bob',   age: 30 },\n]);\n\nconsole.group('User actions');      // collapsible group\nconsole.log('Step 1');\nconsole.log('Step 2');\nconsole.groupEnd();\n\nconsole.time('fetch-time');         // start timer\n// ... some code ...\nconsole.timeEnd('fetch-time');      // prints elapsed ms\n\nconsole.assert(1 === 2, 'Math broken!'); // only logs if false`,
      codeLang: 'javascript',
    },
    {
      id: 'anim-try-catch',
      type: 'code-anim',
      title_ru: 'Оборачиваем рискованный код в try/catch',
      title_en: 'Wrapping risky code in try/catch',
      body_ru: 'Шаг за шагом: пишем парсер JSON с обработкой ошибок.',
      body_en: 'Step by step: write a JSON parser with error handling.',
      animMode: 'console',
      animSteps: [
        {
          code: `// Risky: this will crash if input is invalid\nconst data = JSON.parse('bad input');\nconsole.log(data);`,
          comment_ru: 'Без защиты — выбрасывает SyntaxError',
          comment_en: 'Without protection — throws SyntaxError',
          output: '❌ SyntaxError: Unexpected token b in JSON at position 0',
        },
        {
          code: `function safeParseJSON(str) {\n  try {\n    return JSON.parse(str);\n  } catch (e) {\n    console.error('Parse failed:', e.message);\n    return null;\n  }\n}`,
          comment_ru: 'Оборачиваем JSON.parse в try/catch',
          comment_en: 'Wrap JSON.parse in try/catch',
          output: '',
        },
        {
          code: `function safeParseJSON(str) {\n  try {\n    return JSON.parse(str);\n  } catch (e) {\n    console.error('Parse failed:', e.message);\n    return null;\n  }\n}\n\nconsole.log(safeParseJSON('{"name":"Alex"}'));\nconsole.log(safeParseJSON('bad input'));`,
          comment_ru: 'Тестируем с хорошим и плохим вводом',
          comment_en: 'Test with good and bad input',
          output: '{ name: "Alex" }\nParse failed: Unexpected token b in JSON\nnull',
        },
        {
          code: `function safeParseJSON(str, fallback = {}) {\n  try {\n    return JSON.parse(str);\n  } catch (e) {\n    console.warn('Using fallback value');\n    return fallback;\n  }\n}\nconsole.log(safeParseJSON('bad', { error: true }));`,
          comment_ru: 'Улучшаем: добавляем значение по умолчанию',
          comment_en: 'Improve: add a fallback default value',
          output: 'Using fallback value\n{ error: true }',
        },
      ],
    },
    {
      id: 'concept-devtools',
      type: 'concept',
      title_ru: 'Отладка в DevTools',
      title_en: 'Debugging with DevTools',
      body_ru: 'Брейкпоинт (breakpoint) останавливает выполнение кода в нужном месте, позволяя проверить значения переменных.',
      body_en: 'A breakpoint pauses code execution at a specific line, letting you inspect variable values.',
      code: `function calculateTotal(items) {\n  debugger; // ← opens DevTools debugger here\n  let total = 0;\n  for (const item of items) {\n    total += item.price * item.quantity;\n  }\n  return total;\n}\n\n// In DevTools Sources tab:\n// 1. Open Sources\n// 2. Click line number to set breakpoint\n// 3. Refresh / run code\n// 4. Step through with F10 (next line) or F11 (into function)`,
      codeLang: 'javascript',
    },
    {
      id: 'tip-common-mistakes',
      type: 'tip',
      title_ru: 'Частые ошибки новичков',
      title_en: 'Common beginner mistakes',
      body_ru: '1. Cannot read property of undefined — проверяй существование объекта перед обращением. 2. is not a function — убедись, что переменная — функция. 3. = вместо === в условиях.',
      body_en: '1. Cannot read property of undefined — check the object exists before accessing. 2. is not a function — ensure the variable is actually a function. 3. = instead of === in conditions.',
    },
    {
      id: 'practice-cta',
      type: 'practice-cta',
      title_ru: 'Практика',
      title_en: 'Practice',
      body_ru: 'Напишите функцию с валидацией через throw и обработкой ошибки через try/catch.',
      body_en: 'Write a function with throw validation and error handling via try/catch.',
    },
  ],
  content: {
    intro_ru: 'Умение работать с ошибками отличает начинающего программиста от опытного. Хорошо обработанные ошибки делают приложение надёжным и понятным для пользователя.',
    intro_en: 'The ability to work with errors distinguishes a beginner from an experienced programmer. Well-handled errors make an application reliable and user-friendly.',
    blocks: [
      {
        sectionId: 'error-types',
        heading_ru: 'Типы ошибок JavaScript',
        heading_en: 'JavaScript error types',
        text_ru: 'JavaScript разделяет ошибки на несколько встроенных типов. Зная тип ошибки, вы быстро поймёте её причину и место возникновения.\n\nSyntaxError возникает ещё до выполнения кода — парсер не может разобрать текст программы (например, непарная скобка или запятая на неожиданном месте). ReferenceError сигнализирует об обращении к переменной, которая не была объявлена. TypeError появляется, когда операция выполняется над значением неподходящего типа — например, попытка вызвать null как функцию.\n\nRangeError говорит о том, что числовое значение вышло за допустимый диапазон (например, new Array(-1)). URIError и EvalError встречаются редко. Читая сообщение об ошибке в консоли, всегда обращайте внимание на её имя — это первая подсказка к исправлению.',
        text_en: 'JavaScript divides errors into several built-in types. Knowing the error type lets you quickly understand its cause and origin.\n\nSyntaxError occurs before code runs — the parser cannot read the program text (for example, a mismatched bracket or an unexpected comma). ReferenceError signals an attempt to access a variable that was never declared. TypeError appears when an operation is performed on a value of the wrong type — such as trying to call null as a function.\n\nRangeError means a numeric value is outside its allowed range (for example, new Array(-1)). URIError and EvalError are rarely encountered. When reading an error message in the console, always note the error name — it is the first clue for fixing the problem.',
        code: `// SyntaxError — bad syntax, caught before execution\n// const x = { ; // SyntaxError: Unexpected token ;\n\n// ReferenceError — variable never declared\ntry {\n  console.log(undeclaredVar);\n} catch (e) {\n  console.log(e.name);    // 'ReferenceError'\n  console.log(e.message); // 'undeclaredVar is not defined'\n}\n\n// TypeError — wrong type for the operation\ntry {\n  null.toString();\n} catch (e) {\n  console.log(e.name);    // 'TypeError'\n}\n\n// RangeError — value out of allowed range\ntry {\n  new Array(-1);\n} catch (e) {\n  console.log(e.name);    // 'RangeError'\n}`,
        codeLang: 'javascript',
      },
      {
        sectionId: 'try-catch',
        heading_ru: 'Анатомия try / catch / finally',
        heading_en: 'Anatomy of try / catch / finally',
        text_ru: 'Конструкция try/catch/finally — главный инструмент управления ошибками в JavaScript. Блок try содержит код, который может выбросить ошибку. Если ошибка возникает, управление немедленно передаётся в блок catch, который получает объект ошибки с полями name, message и stack.\n\nБлок finally выполняется всегда — и при успехе, и при ошибке. Это делает его идеальным местом для «уборки»: закрытия соединений, освобождения ресурсов или скрытия индикатора загрузки.\n\nВажно: try/catch перехватывает только синхронные ошибки. Для асинхронного кода с Promise используйте .catch(), а для async/await — оборачивайте await в try/catch.',
        text_en: 'The try/catch/finally construct is the primary error-management tool in JavaScript. The try block contains code that might throw. If an error occurs, control immediately passes to the catch block, which receives an error object with name, message, and stack fields.\n\nThe finally block always runs — on both success and error. This makes it ideal for "cleanup": closing connections, releasing resources, or hiding a loading spinner.\n\nImportant: try/catch only catches synchronous errors. For Promise-based async code use .catch(), and for async/await wrap the await inside try/catch.',
        code: `function loadUserData(userId) {\n  try {\n    // Risky: JSON.parse may throw SyntaxError\n    const raw = localStorage.getItem('user_' + userId);\n    const user = JSON.parse(raw);\n\n    if (!user) throw new Error('User not found');\n    return user;\n  } catch (error) {\n    // error.name, error.message, error.stack are available\n    console.error('[loadUserData]', error.name + ':', error.message);\n    return null; // safe fallback\n  } finally {\n    // Runs whether or not an error occurred\n    console.log('loadUserData finished for id:', userId);\n  }\n}\n\nconsole.log(loadUserData(42));   // null (nothing stored)\nconsole.log(loadUserData('x'));  // null (bad JSON)`,
        codeLang: 'javascript',
      },
      {
        sectionId: 'console',
        heading_ru: 'Полный арсенал методов console',
        heading_en: 'The full console method arsenal',
        text_ru: 'console.log — лишь один из множества инструментов отладки. Разные методы имеют разный визуальный стиль в DevTools и разный уровень серьёзности, что помогает быстро фильтровать вывод.\n\nconsole.warn выводит жёлтое предупреждение, console.error — красное сообщение об ошибке со стектрейсом. console.table отображает массивы и объекты в виде таблицы — незаменимо при отладке списков. console.group позволяет группировать логи в сворачиваемые секции.\n\nconsole.time / timeEnd измеряют время выполнения участка кода — удобно для простого профилирования. console.assert выводит сообщение только если условие ложно, что позволяет вставлять «охранные» проверки прямо в поток отладки.',
        text_en: 'console.log is just one of many debugging tools. Different methods have different visual styles in DevTools and different severity levels, making it easy to filter output.\n\nconsole.warn outputs a yellow warning, console.error outputs a red error message with a stack trace. console.table renders arrays and objects as a table — invaluable when debugging lists. console.group lets you group logs into collapsible sections.\n\nconsole.time / timeEnd measure the execution time of a code segment — handy for simple profiling. console.assert only prints a message if the condition is false, allowing you to embed "guard" checks directly into the debugging flow.',
        code: `// Severity levels\nconsole.log('Loaded 42 items');          // standard info\nconsole.warn('Cache is nearly full');    // yellow ⚠️\nconsole.error('Request failed: 500');   // red ❌ + stack\n\n// Structured data\nconsole.table([\n  { id: 1, name: 'Alice', role: 'admin' },\n  { id: 2, name: 'Bob',   role: 'user'  },\n]);\n\n// Grouped output\nconsole.group('Auth flow');\nconsole.log('1. Token retrieved');\nconsole.log('2. User verified');\nconsole.groupEnd();\n\n// Timing\nconsole.time('sort');\n[3,1,4,1,5,9,2,6].sort((a,b) => a - b);\nconsole.timeEnd('sort'); // 'sort: 0.123ms'\n\n// Conditional logging\nconsole.assert(Array.isArray([]),  'Should be array'); // silent\nconsole.assert(Array.isArray('x'), 'Should be array'); // logs error`,
        codeLang: 'javascript',
      },
      {
        sectionId: 'devtools',
        heading_ru: 'Брейкпоинты и пошаговая отладка в DevTools',
        heading_en: 'Breakpoints and step-through debugging in DevTools',
        text_ru: 'Расстановка брейкпоинтов (breakpoints) в DevTools — намного мощнее, чем добавление console.log в каждую строку. Брейкпоинт приостанавливает выполнение программы в нужном месте, позволяя инспектировать текущие значения всех переменных, scope-цепочку и стек вызовов.\n\nОткройте вкладку Sources в DevTools (F12), найдите нужный файл и кликните на номер строки — появится синяя метка. Обновите страницу или выполните действие, запускающее код. Далее используйте кнопки: F10 (Step over) переходит к следующей строке, F11 (Step into) заходит внутрь функции, Shift+F11 (Step out) выходит из неё.\n\nКлючевое слово debugger в коде работает так же, как визуальный брейкпоинт, но только если DevTools открыты. Это удобно для программной расстановки точек остановки в сложных условиях.',
        text_en: 'Setting breakpoints in DevTools is far more powerful than sprinkling console.log everywhere. A breakpoint pauses program execution at a chosen line, letting you inspect the current values of all variables, the scope chain, and the call stack.\n\nOpen the Sources tab in DevTools (F12), find the file, and click a line number — a blue marker appears. Reload the page or trigger the code path. Then use the controls: F10 (Step over) moves to the next line, F11 (Step into) enters a function call, Shift+F11 (Step out) exits the current function.\n\nThe debugger keyword in code acts exactly like a visual breakpoint, but only when DevTools are open. This is useful for programmatically placing stop points under complex conditions.',
        code: `function processOrder(order) {\n  debugger; // execution pauses here when DevTools is open\n\n  const subtotal = order.items.reduce(\n    (sum, item) => sum + item.price * item.qty, 0\n  );\n\n  const tax = subtotal * 0.2;\n  const total = subtotal + tax;\n\n  return { subtotal, tax, total };\n}\n\n// DevTools Sources workflow:\n// 1. Open DevTools  →  Sources tab\n// 2. Click line number to set a breakpoint (blue dot appears)\n// 3. Run the code / refresh the page\n// 4. Execution pauses → inspect variables in Scope panel\n// 5. F10  = step over (next line)\n//    F11  = step into (enter function)\n//    Shift+F11 = step out (exit current function)\n//    F8   = resume (continue to next breakpoint)`,
        codeLang: 'javascript',
      },
      {
        sectionId: 'throw',
        heading_ru: 'Пользовательские классы ошибок',
        heading_en: 'Custom error classes',
        text_ru: 'Для сложных приложений можно создавать собственные типы ошибок, наследуясь от Error.',
        text_en: 'For complex applications you can create custom error types by extending Error.',
        code: `class ValidationError extends Error {\n  constructor(field, message) {\n    super(message);\n    this.name = 'ValidationError';\n    this.field = field;\n  }\n}\n\nfunction validateAge(age) {\n  if (age < 0 || age > 150) {\n    throw new ValidationError('age', \`Invalid age: \${age}\`);\n  }\n  return age;\n}\n\ntry {\n  validateAge(-5);\n} catch (e) {\n  if (e instanceof ValidationError) {\n    console.log(\`Field '\${e.field}': \${e.message}\`);\n  } else {\n    throw e; // re-throw unknown errors\n  }\n}`,
        codeLang: 'javascript',
      },
      {
        sectionId: 'common-mistakes',
        heading_ru: 'Асинхронные ошибки',
        heading_en: 'Async errors',
        text_ru: 'try/catch не поймает ошибки в асинхронном коде, если не используется async/await. Для промисов используйте .catch().',
        text_en: 'try/catch will not catch errors in async code unless you use async/await. For promises use .catch().',
        code: `// Wrong — error not caught!\ntry {\n  setTimeout(() => { throw new Error('async!'); }, 100);\n} catch(e) { /* never runs */ }\n\n// Correct with Promise + .catch()\nfetch('/api/data')\n  .then(r => r.json())\n  .catch(e => console.error('Fetch failed:', e));\n\n// Correct with async/await\nasync function getData() {\n  try {\n    const res = await fetch('/api/data');\n    return await res.json();\n  } catch (e) {\n    console.error('Fetch failed:', e);\n  }\n}`,
        codeLang: 'javascript',
      },
    ],
  },
  editorTask: {
    title_ru: 'Безопасный калькулятор',
    title_en: 'Safe calculator',
    instructions_ru: 'Напишите функцию calculate(a, operator, b), которая выполняет арифметику. Используйте throw для валидации и try/catch для обработки. Поддержите: +, -, *, /.',
    instructions_en: 'Write a function calculate(a, operator, b) that performs arithmetic. Use throw for validation and try/catch for handling. Support: +, -, *, /.',
    activeTabs: ['javascript'],
    starterCode: {
      javascript: `function calculate(a, operator, b) {\n  // Validate: a and b must be numbers\n  if (typeof a !== 'number' || typeof b !== 'number') {\n    throw new TypeError('Both operands must be numbers');\n  }\n\n  // Validate: operator must be +, -, *, /\n  const validOps = ['+', '-', '*', '/'];\n  if (!validOps.includes(operator)) {\n    throw new Error(\`Unknown operator: \${operator}\`);\n  }\n\n  // TODO: handle division by zero (throw RangeError)\n\n  // TODO: implement and return result for +, -, *, /\n  // Hint: use a switch statement or if/else\n}\n\n// Test cases — wrap each in try/catch\nconst tests = [\n  [10, '+', 5],\n  [10, '/', 0],\n  ['ten', '*', 5],\n  [10, '^', 2],\n];\n\ntests.forEach(([a, op, b]) => {\n  try {\n    console.log(\`\${a} \${op} \${b} = \${calculate(a, op, b)}\`);\n  } catch(e) {\n    console.error(\`\${e.name}: \${e.message}\`);\n  }\n});`,
    },
    hints_ru: [
      'Для деления на ноль: if (operator === "/" && b === 0) throw new RangeError("Division by zero")',
      'switch(operator) { case "+": return a + b; case "-": return a - b; ... }',
      'Каждый тест-кейс обёрнут в try/catch — ошибки отловятся автоматически',
    ],
    hints_en: [
      'For division by zero: if (operator === "/" && b === 0) throw new RangeError("Division by zero")',
      'switch(operator) { case "+": return a + b; case "-": return a - b; ... }',
      'Each test case is wrapped in try/catch — errors will be caught automatically',
    ],
  },
  keyTerms: [
    { term_ru: 'SyntaxError', term_en: 'SyntaxError', definition_ru: 'Ошибка синтаксиса — код не может быть разобран', definition_en: 'Syntax error — code cannot be parsed', example_ru: 'Непарные скобки, неправильное выражение', example_en: 'Unmatched brackets, invalid expression' },
    { term_ru: 'TypeError', term_en: 'TypeError', definition_ru: 'Ошибка типа — операция с неподходящим типом', definition_en: 'Type error — operation on an inappropriate type', example_ru: 'null.toString(), вызов не-функции', example_en: 'null.toString(), calling a non-function' },
    { term_ru: 'ReferenceError', term_en: 'ReferenceError', definition_ru: 'Обращение к необъявленной переменной', definition_en: 'Access to an undeclared variable', example_ru: 'console.log(x) где x не объявлен', example_en: 'console.log(x) where x is not declared' },
    { term_ru: 'try/catch', term_en: 'try/catch', definition_ru: 'Конструкция для перехвата и обработки ошибок', definition_en: 'A construct for catching and handling errors', example_ru: 'try { risky() } catch(e) { handle(e) }', example_en: 'try { risky() } catch(e) { handle(e) }' },
    { term_ru: 'Брейкпоинт', term_en: 'Breakpoint', definition_ru: 'Точка остановки выполнения кода для отладки', definition_en: 'A point where code execution is paused for debugging', example_ru: 'Клик на номер строки в DevTools Sources', example_en: 'Click a line number in DevTools Sources' },
  ],
  didYouKnow: [
    { text_ru: 'Оператор typeof null возвращает "object" — это историческая ошибка в JavaScript, которую не исправляют для обратной совместимости.', text_en: 'typeof null returns "object" — this is a historical JavaScript bug that is not fixed for backward compatibility.' },
    { text_ru: 'console.table() — один из самых недооценённых методов. Он отображает массивы объектов в красивой таблице прямо в консоли DevTools.', text_en: 'console.table() is one of the most underrated methods. It displays arrays of objects as a nice table right in the DevTools console.' },
  ],
  quiz: [
    { id: 'q1', text_ru: 'Какой тип ошибки возникает при обращении к необъявленной переменной?', text_en: 'What error type occurs when accessing an undeclared variable?', options_ru: ['TypeError', 'SyntaxError', 'ReferenceError', 'RangeError'], options_en: ['TypeError', 'SyntaxError', 'ReferenceError', 'RangeError'], correctIndex: 2, explanation_ru: 'ReferenceError возникает при обращении к переменной, которая не была объявлена.', explanation_en: 'ReferenceError occurs when accessing a variable that was never declared.' },
    { id: 'q2', text_ru: 'Что гарантированно выполняется вне зависимости от того, была ли ошибка?', text_en: 'What is guaranteed to run regardless of whether an error occurred?', options_ru: ['try', 'catch', 'finally', 'throw'], options_en: ['try', 'catch', 'finally', 'throw'], correctIndex: 2, explanation_ru: 'Блок finally выполняется всегда — и при успехе, и при ошибке.', explanation_en: 'The finally block always runs — both on success and on error.' },
    { id: 'q3', text_ru: 'Как вывести объект в виде таблицы в консоли?', text_en: 'How do you print an object as a table in the console?', options_ru: ['console.log()', 'console.warn()', 'console.table()', 'console.grid()'], options_en: ['console.log()', 'console.warn()', 'console.table()', 'console.grid()'], correctIndex: 2, explanation_ru: 'console.table() отображает массивы и объекты в виде удобной таблицы.', explanation_en: 'console.table() displays arrays and objects as a convenient table.' },
    { id: 'q4', text_ru: 'Что делает ключевое слово throw?', text_en: 'What does the throw keyword do?', options_ru: ['Ловит ошибку', 'Генерирует (бросает) ошибку', 'Логирует сообщение', 'Останавливает скрипт навсегда'], options_en: ['Catches an error', 'Generates (throws) an error', 'Logs a message', 'Stops the script forever'], correctIndex: 1, explanation_ru: 'throw генерирует ошибку. Если её не поймать через catch, скрипт остановится.', explanation_en: 'throw generates an error. If not caught via catch, the script will stop.' },
    { id: 'q5', text_ru: 'Что означает ошибка TypeError: null is not an object?', text_en: 'What does TypeError: null is not an object mean?', options_ru: ['Синтаксическая ошибка', 'Попытка получить свойство у null/undefined', 'Не найдена переменная', 'Неверный диапазон'], options_en: ['A syntax error', 'Attempting to access a property of null/undefined', 'Variable not found', 'Invalid range'], correctIndex: 1, explanation_ru: 'TypeError: null is not an object означает попытку обратиться к свойству null (например, null.name).', explanation_en: 'TypeError: null is not an object means trying to access a property of null (e.g. null.name).' },
  ],
}
