import type { Lesson } from '@/types/lesson'

export const jsEvents: Lesson = {
  slug: 'js-events',
  category: 'JS',
  icon: '👆',
  readTime: 11,
  title_ru: 'События в JavaScript',
  title_en: 'JavaScript Events',
  description_ru: 'Научитесь обрабатывать клики, ввод, клавиатуру. Поймёте объект события, делегирование и removeEventListener.',
  description_en: 'Learn to handle clicks, input, keyboard. Understand the event object, delegation and removeEventListener.',
  sections: [
    { id: 'addeventlistener', title_ru: 'addEventListener', title_en: 'addEventListener' },
    { id: 'common-events', title_ru: 'Частые события', title_en: 'Common events' },
    { id: 'event-object', title_ru: 'Объект события', title_en: 'Event object' },
    { id: 'prevent-stop', title_ru: 'preventDefault и stopPropagation', title_en: 'preventDefault and stopPropagation' },
    { id: 'delegation', title_ru: 'Делегирование событий', title_en: 'Event delegation' },
    { id: 'remove', title_ru: 'removeEventListener', title_en: 'removeEventListener' },
  ],
  slides: [
    {
      id: 'title-slide',
      type: 'title',
      title_ru: 'События в JavaScript',
      title_en: 'JavaScript Events',
      body_ru: 'События — это сигналы от браузера о действиях пользователя. addEventListener связывает эти сигналы с вашим кодом.',
      body_en: 'Events are signals from the browser about user actions. addEventListener connects these signals to your code.',
      visual: { kind: 'emoji', emojis: ['👆', '⌨️', '🖱️'], caption_ru: 'Клики, ввод, мышь', caption_en: 'Clicks, input, mouse' },
    },
    {
      id: 'concept-addeventlistener',
      type: 'concept',
      title_ru: 'addEventListener — правильный способ',
      title_en: 'addEventListener — the right way',
      body_ru: 'addEventListener(type, handler) регистрирует функцию-обработчик. Можно добавить несколько обработчиков к одному элементу.',
      body_en: 'addEventListener(type, handler) registers a handler function. You can add multiple handlers to the same element.',
      code: `const btn = document.querySelector('#myBtn');\n\n// Add an event listener\nbtn.addEventListener('click', function() {\n  console.log('Button clicked!');\n});\n\n// Arrow function works too\nbtn.addEventListener('click', () => {\n  btn.textContent = 'Clicked!';\n});\n\n// Multiple listeners on same element — both fire\nbtn.addEventListener('click', () => console.log('Second listener'));`,
      codeLang: 'javascript',
    },
    {
      id: 'compare-onclick-listener',
      type: 'compare',
      title_ru: 'onclick="" (плохо) vs addEventListener (хорошо)',
      title_en: 'onclick="" (bad) vs addEventListener (good)',
      body_ru: 'Используйте addEventListener в JavaScript-коде, а не атрибуты onclick в HTML.',
      body_en: 'Use addEventListener in JavaScript code, not onclick attributes in HTML.',
      compareLeft: {
        label_ru: 'Inline onclick="" — плохо',
        label_en: 'Inline onclick="" — bad',
        items_ru: ['HTML смешивается с логикой', 'Только один обработчик', 'Нельзя удалить программно', '<button onclick="doSomething()">'],
        items_en: ['HTML mixed with logic', 'Only one handler allowed', 'Cannot be removed programmatically', '<button onclick="doSomething()">'],
        color: 'red',
      },
      compareRight: {
        label_ru: 'addEventListener — хорошо',
        label_en: 'addEventListener — good',
        items_ru: ['Разделение HTML и JS', 'Несколько обработчиков', 'Можно удалить позже', 'btn.addEventListener("click", fn)'],
        items_en: ['Separation of HTML and JS', 'Multiple handlers possible', 'Can be removed later', 'btn.addEventListener("click", fn)'],
        color: 'green',
      },
    },
    {
      id: 'concept-common-events',
      type: 'concept',
      title_ru: 'Частые типы событий',
      title_en: 'Common event types',
      body_ru: 'Браузер предоставляет десятки типов событий. Вот самые используемые в повседневной разработке.',
      body_en: 'The browser provides dozens of event types. Here are the most commonly used in everyday development.',
      code: `// Mouse\nelement.addEventListener('click', handler);\nelement.addEventListener('dblclick', handler);\nelement.addEventListener('mouseover', handler);\nelement.addEventListener('mouseout', handler);\n\n// Keyboard\ndocument.addEventListener('keydown', handler);\ndocument.addEventListener('keyup', handler);\n\n// Form\ninput.addEventListener('input', handler);   // on every keystroke\nform.addEventListener('submit', handler);\nselect.addEventListener('change', handler);\n\n// Window\nwindow.addEventListener('load', handler);\nwindow.addEventListener('resize', handler);`,
      codeLang: 'javascript',
    },
    {
      id: 'concept-event-object',
      type: 'concept',
      title_ru: 'Объект события (event)',
      title_en: 'The event object',
      body_ru: 'Обработчик получает объект события с полезными свойствами: e.target (элемент, вызвавший событие), e.key, e.clientX, e.clientY и другими.',
      body_en: 'The handler receives an event object with useful properties: e.target (element that triggered the event), e.key, e.clientX, e.clientY and more.',
      code: `document.addEventListener('click', (e) => {\n  console.log(e.target);       // element that was clicked\n  console.log(e.clientX);     // X position of click\n  console.log(e.clientY);     // Y position of click\n  console.log(e.type);        // 'click'\n});\n\ndocument.addEventListener('keydown', (e) => {\n  console.log(e.key);         // 'Enter', 'a', 'ArrowUp'...\n  console.log(e.code);        // 'KeyA', 'Space'...\n  console.log(e.ctrlKey);     // true if Ctrl held\n});`,
      codeLang: 'javascript',
    },
    {
      id: 'concept-prevent-stop',
      type: 'concept',
      title_ru: 'preventDefault и stopPropagation',
      title_en: 'preventDefault and stopPropagation',
      body_ru: 'preventDefault отменяет поведение браузера по умолчанию. stopPropagation останавливает всплытие события к родительским элементам.',
      body_en: 'preventDefault cancels the browser default behavior. stopPropagation stops the event from bubbling up to parent elements.',
      code: `// Prevent form from reloading the page\nform.addEventListener('submit', (e) => {\n  e.preventDefault();\n  console.log('Form handled by JS!');\n});\n\n// Prevent link navigation\nlink.addEventListener('click', (e) => {\n  e.preventDefault();\n  console.log('Link click intercepted');\n});\n\n// Stop event bubbling\nchild.addEventListener('click', (e) => {\n  e.stopPropagation(); // parent click won't fire\n  console.log('Only child handler runs');\n});`,
      codeLang: 'javascript',
    },
    {
      id: 'concept-delegation',
      type: 'concept',
      title_ru: 'Делегирование событий',
      title_en: 'Event delegation',
      body_ru: 'Вместо добавления обработчика к каждому дочернему элементу, добавьте один обработчик к родителю и проверьте e.target.',
      body_en: 'Instead of adding a handler to each child element, add one handler to the parent and check e.target.',
      code: `// Without delegation (bad for large lists):\ndocument.querySelectorAll('.item').forEach(item => {\n  item.addEventListener('click', handleClick);\n});\n\n// With delegation (efficient):\ndocument.querySelector('#list').addEventListener('click', (e) => {\n  if (e.target.classList.contains('item')) {\n    console.log('Item clicked:', e.target.textContent);\n  }\n});\n\n// Also works for dynamically added elements!`,
      codeLang: 'javascript',
    },
    {
      id: 'anim-events',
      type: 'code-anim',
      title_ru: 'Интерактивная кнопка шаг за шагом',
      title_en: 'Interactive button step by step',
      body_ru: 'Строим кнопку с кликом, изменением текста и слушателем клавиатуры.',
      body_en: 'Build a button with click, text change and keyboard listener.',
      animMode: 'preview',
      animSteps: [
        {
          code: `<button id="btn">Click me</button>\n<p id="msg"></p>`,
          comment_ru: 'HTML-структура: кнопка и параграф для сообщения',
          comment_en: 'HTML structure: button and paragraph for message',
          preview: '<button style="padding:8px 16px">Click me</button><p></p>',
        },
        {
          code: `const btn = document.querySelector('#btn');\nconst msg = document.querySelector('#msg');\n\nbtn.addEventListener('click', () => {\n  btn.textContent = 'Clicked!';\n  msg.textContent = 'Button was clicked!';\n});`,
          comment_ru: 'Добавляем обработчик клика — меняем текст',
          comment_en: 'Add click handler — change text',
          preview: '<button style="padding:8px 16px;background:#4ade80">Clicked!</button><p>Button was clicked!</p>',
        },
        {
          code: `document.addEventListener('keydown', (e) => {\n  if (e.key === 'Enter') {\n    msg.textContent = \`Enter pressed! Key: \${e.key}\`;\n  }\n});`,
          comment_ru: 'Слушаем клавишу Enter на всём документе',
          comment_en: 'Listen for Enter key on the whole document',
          preview: '<button style="padding:8px 16px;background:#4ade80">Clicked!</button><p>Enter pressed! Key: Enter</p>',
        },
      ],
    },
    {
      id: 'concept-remove',
      type: 'concept',
      title_ru: 'removeEventListener',
      title_en: 'removeEventListener',
      body_ru: 'removeEventListener удаляет обработчик. ВАЖНО: функция должна быть той же ссылкой — анонимные функции удалить нельзя.',
      body_en: 'removeEventListener removes a handler. IMPORTANT: the function must be the same reference — anonymous functions cannot be removed.',
      code: `// WRONG — can't remove anonymous function\nbtn.addEventListener('click', () => console.log('hi'));\nbtn.removeEventListener('click', () => console.log('hi')); // does nothing!\n\n// CORRECT — use named function\nfunction handleClick() { console.log('hi'); }\nbtn.addEventListener('click', handleClick);\nbtn.removeEventListener('click', handleClick); // works!`,
      codeLang: 'javascript',
    },
    {
      id: 'tip-once',
      type: 'tip',
      title_ru: 'Совет: опция once',
      title_en: 'Tip: the once option',
      body_ru: 'Передайте { once: true } третьим аргументом, чтобы обработчик сработал один раз и автоматически удалился.',
      body_en: 'Pass { once: true } as the third argument to make the handler fire once and automatically remove itself.',
      code: `btn.addEventListener('click', handleClick, { once: true });`,
      codeLang: 'javascript',
    },
    {
      id: 'practice-cta',
      type: 'practice-cta',
      title_ru: 'Практика',
      title_en: 'Practice',
      body_ru: 'Создайте интерактивный счётчик кликов с кнопками + и –.',
      body_en: 'Build an interactive click counter with + and – buttons.',
    },
  ],
  content: {
    intro_ru: 'События — основа интерактивности в вебе. Каждый раз, когда пользователь что-то делает (кликает, печатает, прокручивает страницу), браузер генерирует событие. Ваша задача — поймать его и ответить.',
    intro_en: 'Events are the foundation of web interactivity. Every time a user does something (clicks, types, scrolls), the browser fires an event. Your job is to catch it and respond.',
    blocks: [
      {
        sectionId: 'addeventlistener',
        heading_ru: 'Как работает addEventListener изнутри',
        heading_en: 'How addEventListener works under the hood',
        text_ru: 'addEventListener регистрирует обработчик в внутреннем списке слушателей элемента. Когда происходит событие указанного типа, браузер последовательно вызывает все зарегистрированные обработчики в порядке их добавления.\n\nВажное отличие от свойства onclick: один элемент может иметь неограниченное количество обработчиков одного типа. Если вы дважды зарегистрируете одну и ту же функцию с теми же параметрами — дубликат будет проигнорирован. Но если функции разные (даже если тело идентично), оба обработчика сработают.\n\nTretий необязательный аргумент — объект options или булево значение useCapture. Через options можно передать { once: true } (срабатывает один раз), { passive: true } (улучшает производительность скролла) или { capture: true } (обработчик перехватывает событие на фазе захвата, а не всплытия).',
        text_en: 'addEventListener registers a handler in the element\'s internal listener list. When an event of the specified type occurs, the browser calls all registered handlers in the order they were added.\n\nThe key difference from the onclick property: one element can have an unlimited number of handlers for the same event type. If you register the exact same function twice with the same parameters, the duplicate is silently ignored. But if the functions are different (even if their bodies are identical), both handlers will fire.\n\nThe optional third argument is an options object or a boolean useCapture value. Via options you can pass { once: true } (fires only once), { passive: true } (improves scroll performance), or { capture: true } (handler intercepts the event in the capture phase rather than the bubbling phase).',
        code: `const btn = document.querySelector('#btn');\n\n// Basic usage\nbtn.addEventListener('click', () => {\n  console.log('clicked!');\n});\n\n// Multiple handlers — both fire independently\nbtn.addEventListener('click', () => console.log('handler 1'));\nbtn.addEventListener('click', () => console.log('handler 2'));\n\n// Options: fire once then auto-remove\nbtn.addEventListener('click', () => {\n  console.log('This fires only once');\n}, { once: true });\n\n// Options: passive scroll listener (better performance)\nwindow.addEventListener('scroll', onScroll, { passive: true });\n\n// Capture phase — fires before the target's own handlers\ndocument.addEventListener('click', onCapture, { capture: true });`,
        codeLang: 'javascript',
      },
      {
        sectionId: 'event-object',
        heading_ru: 'Полезные свойства объекта события',
        heading_en: 'Useful event object properties',
        text_ru: 'Каждый обработчик событий автоматически получает объект события (обычно называемый e или event). Этот объект содержит всю информацию о произошедшем: где, когда, что именно случилось и на каком элементе.\n\nСвойство e.target — элемент, на котором непосредственно произошло событие (например, конкретная кнопка). e.currentTarget — элемент, на котором зарегистрирован обработчик (они могут отличаться при всплытии). e.type возвращает строку с именем события (\'click\', \'keydown\' и т.д.).\n\nДля событий мыши важны e.clientX / e.clientY (координаты относительно окна браузера) и e.button (какая кнопка мыши нажата). Для клавиатурных событий — e.key (читаемое название клавиши, например \'Enter\' или \'ArrowLeft\') и e.code (физическая позиция на клавиатуре, например \'KeyA\'). Модификаторы e.ctrlKey, e.shiftKey, e.altKey, e.metaKey указывают, были ли зажаты соответствующие клавиши.',
        text_en: 'Every event handler automatically receives an event object (commonly named e or event). This object carries all information about what happened: where, when, what exactly, and on which element.\n\nThe e.target property is the element where the event actually occurred (e.g. the specific button clicked). e.currentTarget is the element where the handler is registered — these can differ when events bubble. e.type returns the event name as a string (\'click\', \'keydown\', etc.).\n\nFor mouse events, e.clientX / e.clientY (coordinates relative to the browser window) and e.button (which mouse button was pressed) are important. For keyboard events, e.key (human-readable key name, e.g. \'Enter\' or \'ArrowLeft\') and e.code (physical keyboard position, e.g. \'KeyA\') are key. The modifiers e.ctrlKey, e.shiftKey, e.altKey, and e.metaKey indicate whether the corresponding modifier keys were held.',
        code: `// Mouse event properties\ndocument.addEventListener('click', (e) => {\n  console.log('target:   ', e.target);      // exact clicked element\n  console.log('current:  ', e.currentTarget); // element with listener\n  console.log('position: ', e.clientX, e.clientY);\n  console.log('button:   ', e.button); // 0=left, 1=middle, 2=right\n});\n\n// Keyboard event properties\ndocument.addEventListener('keydown', (e) => {\n  console.log('key: ', e.key);    // 'a', 'Enter', 'ArrowUp'\n  console.log('code:', e.code);   // 'KeyA', 'Enter', 'ArrowUp'\n\n  // Detecting keyboard shortcuts\n  if (e.ctrlKey && e.key === 's') {\n    e.preventDefault(); // stop browser "Save page" dialog\n    console.log('Ctrl+S intercepted — save triggered');\n  }\n});\n\n// Input event — fires on every keystroke\nconst input = document.querySelector('#search');\ninput.addEventListener('input', (e) => {\n  console.log('Current value:', e.target.value);\n});`,
        codeLang: 'javascript',
      },
      {
        sectionId: 'prevent-stop',
        heading_ru: 'Управление поведением и распространением события',
        heading_en: 'Controlling event behavior and propagation',
        text_ru: 'Браузер имеет встроенное поведение для многих событий: отправка формы перезагружает страницу, клик по ссылке открывает URL, правый клик показывает контекстное меню. Метод e.preventDefault() отменяет только это браузерное поведение — ваши обработчики продолжают работать нормально.\n\nСобытия в DOM «всплывают» снизу вверх по дереву: сначала срабатывает обработчик на элементе-цели, затем на его родителе, затем на родителе родителя и так до window. Метод e.stopPropagation() прерывает это всплытие — вышестоящие обработчики не получат событие. Если на одном элементе несколько обработчиков одного события, e.stopImmediatePropagation() остановит и остальные обработчики того же элемента.\n\nИспользуйте эти методы осторожно: stopPropagation может сломать делегирование событий или сторонние библиотеки, которые слушают события на родительских элементах.',
        text_en: 'The browser has built-in behavior for many events: submitting a form reloads the page, clicking a link opens a URL, right-clicking shows a context menu. The e.preventDefault() method cancels only this browser-native behavior — your own handlers continue running normally.\n\nDOM events "bubble" upward through the tree: first the handler on the target element fires, then on its parent, then on the parent\'s parent, all the way up to window. The e.stopPropagation() method interrupts this bubbling — handlers on ancestor elements will not receive the event. If multiple handlers are registered for the same event on the same element, e.stopImmediatePropagation() will also stop the remaining handlers on that element.\n\nUse these methods with care: stopPropagation can break event delegation or third-party libraries that listen for events on parent elements.',
        code: `// preventDefault — cancel browser default without stopping handlers\nconst form = document.querySelector('#signupForm');\nform.addEventListener('submit', (e) => {\n  e.preventDefault(); // no page reload\n  const email = form.querySelector('[name=email]').value;\n  if (!email.includes('@')) {\n    showError('Invalid email');\n    return;\n  }\n  submitToAPI(email);\n});\n\n// Prevent link navigation\nconst link = document.querySelector('.ajax-link');\nlink.addEventListener('click', (e) => {\n  e.preventDefault();          // don't navigate\n  loadContent(link.href);      // load via AJAX instead\n});\n\n// stopPropagation — stop bubbling to parent handlers\nconst modal = document.querySelector('#modal');\nconst overlay = document.querySelector('#overlay');\n\noverlay.addEventListener('click', () => modal.close()); // close on backdrop\nmodal.addEventListener('click', (e) => {\n  e.stopPropagation(); // click inside modal doesn't reach overlay\n});`,
        codeLang: 'javascript',
      },
      {
        sectionId: 'delegation',
        heading_ru: 'Всплытие событий (event bubbling)',
        heading_en: 'Event bubbling',
        text_ru: 'Когда событие происходит на элементе, оно "всплывает" вверх по дереву DOM к родительским элементам. Именно это позволяет работать делегированию.',
        text_en: 'When an event occurs on an element, it "bubbles" up through the DOM tree to parent elements. This is exactly what makes delegation work.',
        code: `// Bubbling: click on <span> inside <div> fires both handlers\ndiv.addEventListener('click', () => console.log('div clicked'));\nspan.addEventListener('click', () => console.log('span clicked'));\n// Clicking span prints: "span clicked" then "div clicked"`,
        codeLang: 'javascript',
      },
      {
        sectionId: 'common-events',
        heading_ru: 'Работа с формами',
        heading_en: 'Working with forms',
        text_ru: 'Форма — один из самых важных источников событий. Всегда перехватывайте submit и используйте e.preventDefault().',
        text_en: 'Forms are one of the most important event sources. Always intercept submit and use e.preventDefault().',
        code: `const form = document.querySelector('#loginForm');\n\nform.addEventListener('submit', (e) => {\n  e.preventDefault(); // stop page reload\n\n  const username = document.querySelector('#username').value;\n  const password = document.querySelector('#password').value;\n\n  if (!username || !password) {\n    alert('Fill in all fields!');\n    return;\n  }\n\n  console.log('Logging in:', username);\n  // send data to server here\n});`,
        codeLang: 'javascript',
      },
      {
        sectionId: 'remove',
        heading_ru: 'Когда и зачем удалять обработчики событий',
        heading_en: 'When and why to remove event listeners',
        text_ru: 'Обработчики событий, которые больше не нужны, стоит удалять — иначе они продолжают работать в фоне и могут вызвать утечки памяти или неожиданное поведение. Типичные случаи: одноразовые действия (например, анимация приветствия), обработчики на элементах, удалённых из DOM, и очистка при уничтожении компонента в SPA-фреймворках.\n\nГлавное правило removeEventListener: вы должны передать ту же самую ссылку на функцию, что и при addEventListener. Анонимные стрелочные функции — уникальные объекты при каждом создании, поэтому их нельзя удалить. Всегда сохраняйте ссылку на обработчик в переменную, если планируете его удалять.\n\nАльтернатива ручному удалению — опция { once: true }, которую можно передать третьим аргументом в addEventListener. Браузер автоматически удалит обработчик после первого вызова. Также можно использовать AbortController: создайте контроллер, передайте его signal в options, и вызов controller.abort() удалит сразу все связанные слушатели.',
        text_en: 'Event handlers that are no longer needed should be removed — otherwise they keep running in the background and can cause memory leaks or unexpected behavior. Typical cases: one-time actions (such as a welcome animation), handlers on elements removed from the DOM, and cleanup when a component is destroyed in SPA frameworks.\n\nThe key rule for removeEventListener: you must pass the exact same function reference that was used with addEventListener. Anonymous arrow functions are unique objects each time they are created, so they cannot be removed. Always store the handler in a variable if you plan to remove it later.\n\nAn alternative to manual removal is the { once: true } option, which can be passed as the third argument to addEventListener. The browser automatically removes the handler after its first invocation. You can also use AbortController: create a controller, pass its signal in the options object, and calling controller.abort() removes all associated listeners at once.',
        code: `// WRONG: anonymous function — cannot be removed\nbtn.addEventListener('click', () => console.log('clicked'));\nbtn.removeEventListener('click', () => console.log('clicked')); // no-op!\n\n// CORRECT: named function reference\nfunction handleClick(e) {\n  console.log('Button clicked:', e.target);\n}\nbtn.addEventListener('click', handleClick);\n// ... later, when no longer needed:\nbtn.removeEventListener('click', handleClick); // works!\n\n// Auto-remove with { once: true }\nbtn.addEventListener('click', () => {\n  console.log('Fires once, then auto-removed');\n}, { once: true });\n\n// Remove multiple listeners at once with AbortController\nconst controller = new AbortController();\nconst { signal } = controller;\n\nbtn.addEventListener('click',    handleClick, { signal });\nbtn.addEventListener('keydown',  handleKey,   { signal });\nwindow.addEventListener('resize', handleResize, { signal });\n\n// Later: remove all three in one call\ncontroller.abort();`,
        codeLang: 'javascript',
      },
    ],
  },
  editorTask: {
    title_ru: 'Интерактивный счётчик кликов',
    title_en: 'Interactive click counter',
    instructions_ru: 'Создайте счётчик с двумя кнопками: + (увеличить) и – (уменьшить). Счёт не должен уходить ниже 0. Цвет счёта должен меняться: зелёный (>0), серый (=0).',
    instructions_en: 'Build a counter with two buttons: + (increment) and – (decrement). Count should not go below 0. Color should change: green (>0), grey (=0).',
    activeTabs: ['html', 'javascript'],
    starterCode: {
      html: `<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <title>Click Counter</title>\n  <style>\n    body { font-family: sans-serif; text-align: center; padding: 40px; }\n    #count { font-size: 3rem; margin: 20px; }\n    button { font-size: 1.5rem; padding: 10px 24px; margin: 5px; cursor: pointer; }\n    .positive { color: #22c55e; }\n    .zero { color: #9ca3af; }\n  </style>\n</head>\n<body>\n  <h1>Click Counter</h1>\n  <div id="count" class="zero">0</div>\n  <button id="decrease">–</button>\n  <button id="increase">+</button>\n  <script src="script.js"></script>\n</body>\n</html>`,
      javascript: `const countEl = document.querySelector('#count');\nconst increaseBtn = document.querySelector('#increase');\nconst decreaseBtn = document.querySelector('#decrease');\n\nlet count = 0;\n\nfunction updateDisplay() {\n  countEl.textContent = count;\n  // TODO: update class to 'positive' or 'zero' based on count\n}\n\n// TODO: add click listener to increaseBtn → increase count, call updateDisplay\n\n// TODO: add click listener to decreaseBtn → decrease count (min 0), call updateDisplay`,
    },
    hints_ru: [
      'increaseBtn.addEventListener("click", () => { count++; updateDisplay(); })',
      'Для уменьшения: if (count > 0) count--;',
      'Класс: countEl.className = count > 0 ? "positive" : "zero";',
    ],
    hints_en: [
      'increaseBtn.addEventListener("click", () => { count++; updateDisplay(); })',
      'To decrement: if (count > 0) count--;',
      'Class: countEl.className = count > 0 ? "positive" : "zero";',
    ],
  },
  keyTerms: [
    { term_ru: 'Событие', term_en: 'Event', definition_ru: 'Сигнал браузера о произошедшем действии (клик, ввод, загрузка)', definition_en: 'A browser signal about an action that occurred (click, input, load)', example_ru: 'click, submit, keydown, mouseover', example_en: 'click, submit, keydown, mouseover' },
    { term_ru: 'Обработчик (handler)', term_en: 'Handler', definition_ru: 'Функция, вызываемая при наступлении события', definition_en: 'A function called when an event occurs', example_ru: 'btn.addEventListener("click", handler)', example_en: 'btn.addEventListener("click", handler)' },
    { term_ru: 'Всплытие (bubbling)', term_en: 'Bubbling', definition_ru: 'Распространение события вверх по DOM-дереву', definition_en: 'Event propagation upward through the DOM tree', example_ru: 'Клик на дочернем элементе → срабатывает у родителя', example_en: 'Click on child → fires on parent too' },
    { term_ru: 'Делегирование событий', term_en: 'Event delegation', definition_ru: 'Назначение одного обработчика родителю вместо многих дочерним', definition_en: 'Assigning one handler to parent instead of many to children', example_ru: 'list.addEventListener("click", e => { if (e.target.matches(".item")) ... })', example_en: 'list.addEventListener("click", e => { if (e.target.matches(".item")) ... })' },
    { term_ru: 'e.preventDefault()', term_en: 'e.preventDefault()', definition_ru: 'Отменяет поведение браузера по умолчанию', definition_en: 'Cancels the browser default behavior', example_ru: 'Предотвращает отправку формы или переход по ссылке', example_en: 'Prevents form submission or link navigation' },
  ],
  didYouKnow: [
    { text_ru: 'Существует более 100 типов событий в браузере! От animationend до visibilitychange. Полный список есть на MDN.', text_en: 'There are over 100 event types in the browser! From animationend to visibilitychange. The full list is on MDN.' },
    { text_ru: 'addEventListener поддерживает третий аргумент с опциями: { once, capture, passive }. Опция passive: true улучшает производительность скролла.', text_en: 'addEventListener supports a third argument with options: { once, capture, passive }. The passive: true option improves scroll performance.' },
  ],
  quiz: [
    { id: 'q1', text_ru: 'Как правильно добавить обработчик клика на кнопку?', text_en: 'How do you properly add a click handler to a button?', options_ru: ['btn.onclick = "doThing()"', 'btn.addEventListener("click", doThing)', 'btn.click(doThing)', '<button onclick="doThing()">'], options_en: ['btn.onclick = "doThing()"', 'btn.addEventListener("click", doThing)', 'btn.click(doThing)', '<button onclick="doThing()">'], correctIndex: 1, explanation_ru: 'addEventListener — правильный способ: разделяет HTML и JS, поддерживает несколько обработчиков.', explanation_en: 'addEventListener is the correct way: separates HTML and JS, supports multiple handlers.' },
    { id: 'q2', text_ru: 'Что делает e.preventDefault()?', text_en: 'What does e.preventDefault() do?', options_ru: ['Останавливает всплытие', 'Отменяет действие браузера по умолчанию', 'Удаляет обработчик', 'Вызывает ошибку'], options_en: ['Stops bubbling', 'Cancels the browser default action', 'Removes the handler', 'Throws an error'], correctIndex: 1, explanation_ru: 'preventDefault отменяет поведение браузера: отправку формы, переход по ссылке и т.д.', explanation_en: 'preventDefault cancels the browser behavior: form submission, link navigation etc.' },
    { id: 'q3', text_ru: 'Что такое делегирование событий?', text_en: 'What is event delegation?', options_ru: ['Копирование обработчика', 'Один обработчик на родителе для всех дочерних элементов', 'Удаление событий', 'Тип анимации'], options_en: ['Copying a handler', 'One handler on parent for all child elements', 'Removing events', 'A type of animation'], correctIndex: 1, explanation_ru: 'Делегирование использует всплытие: один обработчик на родителе обрабатывает события всех потомков.', explanation_en: 'Delegation uses bubbling: one parent handler handles events from all descendants.' },
    { id: 'q4', text_ru: 'Почему нельзя удалить анонимный обработчик через removeEventListener?', text_en: 'Why can you not remove an anonymous handler with removeEventListener?', options_ru: ['Это запрещено браузером', 'У анонимной функции нет ссылки для сравнения', 'removeEventListener не существует', 'Нужно использовать onclick'], options_en: ['The browser forbids it', 'An anonymous function has no reference to compare', 'removeEventListener does not exist', 'You must use onclick'], correctIndex: 1, explanation_ru: 'removeEventListener требует той же ссылки на функцию. Каждая анонимная функция — уникальный объект.', explanation_en: 'removeEventListener requires the exact same function reference. Each anonymous function is a unique object.' },
    { id: 'q5', text_ru: 'Какое свойство объекта события указывает на элемент, вызвавший событие?', text_en: 'Which event object property points to the element that triggered the event?', options_ru: ['e.source', 'e.element', 'e.target', 'e.currentTarget'], options_en: ['e.source', 'e.element', 'e.target', 'e.currentTarget'], correctIndex: 2, explanation_ru: 'e.target — элемент, на котором произошло событие. e.currentTarget — элемент с обработчиком.', explanation_en: 'e.target is the element where the event occurred. e.currentTarget is the element with the handler.' },
  ],
}
