import type { BilingualGlossaryTerm } from '@/types/glossary'

export const BILINGUAL_TERMS: BilingualGlossaryTerm[] = [

  // ─── HTML ─────────────────────────────────────────────────────────────────

  {
    id: 'h1',
    term_ru: 'Заголовок <h1>',
    term_en: 'Heading <h1>',
    category: 'HTML',
    topicSlug: 'intro-to-html',
    definition_ru: 'Тег для самого крупного и главного заголовка на странице.',
    definition_en: 'The tag for the biggest and most important heading on the page.',
    whyNeeded_ru: 'Заголовок помогает читателю сразу понять, о чём страница. <h1> — это как название главы в книге: оно одно и оно главное.',
    whyNeeded_en: 'A heading helps the reader instantly understand what the page is about. <h1> is like a chapter title in a book: there is one and it is the main one.',
    commonMistake_ru: 'Использовать несколько <h1> на одной странице. Главный заголовок должен быть только один, для остальных есть <h2>, <h3>.',
    commonMistake_en: 'Using several <h1> tags on one page. There should be only one main heading; use <h2>, <h3> for the rest.',
    example_ru: '<h1>Мой сайт</h1>',
    example_en: '<h1>My website</h1>',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '<h1>Привет!</h1>',
          comment_ru: 'Пишем заголовок первого уровня — самый большой',
          comment_en: 'We write a level-one heading — the biggest',
          preview: '<h1>Привет!</h1>',
        },
        {
          code: '<h1>Привет!</h1>\n<h2>Меньший заголовок</h2>',
          comment_ru: 'Добавляем <h2> — он меньше, чем <h1>',
          comment_en: 'We add <h2> — it is smaller than <h1>',
          preview: '<h1>Привет!</h1><h2>Меньший заголовок</h2>',
        },
      ],
    },
  },

  {
    id: 'html-p',
    term_ru: 'Абзац <p>',
    term_en: 'Paragraph <p>',
    category: 'HTML',
    topicSlug: 'intro-to-html',
    definition_ru: 'Тег <p> создаёт абзац — отдельный блок текста.',
    definition_en: 'The <p> tag creates a paragraph — a separate block of text.',
    whyNeeded_ru: 'Абзацы разбивают текст на логические части. Браузер автоматически добавляет отступы вокруг каждого <p>.',
    whyNeeded_en: 'Paragraphs break text into logical parts. The browser automatically adds spacing around each <p>.',
    commonMistake_ru: 'Не закрыть тег: <p>Текст без закрывающего </p>. Браузер простит, но всегда закрывай теги.',
    commonMistake_en: 'Not closing the tag: <p>Text without </p>. The browser forgives it, but always close your tags.',
    example_ru: '<p>Это мой первый абзац.</p>',
    example_en: '<p>This is my first paragraph.</p>',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '<p>Первый абзац</p>',
          comment_ru: 'Тег <p> создаёт блок текста',
          comment_en: 'The <p> tag creates a text block',
          preview: '<p>Первый абзац</p>',
        },
        {
          code: '<p>Первый абзац</p>\n<p>Второй абзац</p>',
          comment_ru: 'Каждый <p> начинается с новой строки автоматически',
          comment_en: 'Each <p> starts on a new line automatically',
          preview: '<p>Первый абзац</p><p>Второй абзац</p>',
        },
      ],
    },
  },

  {
    id: 'html-a',
    term_ru: 'Ссылка <a>',
    term_en: 'Link <a>',
    category: 'HTML',
    topicSlug: 'html-tags',
    definition_ru: 'Тег <a> создаёт ссылку — кликабельный текст, который ведёт на другую страницу.',
    definition_en: 'The <a> tag creates a link — clickable text that leads to another page.',
    whyNeeded_ru: 'Без ссылок интернет не был бы интернетом — они соединяют все страницы между собой. Атрибут href задаёт, куда ведёт ссылка.',
    whyNeeded_en: 'Without links the internet would not be the internet — they connect all pages together. The href attribute sets where the link goes.',
    commonMistake_ru: 'Забыть закрывающий тег </a>. Весь оставшийся текст страницы станет ссылкой!',
    commonMistake_en: 'Forgetting the closing </a> tag. All remaining text on the page becomes a link!',
    example_ru: '<a href="https://example.com">Нажми меня</a>',
    example_en: '<a href="https://example.com">Click me</a>',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '<a href="#">Перейти на сайт</a>',
          comment_ru: 'href — это адрес, куда ведёт ссылка',
          comment_en: 'href is the address the link goes to',
          preview: '<a href="#" style="color:#3B5BDB">Перейти на сайт</a>',
        },
        {
          code: '<a href="#">Перейти на сайт</a>\n<br>\n<a href="#">Ещё ссылка</a>',
          comment_ru: 'Можно добавить сколько угодно ссылок',
          comment_en: 'You can add as many links as you want',
          preview: '<a href="#" style="color:#3B5BDB">Перейти на сайт</a><br><a href="#" style="color:#7950F2">Ещё ссылка</a>',
        },
      ],
    },
  },

  {
    id: 'html-img',
    term_ru: 'Изображение <img>',
    term_en: 'Image <img>',
    category: 'HTML',
    topicSlug: 'html-tags',
    definition_ru: 'Тег <img> вставляет изображение на страницу. Это одиночный тег — закрывать его не нужно.',
    definition_en: 'The <img> tag inserts an image on the page. It is a self-closing tag — no closing tag needed.',
    whyNeeded_ru: 'Страницы без картинок скучны! <img> позволяет добавить любое изображение. Атрибут src задаёт путь к файлу, alt — подпись для тех, кто не видит картинку.',
    whyNeeded_en: 'Pages without images are boring! <img> lets you add any image. The src attribute sets the file path, alt sets a description for those who cannot see the image.',
    commonMistake_ru: 'Забыть атрибут alt. Он важен для доступности и для случаев, когда картинка не загружается.',
    commonMistake_en: 'Forgetting the alt attribute. It is important for accessibility and for cases when the image fails to load.',
    example_ru: '<img src="cat.png" alt="Кот">',
    example_en: '<img src="cat.png" alt="Cat">',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '<img src="https://placecats.com/80/60" alt="Кот">',
          comment_ru: 'src — путь к картинке, alt — описание',
          comment_en: 'src is the image path, alt is the description',
          preview: '<img src="https://placecats.com/80/60" alt="Кот" style="border-radius:8px">',
        },
        {
          code: '<img src="https://placecats.com/80/60" alt="Кот">\n<p>Посмотри на кота!</p>',
          comment_ru: 'Картинку можно совмещать с другими тегами',
          comment_en: 'You can combine images with other tags',
          preview: '<img src="https://placecats.com/80/60" alt="Кот" style="border-radius:8px"><p>Посмотри на кота!</p>',
        },
      ],
    },
  },

  {
    id: 'html-ul',
    term_ru: 'Список <ul>',
    term_en: 'List <ul>',
    category: 'HTML',
    topicSlug: 'html-tags',
    definition_ru: '<ul> создаёт маркированный список (с точками). Каждый пункт списка — тег <li>.',
    definition_en: '<ul> creates a bullet list. Each list item is wrapped in an <li> tag.',
    whyNeeded_ru: 'Списки помогают организовать информацию — например, список покупок, шаги рецепта или пункты меню.',
    whyNeeded_en: 'Lists help organise information — for example a shopping list, recipe steps, or navigation items.',
    commonMistake_ru: 'Забыть тег <li> и поместить текст прямо в <ul>. Текст без <li> не будет отображаться правильно.',
    commonMistake_en: 'Forgetting <li> tags and placing text directly in <ul>. Text without <li> will not display correctly.',
    example_ru: '<ul>\n  <li>HTML</li>\n  <li>CSS</li>\n</ul>',
    example_en: '<ul>\n  <li>HTML</li>\n  <li>CSS</li>\n</ul>',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '<ul>\n  <li>HTML</li>\n</ul>',
          comment_ru: 'ul — список, li — каждый пункт',
          comment_en: 'ul is the list, li is each item',
          preview: '<ul><li>HTML</li></ul>',
        },
        {
          code: '<ul>\n  <li>HTML</li>\n  <li>CSS</li>\n  <li>JavaScript</li>\n</ul>',
          comment_ru: 'Добавляем все три технологии — браузер ставит точки автоматически',
          comment_en: 'We add all three — the browser adds bullets automatically',
          preview: '<ul><li>HTML</li><li>CSS</li><li>JavaScript</li></ul>',
        },
      ],
    },
  },

  {
    id: 'html-ol',
    term_ru: 'Нумерованный список <ol>',
    term_en: 'Ordered list <ol>',
    category: 'HTML',
    topicSlug: 'html-tags',
    definition_ru: '<ol> создаёт нумерованный список. Браузер автоматически ставит 1, 2, 3… перед каждым <li>.',
    definition_en: '<ol> creates a numbered list. The browser automatically puts 1, 2, 3… before each <li>.',
    whyNeeded_ru: 'Используй <ol>, когда порядок важен: шаги инструкции, топ-10, рецепт.',
    whyNeeded_en: 'Use <ol> when order matters: instruction steps, a top-10 list, a recipe.',
    commonMistake_ru: 'Перепутать <ul> и <ol>. Помни: ol = ordered (упорядоченный), ul = unordered (неупорядоченный).',
    commonMistake_en: 'Confusing <ul> and <ol>. Remember: ol = ordered, ul = unordered.',
    example_ru: '<ol>\n  <li>Открой редактор</li>\n  <li>Напиши код</li>\n</ol>',
    example_en: '<ol>\n  <li>Open editor</li>\n  <li>Write code</li>\n</ol>',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '<ol>\n  <li>Шаг первый</li>\n  <li>Шаг второй</li>\n</ol>',
          comment_ru: 'ol нумерует пункты автоматически',
          comment_en: 'ol numbers the items automatically',
          preview: '<ol><li>Шаг первый</li><li>Шаг второй</li></ol>',
        },
        {
          code: '<ol>\n  <li>Открыть браузер</li>\n  <li>Написать HTML</li>\n  <li>Нажать F5</li>\n</ol>',
          comment_ru: 'Три шага — браузер считает сам',
          comment_en: 'Three steps — the browser counts automatically',
          preview: '<ol><li>Открыть браузер</li><li>Написать HTML</li><li>Нажать F5</li></ol>',
        },
      ],
    },
  },

  {
    id: 'html-div',
    term_ru: 'Контейнер <div>',
    term_en: 'Container <div>',
    category: 'HTML',
    topicSlug: 'html-tags',
    definition_ru: '<div> — это блочный контейнер без особого смысла. Используется для группировки элементов.',
    definition_en: '<div> is a block container with no special meaning. It is used to group elements together.',
    whyNeeded_ru: '<div> нужен, чтобы объединять несколько элементов в группу и применять к ним стили CSS как к одному блоку.',
    whyNeeded_en: '<div> is needed to group several elements together and apply CSS styles to them as one block.',
    commonMistake_ru: 'Использовать <div> везде вместо смысловых тегов. Там, где есть смысл — лучше <header>, <main>, <section>.',
    commonMistake_en: 'Using <div> everywhere instead of semantic tags. Where there is meaning — prefer <header>, <main>, <section>.',
    example_ru: '<div>\n  <h2>Карточка</h2>\n  <p>Текст</p>\n</div>',
    example_en: '<div>\n  <h2>Card</h2>\n  <p>Text</p>\n</div>',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '<div>\n  <h2>Карточка</h2>\n  <p>Описание</p>\n</div>',
          comment_ru: 'div объединяет элементы в один блок',
          comment_en: 'div groups elements into one block',
          preview: '<div style="border:2px solid #3B5BDB;padding:12px;border-radius:8px"><h2 style="margin:0 0 6px">Карточка</h2><p style="margin:0">Описание</p></div>',
        },
      ],
    },
  },

  {
    id: 'html-span',
    term_ru: 'Строчный тег <span>',
    term_en: 'Inline tag <span>',
    category: 'HTML',
    topicSlug: 'html-tags',
    definition_ru: '<span> — строчный контейнер без смысла. Используется для выделения части текста.',
    definition_en: '<span> is an inline container with no meaning. It is used to style part of a text.',
    whyNeeded_ru: 'В отличие от <div>, <span> не переносит на новую строку. Удобен для того, чтобы выделить слово или фразу внутри абзаца.',
    whyNeeded_en: 'Unlike <div>, <span> does not start a new line. Handy for highlighting a word or phrase inside a paragraph.',
    commonMistake_ru: 'Перепутать <span> и <div>: <div> всегда блочный (новая строка), <span> — строчный (остаётся в строке).',
    commonMistake_en: 'Confusing <span> and <div>: <div> is always a block (new line), <span> is inline (stays in the line).',
    example_ru: '<p>Вот <span>важное</span> слово.</p>',
    example_en: '<p>Here is an <span>important</span> word.</p>',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '<p>Обычный текст и\n<span style="color:red">красное слово</span>.</p>',
          comment_ru: 'span позволяет покрасить только часть текста',
          comment_en: 'span lets you colour only part of the text',
          preview: '<p>Обычный текст и <span style="color:red">красное слово</span>.</p>',
        },
      ],
    },
  },

  {
    id: 'html-head',
    term_ru: 'Голова страницы <head>',
    term_en: 'Page head <head>',
    category: 'HTML',
    topicSlug: 'intro-to-html',
    definition_ru: 'Тег <head> содержит невидимую информацию о странице: заголовок вкладки, кодировку, подключаемые файлы.',
    definition_en: 'The <head> tag contains invisible information about the page: the tab title, encoding, linked files.',
    whyNeeded_ru: 'Браузер читает <head> первым. Именно здесь ты говоришь: как называется страница, какие шрифты загрузить, какой CSS подключить.',
    whyNeeded_en: 'The browser reads <head> first. This is where you say: what the page is called, which fonts to load, which CSS to link.',
    commonMistake_ru: 'Поместить в <head> видимый контент. Всё, что пользователь видит, должно быть в <body>.',
    commonMistake_en: 'Placing visible content inside <head>. Everything the user sees must go in <body>.',
    example_ru: '<head>\n  <title>Мой сайт</title>\n</head>',
    example_en: '<head>\n  <title>My site</title>\n</head>',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '<!DOCTYPE html>\n<html>\n<head>\n  <title>Привет!</title>\n</head>\n<body>\n  <p>Страница</p>\n</body>\n</html>',
          comment_ru: 'head — невидимая часть, body — то, что видит пользователь',
          comment_en: 'head is the invisible part, body is what the user sees',
          preview: '<p>Страница</p>',
        },
      ],
    },
  },

  {
    id: 'html-attribute',
    term_ru: 'Атрибут',
    term_en: 'Attribute',
    category: 'HTML',
    topicSlug: 'intro-to-html',
    definition_ru: 'Дополнительная информация внутри тега. Атрибуты пишутся в открывающем теге: имя="значение".',
    definition_en: 'Extra information inside a tag. Attributes are written in the opening tag: name="value".',
    whyNeeded_ru: 'Атрибуты уточняют поведение тега. Например, <a> без href — просто текст, а с href — ссылка. <img> без src не покажет картинку.',
    whyNeeded_en: 'Attributes specify how a tag behaves. For example, <a> without href is just text, with href it becomes a link. <img> without src shows nothing.',
    commonMistake_ru: 'Пропустить кавычки: href=https://... вместо href="https://...". Всегда заключай значение в кавычки.',
    commonMistake_en: 'Missing quotes: href=https://... instead of href="https://...". Always wrap the value in quotes.',
    example_ru: '<a href="https://example.com">Ссылка</a>',
    example_en: '<a href="https://example.com">Link</a>',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '<a>Просто текст</a>',
          comment_ru: 'Без атрибута href — это не ссылка',
          comment_en: 'Without the href attribute this is not a link',
          preview: '<a>Просто текст</a>',
        },
        {
          code: '<a href="#">Настоящая ссылка</a>',
          comment_ru: 'Атрибут href превращает текст в кликабельную ссылку',
          comment_en: 'The href attribute turns text into a clickable link',
          preview: '<a href="#" style="color:#3B5BDB">Настоящая ссылка</a>',
        },
      ],
    },
  },

  {
    id: 'html-form',
    term_ru: 'Форма <form>',
    term_en: 'Form <form>',
    category: 'HTML',
    topicSlug: 'html-tags',
    definition_ru: '<form> создаёт форму для ввода данных пользователем: имя, пароль, поиск.',
    definition_en: '<form> creates a form for user input: name, password, search.',
    whyNeeded_ru: 'Без форм невозможно зарегистрироваться, войти в аккаунт или что-то поискать. Формы — главный способ общения пользователя с сайтом.',
    whyNeeded_en: 'Without forms you cannot sign up, log in, or search for anything. Forms are the main way users communicate with a site.',
    commonMistake_ru: 'Не добавить кнопку submit. Без кнопки пользователь не сможет отправить форму.',
    commonMistake_en: 'Not adding a submit button. Without a button the user cannot send the form.',
    example_ru: '<form>\n  <input type="text">\n  <button>Отправить</button>\n</form>',
    example_en: '<form>\n  <input type="text">\n  <button>Submit</button>\n</form>',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '<form>\n  <input type="text" placeholder="Твоё имя">\n  <button>Отправить</button>\n</form>',
          comment_ru: 'Форма с полем ввода и кнопкой',
          comment_en: 'A form with an input field and a button',
          preview: '<form style="display:flex;gap:8px"><input type="text" placeholder="Твоё имя" style="border:1px solid #ccc;padding:6px;border-radius:6px"><button style="background:#3B5BDB;color:white;border:none;padding:6px 12px;border-radius:6px;cursor:pointer">Отправить</button></form>',
        },
      ],
    },
  },

  {
    id: 'html-input',
    term_ru: 'Поле ввода <input>',
    term_en: 'Input field <input>',
    category: 'HTML',
    topicSlug: 'html-tags',
    definition_ru: '<input> создаёт поле для ввода данных. Тип поля задаётся атрибутом type.',
    definition_en: '<input> creates a field for entering data. The field type is set by the type attribute.',
    whyNeeded_ru: 'Разные type создают разные поля: text — обычный текст, password — пароль (звёздочки), checkbox — флажок, email — проверяет формат email.',
    whyNeeded_en: 'Different type values create different fields: text for plain text, password for passwords (dots), checkbox for a tick box, email validates email format.',
    commonMistake_ru: '<input> — одиночный тег! Не пиши </input>. Правильно: просто <input type="text">.',
    commonMistake_en: '<input> is a self-closing tag! Do not write </input>. Correct: just <input type="text">.',
    example_ru: '<input type="text" placeholder="Введи имя">',
    example_en: '<input type="text" placeholder="Enter name">',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '<input type="text" placeholder="Введи текст">',
          comment_ru: 'type="text" — обычное поле для текста',
          comment_en: 'type="text" — a plain text field',
          preview: '<input type="text" placeholder="Введи текст" style="border:1px solid #ccc;padding:8px;border-radius:6px;width:200px">',
        },
        {
          code: '<input type="password" placeholder="Пароль">',
          comment_ru: 'type="password" скрывает введённый текст точками',
          comment_en: 'type="password" hides the typed text with dots',
          preview: '<input type="text" placeholder="Введи текст" style="border:1px solid #ccc;padding:8px;border-radius:6px;width:200px;display:block;margin-bottom:8px"><input type="password" placeholder="Пароль" style="border:1px solid #ccc;padding:8px;border-radius:6px;width:200px">',
        },
      ],
    },
  },

  {
    id: 'html-title',
    term_ru: 'Заголовок вкладки <title>',
    term_en: 'Tab title <title>',
    category: 'HTML',
    topicSlug: 'intro-to-html',
    definition_ru: 'Тег <title> задаёт текст, который видно во вкладке браузера. Он находится внутри <head>.',
    definition_en: 'The <title> tag sets the text shown in the browser tab. It lives inside <head>.',
    whyNeeded_ru: 'Когда у тебя открыто 10 вкладок, ты ориентируешься по заголовкам. Хороший title объясняет, что на странице.',
    whyNeeded_en: 'When you have 10 tabs open, you navigate by their titles. A good title explains what is on the page.',
    commonMistake_ru: 'Написать <title> вне <head> или внутри <body>. Он работает только внутри <head>.',
    commonMistake_en: 'Writing <title> outside <head> or inside <body>. It only works inside <head>.',
    example_ru: '<title>Мой первый сайт</title>',
    example_en: '<title>My first website</title>',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '<head>\n  <title>Мой сайт</title>\n</head>',
          comment_ru: 'title — это название вкладки в браузере',
          comment_en: 'title is the name shown in the browser tab',
          preview: '<div style="background:#f1f3f5;padding:6px 12px;border-radius:6px;font-size:13px;color:#555;display:inline-flex;align-items:center;gap:8px"><span style="width:8px;height:8px;background:#ccc;border-radius:50%;display:inline-block"></span>Мой сайт</div>',
        },
      ],
    },
  },

  // ─── CSS ─────────────────────────────────────────────────────────────────

  {
    id: 'css-color',
    term_ru: 'Свойство color',
    term_en: 'The color property',
    category: 'CSS',
    topicSlug: 'css-styling',
    definition_ru: 'CSS-свойство, которое задаёт цвет текста элемента.',
    definition_en: 'A CSS property that sets the colour of an element\'s text.',
    whyNeeded_ru: 'Без CSS весь текст чёрный. Свойство color позволяет раскрасить заголовки, ссылки и любой текст так, как ты хочешь.',
    whyNeeded_en: 'Without CSS all text is black. The color property lets you paint headings, links and any text the way you want.',
    commonMistake_ru: 'Написать colour вместо color. В CSS всегда американское написание — color, без буквы "u".',
    commonMistake_en: 'Writing colour instead of color. CSS always uses the American spelling — color, without the "u".',
    example_ru: 'color: red;',
    example_en: 'color: red;',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '<p>Обычный текст</p>',
          comment_ru: 'Без стилей текст по умолчанию чёрный',
          comment_en: 'With no styles the text is black by default',
          preview: '<p>Обычный текст</p>',
        },
        {
          code: 'p { color: red; }',
          comment_ru: 'Добавляем CSS — красим текст абзаца в красный',
          comment_en: 'We add CSS — we paint the paragraph text red',
          preview: '<p style="color:red">Обычный текст</p>',
        },
      ],
    },
  },

  {
    id: 'css-background',
    term_ru: 'Фон background-color',
    term_en: 'Background background-color',
    category: 'CSS',
    topicSlug: 'css-styling',
    definition_ru: 'CSS-свойство, которое задаёт цвет фона элемента.',
    definition_en: 'A CSS property that sets the background colour of an element.',
    whyNeeded_ru: 'Фон помогает выделить важные блоки, сделать карточки, кнопки или цветные секции на странице.',
    whyNeeded_en: 'Background helps highlight important blocks, create cards, buttons, or coloured sections on a page.',
    commonMistake_ru: 'Написать background вместо background-color. Свойство background — это сокращение и делает больше, background-color — только цвет.',
    commonMistake_en: 'Writing background instead of background-color. background is a shorthand that does more; background-color sets only the colour.',
    example_ru: 'background-color: lightyellow;',
    example_en: 'background-color: lightyellow;',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '<div>Блок без фона</div>',
          comment_ru: 'По умолчанию фон прозрачный',
          comment_en: 'By default the background is transparent',
          preview: '<div style="padding:12px;border:1px solid #ddd;border-radius:6px">Блок без фона</div>',
        },
        {
          code: 'div { background-color: #e7f5ff; }',
          comment_ru: 'Добавляем голубой фон — блок сразу выделяется',
          comment_en: 'We add a blue background — the block stands out immediately',
          preview: '<div style="padding:12px;border-radius:6px;background-color:#e7f5ff">Блок без фона</div>',
        },
      ],
    },
  },

  {
    id: 'css-font-size',
    term_ru: 'Размер шрифта font-size',
    term_en: 'Font size font-size',
    category: 'CSS',
    topicSlug: 'css-styling',
    definition_ru: 'CSS-свойство, которое задаёт размер текста. Чаще всего измеряется в пикселях (px).',
    definition_en: 'A CSS property that sets the text size. Most often measured in pixels (px).',
    whyNeeded_ru: 'Размер шрифта управляет иерархией: крупный текст — главный, мелкий — второстепенный. Стандартный размер на странице — 16px.',
    whyNeeded_en: 'Font size controls hierarchy: large text is primary, small text is secondary. The standard size on a page is 16px.',
    commonMistake_ru: 'Забыть указать единицу измерения: font-size: 20 вместо font-size: 20px. Без px браузер проигнорирует значение.',
    commonMistake_en: 'Forgetting the unit: font-size: 20 instead of font-size: 20px. Without px the browser ignores the value.',
    example_ru: 'font-size: 24px;',
    example_en: 'font-size: 24px;',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '<p>Обычный текст</p>',
          comment_ru: 'По умолчанию браузер использует 16px',
          comment_en: 'By default the browser uses 16px',
          preview: '<p>Обычный текст</p>',
        },
        {
          code: 'p { font-size: 28px; }',
          comment_ru: '28px — текст стал крупнее',
          comment_en: '28px — the text is now bigger',
          preview: '<p style="font-size:28px">Обычный текст</p>',
        },
      ],
    },
  },

  {
    id: 'css-font-weight',
    term_ru: 'Жирность шрифта font-weight',
    term_en: 'Font weight font-weight',
    category: 'CSS',
    topicSlug: 'css-styling',
    definition_ru: 'CSS-свойство, которое задаёт жирность (толщину) текста: normal, bold или число от 100 до 900.',
    definition_en: 'A CSS property that sets the thickness of text: normal, bold, or a number from 100 to 900.',
    whyNeeded_ru: 'Жирный текст привлекает внимание. Используй bold для ключевых слов, заголовков и важных фраз.',
    whyNeeded_en: 'Bold text draws attention. Use bold for key words, headings, and important phrases.',
    commonMistake_ru: 'Написать font-weight: "bold" в кавычках. Значения CSS не заключаются в кавычки: font-weight: bold.',
    commonMistake_en: 'Writing font-weight: "bold" with quotes. CSS values do not go in quotes: font-weight: bold.',
    example_ru: 'font-weight: bold;',
    example_en: 'font-weight: bold;',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '<p>Обычный текст</p>',
          comment_ru: 'Стандартный вес — normal (400)',
          comment_en: 'Default weight is normal (400)',
          preview: '<p>Обычный текст</p>',
        },
        {
          code: 'p { font-weight: bold; }',
          comment_ru: 'bold делает текст жирным',
          comment_en: 'bold makes the text thick',
          preview: '<p style="font-weight:bold">Обычный текст</p>',
        },
      ],
    },
  },

  {
    id: 'css-text-align',
    term_ru: 'Выравнивание текста text-align',
    term_en: 'Text alignment text-align',
    category: 'CSS',
    topicSlug: 'css-styling',
    definition_ru: 'CSS-свойство для выравнивания текста по горизонтали: left, center, right или justify.',
    definition_en: 'A CSS property for horizontal text alignment: left, center, right, or justify.',
    whyNeeded_ru: 'Центрирование заголовков, выравнивание кнопок, подписей — text-align делает страницу опрятной.',
    whyNeeded_en: 'Centering headings, aligning buttons, captions — text-align makes a page tidy.',
    commonMistake_ru: 'text-align: middle — такого значения нет! Для центрирования используй text-align: center.',
    commonMistake_en: 'text-align: middle — that value does not exist! Use text-align: center for centring.',
    example_ru: 'text-align: center;',
    example_en: 'text-align: center;',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '<h1>Заголовок</h1>',
          comment_ru: 'По умолчанию текст выравнивается по левому краю',
          comment_en: 'By default text is left-aligned',
          preview: '<h1>Заголовок</h1>',
        },
        {
          code: 'h1 { text-align: center; }',
          comment_ru: 'center — заголовок по центру',
          comment_en: 'center — the heading moves to the middle',
          preview: '<h1 style="text-align:center">Заголовок</h1>',
        },
      ],
    },
  },

  {
    id: 'css-margin',
    term_ru: 'Внешний отступ margin',
    term_en: 'Outer spacing margin',
    category: 'CSS',
    topicSlug: 'css-layout',
    definition_ru: 'margin — пространство снаружи элемента, между ним и соседними элементами.',
    definition_en: 'margin is the space outside an element, between it and its neighbours.',
    whyNeeded_ru: 'Без margin все элементы слиплись бы в один блок. Margin создаёт воздух между блоками.',
    whyNeeded_en: 'Without margin all elements would clump together. Margin creates breathing room between blocks.',
    commonMistake_ru: 'Перепутать margin и padding. Margin — снаружи границы, padding — внутри.',
    commonMistake_en: 'Confusing margin and padding. Margin is outside the border, padding is inside.',
    example_ru: 'margin: 16px;',
    example_en: 'margin: 16px;',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '<div>Блок 1</div><div>Блок 2</div>',
          comment_ru: 'Без margin блоки вплотную друг к другу',
          comment_en: 'Without margin the blocks are right next to each other',
          preview: '<div style="background:#dbe4ff;padding:8px;border-radius:4px">Блок 1</div><div style="background:#d3f9d8;padding:8px;border-radius:4px">Блок 2</div>',
        },
        {
          code: 'div { margin-bottom: 16px; }',
          comment_ru: 'margin-bottom добавляет отступ снизу каждого блока',
          comment_en: 'margin-bottom adds space below each block',
          preview: '<div style="background:#dbe4ff;padding:8px;border-radius:4px;margin-bottom:16px">Блок 1</div><div style="background:#d3f9d8;padding:8px;border-radius:4px">Блок 2</div>',
        },
      ],
    },
  },

  {
    id: 'css-padding',
    term_ru: 'Внутренний отступ padding',
    term_en: 'Inner spacing padding',
    category: 'CSS',
    topicSlug: 'css-layout',
    definition_ru: 'padding — пространство внутри элемента, между содержимым и границей.',
    definition_en: 'padding is the space inside an element, between the content and the border.',
    whyNeeded_ru: 'Padding делает кнопки, карточки и блоки удобными — текст не прилипает к краям. Кнопка без padding выглядит некрасиво.',
    whyNeeded_en: 'Padding makes buttons, cards and blocks comfortable — text does not cling to the edges. A button without padding looks ugly.',
    commonMistake_ru: 'Перепутать padding и margin. Padding — это подушка внутри элемента, margin — расстояние до соседних элементов.',
    commonMistake_en: 'Confusing padding and margin. Padding is the cushion inside the element, margin is the distance to neighbouring elements.',
    example_ru: 'padding: 12px 24px;',
    example_en: 'padding: 12px 24px;',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '<button>Нажми</button>',
          comment_ru: 'Без padding кнопка совсем маленькая',
          comment_en: 'Without padding the button is tiny',
          preview: '<button style="background:#3B5BDB;color:white;border:none;border-radius:4px;cursor:pointer">Нажми</button>',
        },
        {
          code: 'button { padding: 10px 24px; }',
          comment_ru: 'padding даёт кнопке простор — так удобнее нажимать',
          comment_en: 'padding gives the button room — much easier to click',
          preview: '<button style="background:#3B5BDB;color:white;border:none;border-radius:6px;cursor:pointer;padding:10px 24px">Нажми</button>',
        },
      ],
    },
  },

  {
    id: 'css-border',
    term_ru: 'Граница border',
    term_en: 'Border',
    category: 'CSS',
    topicSlug: 'css-styling',
    definition_ru: 'border рисует рамку вокруг элемента. Задаётся тремя параметрами: толщина, стиль, цвет.',
    definition_en: 'border draws a frame around an element. It takes three values: thickness, style, colour.',
    whyNeeded_ru: 'Граница помогает визуально выделить карточки, таблицы, поля ввода. Красивые рамки делают интерфейс структурированным.',
    whyNeeded_en: 'A border visually separates cards, tables, input fields. Nice borders make the interface structured.',
    commonMistake_ru: 'Написать только border: 2px — без стиля (solid, dashed) граница не появится.',
    commonMistake_en: 'Writing just border: 2px — without a style (solid, dashed) the border will not appear.',
    example_ru: 'border: 2px solid #3B5BDB;',
    example_en: 'border: 2px solid #3B5BDB;',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '<div>Блок</div>',
          comment_ru: 'Без border у блока нет видимой границы',
          comment_en: 'Without border the block has no visible edge',
          preview: '<div style="padding:12px">Блок</div>',
        },
        {
          code: 'div { border: 2px solid #3B5BDB; }',
          comment_ru: 'solid — сплошная линия; можно и dashed (пунктир)',
          comment_en: 'solid is a solid line; you can also use dashed',
          preview: '<div style="padding:12px;border:2px solid #3B5BDB;border-radius:6px">Блок</div>',
        },
      ],
    },
  },

  {
    id: 'css-width',
    term_ru: 'Ширина width',
    term_en: 'Width',
    category: 'CSS',
    topicSlug: 'css-layout',
    definition_ru: 'width задаёт ширину элемента в пикселях (px) или процентах (%).',
    definition_en: 'width sets the width of an element in pixels (px) or percentages (%).',
    whyNeeded_ru: 'Управление шириной — основа вёрстки. width: 100% растягивает элемент на всю ширину контейнера, width: 50% — на половину.',
    whyNeeded_en: 'Controlling width is the foundation of layout. width: 100% stretches an element to the full container width, width: 50% to half.',
    commonMistake_ru: 'Задать width: 100px для текстового поля и удивиться, что оно маленькое. Попробуй width: 100%.',
    commonMistake_en: 'Setting width: 100px for an input and wondering why it is small. Try width: 100%.',
    example_ru: 'width: 300px;',
    example_en: 'width: 300px;',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '<div>Блок</div>',
          comment_ru: 'По умолчанию блочный элемент занимает всю ширину',
          comment_en: 'By default a block element takes the full width',
          preview: '<div style="background:#dbe4ff;padding:8px;border-radius:4px">Блок</div>',
        },
        {
          code: 'div { width: 50%; }',
          comment_ru: 'width: 50% — блок занимает половину ширины',
          comment_en: 'width: 50% — the block takes half the width',
          preview: '<div style="background:#dbe4ff;padding:8px;border-radius:4px;width:50%">Блок</div>',
        },
      ],
    },
  },

  {
    id: 'css-selector',
    term_ru: 'Селектор CSS',
    term_en: 'CSS Selector',
    category: 'CSS',
    topicSlug: 'css-styling',
    definition_ru: 'Селектор — это часть CSS-правила, которая говорит, к каким HTML-элементам применить стиль.',
    definition_en: 'A selector is the part of a CSS rule that says which HTML elements to apply the style to.',
    whyNeeded_ru: 'Без селектора браузер не знает, КОМУ назначить стиль. Селектор p означает "все абзацы", h1 — "все заголовки первого уровня".',
    whyNeeded_en: 'Without a selector the browser does not know WHO to apply the style to. The selector p means "all paragraphs", h1 means "all level-one headings".',
    commonMistake_ru: 'Написать css p { color: red } вместо просто p { color: red }. Слово "css" — не часть синтаксиса.',
    commonMistake_en: 'Writing css p { color: red } instead of just p { color: red }. The word "css" is not part of the syntax.',
    example_ru: 'h1 { color: blue; }',
    example_en: 'h1 { color: blue; }',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '<h1>Заголовок</h1>\n<p>Абзац</p>',
          comment_ru: 'Два элемента без стилей — оба чёрные',
          comment_en: 'Two elements with no styles — both are black',
          preview: '<h1>Заголовок</h1><p>Абзац</p>',
        },
        {
          code: 'p { color: #3B5BDB; }',
          comment_ru: 'Селектор p применяет стиль только к абзацам',
          comment_en: 'The p selector applies the style only to paragraphs',
          preview: '<h1>Заголовок</h1><p style="color:#3B5BDB">Абзац</p>',
        },
      ],
    },
  },

  {
    id: 'css-class-selector',
    term_ru: 'Класс .class',
    term_en: 'Class selector .class',
    category: 'CSS',
    topicSlug: 'css-styling',
    definition_ru: 'Класс в CSS — это имя, которое ты придумываешь сам. Оно пишется с точкой: .myClass. В HTML — через атрибут class.',
    definition_en: 'A CSS class is a name you create yourself. It is written with a dot: .myClass. In HTML it goes in the class attribute.',
    whyNeeded_ru: 'Классы позволяют применить стиль к ЛЮБОМУ элементу, а не только к тегу. Один класс — много элементов. Очень гибко!',
    whyNeeded_en: 'Classes let you apply a style to ANY element, not just a tag. One class — many elements. Very flexible!',
    commonMistake_ru: 'Забыть точку в CSS: написать card {} вместо .card {}. Без точки это будет селектор тега, а не класса.',
    commonMistake_en: 'Forgetting the dot in CSS: writing card {} instead of .card {}. Without the dot it selects a tag, not a class.',
    example_ru: '.highlight { background: yellow; }',
    example_en: '.highlight { background: yellow; }',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '<p class="highlight">Важный текст</p>\n<p>Обычный текст</p>',
          comment_ru: 'Атрибут class="highlight" назначает класс элементу',
          comment_en: 'The class="highlight" attribute assigns the class to the element',
          preview: '<p>Важный текст</p><p>Обычный текст</p>',
        },
        {
          code: '.highlight { background: #fff3bf; }',
          comment_ru: 'В CSS точка перед именем — это селектор класса',
          comment_en: 'In CSS the dot before the name is the class selector',
          preview: '<p style="background:#fff3bf;padding:4px 8px;border-radius:4px">Важный текст</p><p>Обычный текст</p>',
        },
      ],
    },
  },

  {
    id: 'css-display-flex',
    term_ru: 'Flexbox display: flex',
    term_en: 'Flexbox display: flex',
    category: 'CSS',
    topicSlug: 'css-layout',
    definition_ru: 'display: flex включает Flexbox — систему CSS для выравнивания элементов в строку или колонку.',
    definition_en: 'display: flex activates Flexbox — a CSS system for aligning elements in a row or column.',
    whyNeeded_ru: 'До Flexbox выровнять элементы по центру или в ряд было сложно. Теперь три строки кода решают задачу за секунды.',
    whyNeeded_en: 'Before Flexbox, centring or lining up elements was hard. Now three lines of CSS solve it in seconds.',
    commonMistake_ru: 'Применить display: flex к самим элементам вместо их родителя. Flex нужно поставить на КОНТЕЙНЕР, а не на элементы внутри.',
    commonMistake_en: 'Applying display: flex to the items instead of their parent. Flex must go on the CONTAINER, not the items inside.',
    example_ru: '.row { display: flex; gap: 16px; }',
    example_en: '.row { display: flex; gap: 16px; }',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '<div>\n  <div>A</div>\n  <div>B</div>\n  <div>C</div>\n</div>',
          comment_ru: 'Без flex три div стоят в столбик',
          comment_en: 'Without flex three divs stack vertically',
          preview: '<div><div style="background:#dbe4ff;padding:8px;margin-bottom:4px;border-radius:4px">A</div><div style="background:#d3f9d8;padding:8px;margin-bottom:4px;border-radius:4px">B</div><div style="background:#ffe8cc;padding:8px;border-radius:4px">C</div></div>',
        },
        {
          code: '.row { display: flex; gap: 12px; }',
          comment_ru: 'display: flex выстраивает их в строку!',
          comment_en: 'display: flex lines them up in a row!',
          preview: '<div style="display:flex;gap:12px"><div style="background:#dbe4ff;padding:8px;border-radius:4px">A</div><div style="background:#d3f9d8;padding:8px;border-radius:4px">B</div><div style="background:#ffe8cc;padding:8px;border-radius:4px">C</div></div>',
        },
      ],
    },
  },

  {
    id: 'css-hover',
    term_ru: 'Псевдокласс :hover',
    term_en: 'Pseudo-class :hover',
    category: 'CSS',
    topicSlug: 'css-styling',
    definition_ru: ':hover — состояние элемента, когда на него наводят мышь. Применяется для интерактивных эффектов.',
    definition_en: ':hover is the state of an element when the mouse is over it. Used for interactive effects.',
    whyNeeded_ru: 'Кнопки, ссылки и карточки должны реагировать на наведение. Это даёт пользователю обратную связь: "да, это кликабельно!"',
    whyNeeded_en: 'Buttons, links and cards should react to hover. It gives the user feedback: "yes, this is clickable!"',
    commonMistake_ru: 'Написать .btn:hover { color red; } — пропустить двоеточие после свойства. Правильно: color: red;',
    commonMistake_en: 'Writing .btn:hover { color red; } — missing the colon after the property. Correct: color: red;',
    example_ru: 'button:hover { background: #2946c4; }',
    example_en: 'button:hover { background: #2946c4; }',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '<button>Кнопка</button>',
          comment_ru: 'Обычная кнопка без реакции на наведение',
          comment_en: 'A plain button with no hover reaction',
          preview: '<button style="background:#3B5BDB;color:white;border:none;padding:8px 20px;border-radius:6px;cursor:pointer">Кнопка</button>',
        },
        {
          code: 'button:hover { background: #2946c4;\n  transform: scale(1.05); }',
          comment_ru: ':hover — стили применяются при наведении мыши',
          comment_en: ':hover — styles apply when the mouse is over the element',
          preview: '<button style="background:#3B5BDB;color:white;border:none;padding:8px 20px;border-radius:6px;cursor:pointer;transition:0.2s" onmouseover="this.style.background=\'#2946c4\';this.style.transform=\'scale(1.05)\'" onmouseout="this.style.background=\'#3B5BDB\';this.style.transform=\'scale(1)\'">Наведи мышь!</button>',
        },
      ],
    },
  },

  {
    id: 'css-border-radius',
    term_ru: 'Скруглённые углы border-radius',
    term_en: 'Rounded corners border-radius',
    category: 'CSS',
    topicSlug: 'css-styling',
    definition_ru: 'border-radius скругляет углы элемента. Значение 50% делает круг.',
    definition_en: 'border-radius rounds the corners of an element. A value of 50% makes a circle.',
    whyNeeded_ru: 'Острые углы выглядят грубо. border-radius делает кнопки, карточки и аватары мягкими и современными.',
    whyNeeded_en: 'Sharp corners look harsh. border-radius makes buttons, cards and avatars soft and modern.',
    commonMistake_ru: 'Написать border-radius без единицы: border-radius: 8 вместо border-radius: 8px.',
    commonMistake_en: 'Writing border-radius without a unit: border-radius: 8 instead of border-radius: 8px.',
    example_ru: 'border-radius: 12px;',
    example_en: 'border-radius: 12px;',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '<div>Блок</div>',
          comment_ru: 'По умолчанию углы у блока острые',
          comment_en: 'By default a block has sharp corners',
          preview: '<div style="background:#dbe4ff;padding:12px;width:80px">Блок</div>',
        },
        {
          code: 'div { border-radius: 12px; }',
          comment_ru: '12px — углы мягко скруглены',
          comment_en: '12px — the corners are softly rounded',
          preview: '<div style="background:#dbe4ff;padding:12px;border-radius:12px;width:80px">Блок</div>',
        },
        {
          code: 'div { border-radius: 50%; }',
          comment_ru: '50% превращает квадрат в круг',
          comment_en: '50% turns a square into a circle',
          preview: '<div style="background:#3B5BDB;color:white;padding:12px;border-radius:50%;width:60px;height:60px;display:flex;align-items:center;justify-content:center">Hi!</div>',
        },
      ],
    },
  },

  // ─── JavaScript ───────────────────────────────────────────────────────────

  {
    id: 'const',
    term_ru: 'const',
    term_en: 'const',
    category: 'JS',
    topicSlug: 'intro-to-js',
    definition_ru: 'Способ создать константу — значение с именем, которое нельзя изменить после создания.',
    definition_en: 'A way to create a constant — a named value that cannot be changed after it is created.',
    whyNeeded_ru: 'const защищает важные значения от случайного изменения. Если что-то не должно меняться (например, число пи), используй const — и программа сама не даст это сломать.',
    whyNeeded_en: 'const protects important values from accidental changes. If something should never change (like the number pi), use const — and the program itself will not let it break.',
    commonMistake_ru: 'Новички пытаются изменить const после создания и получают ошибку. Если значение нужно менять — используй let вместо const.',
    commonMistake_en: 'Beginners try to change a const after creating it and get an error. If a value needs to change, use let instead of const.',
    example_ru: 'const pi = 3.14',
    example_en: 'const pi = 3.14',
    demoMode: 'console',
    demo: {
      steps: [
        {
          code: 'const pi = 3.14',
          comment_ru: 'Создаём константу — значение, которое нельзя менять',
          comment_en: 'We create a constant — a value that cannot change',
          output: '',
        },
        {
          code: 'console.log(pi)',
          comment_ru: 'Используем её — просто выводим на экран',
          comment_en: 'We use it — simply print it to the screen',
          output: '3.14',
        },
        {
          code: 'pi = 5',
          comment_ru: 'Пробуем изменить... но const это запрещает!',
          comment_en: 'We try to change it... but const forbids that!',
          output: '⚠ TypeError: Assignment to constant variable',
          isError: true,
        },
      ],
    },
  },

  {
    id: 'let',
    term_ru: 'let',
    term_en: 'let',
    category: 'JS',
    topicSlug: 'intro-to-js',
    definition_ru: 'Способ создать переменную — именованное значение, которое можно менять в течение программы.',
    definition_en: 'A way to create a variable — a named value that can change during the program.',
    whyNeeded_ru: 'let нужен, когда значение должно меняться: счёт в игре, возраст игрока, текст на кнопке. Создал один раз — меняй сколько угодно.',
    whyNeeded_en: 'let is needed when a value should change: a game score, a player age, the text on a button. Create it once, then change it as much as you want.',
    commonMistake_ru: 'Забыть написать let при первом создании переменной. Имя переменной нужно объявить со словом let только один раз.',
    commonMistake_en: 'Forgetting to write let when first creating a variable. A variable name must be declared with let only once.',
    example_ru: 'let score = 0',
    example_en: 'let score = 0',
    demoMode: 'console',
    demo: {
      steps: [
        {
          code: 'let score = 0',
          comment_ru: 'Создаём переменную для счёта в игре',
          comment_en: 'We create a variable for the game score',
          output: '',
        },
        {
          code: 'console.log(score)',
          comment_ru: 'В начале счёт равен нулю',
          comment_en: 'At the start the score is zero',
          output: '0',
        },
        {
          code: 'score = score + 10',
          comment_ru: 'Игрок забил гол — увеличиваем счёт',
          comment_en: 'The player scored — we increase the score',
          output: '',
        },
        {
          code: 'console.log(score)',
          comment_ru: 'Теперь счёт изменился — let это разрешает!',
          comment_en: 'Now the score has changed — let allows that!',
          output: '10',
        },
      ],
    },
  },

  {
    id: 'js-string',
    term_ru: 'Строка (string)',
    term_en: 'String',
    category: 'JS',
    topicSlug: 'intro-to-js',
    definition_ru: 'Тип данных для текста. Строка всегда заключается в кавычки: одинарные, двойные или обратные.',
    definition_en: 'A data type for text. A string is always wrapped in quotes: single, double, or backtick.',
    whyNeeded_ru: 'Строки нужны для всего, что связано с текстом: имена, сообщения, адреса, подписи. Без строк нельзя написать даже "Привет!".',
    whyNeeded_en: 'Strings are needed for everything text-related: names, messages, addresses, labels. Without strings you cannot even write "Hello!".',
    commonMistake_ru: 'Забыть закрывающую кавычку: let name = "Алиса. JavaScript не поймёт, где заканчивается строка.',
    commonMistake_en: 'Forgetting the closing quote: let name = "Alice. JavaScript will not know where the string ends.',
    example_ru: 'let name = "Алиса"',
    example_en: 'let name = "Alice"',
    demoMode: 'console',
    demo: {
      steps: [
        {
          code: 'let name = "Алиса"',
          comment_ru: 'Создаём строку — текст в кавычках',
          comment_en: 'We create a string — text in quotes',
          output: '',
        },
        {
          code: 'console.log(name)',
          comment_ru: 'Выводим строку на экран',
          comment_en: 'We print the string to the screen',
          output: 'Алиса',
        },
        {
          code: 'console.log(name.length)',
          comment_ru: '.length — количество символов в строке',
          comment_en: '.length — the number of characters in the string',
          output: '5',
        },
      ],
    },
  },

  {
    id: 'js-number',
    term_ru: 'Число (number)',
    term_en: 'Number',
    category: 'JS',
    topicSlug: 'intro-to-js',
    definition_ru: 'Тип данных для чисел. В отличие от строк, числа не берутся в кавычки. Можно делать математику!',
    definition_en: 'A data type for numbers. Unlike strings, numbers do not go in quotes. You can do maths with them!',
    whyNeeded_ru: 'Числа нужны для подсчётов: очки в игре, возраст, цены, количество. С числами работают операторы +, -, *, /.',
    whyNeeded_en: 'Numbers are needed for counting: game points, age, prices, quantities. The operators +, -, *, / work with numbers.',
    commonMistake_ru: 'Написать число в кавычках: "5" + "3" = "53" (склеивает как строки!), а 5 + 3 = 8. Разница огромная!',
    commonMistake_en: 'Writing a number in quotes: "5" + "3" = "53" (joins as strings!), but 5 + 3 = 8. Huge difference!',
    example_ru: 'let age = 12',
    example_en: 'let age = 12',
    demoMode: 'console',
    demo: {
      steps: [
        {
          code: 'let age = 12',
          comment_ru: 'Число без кавычек — это тип number',
          comment_en: 'A number without quotes is the number type',
          output: '',
        },
        {
          code: 'console.log(age + 1)',
          comment_ru: 'Математика работает: 12 + 1 = 13',
          comment_en: 'Maths works: 12 + 1 = 13',
          output: '13',
        },
        {
          code: 'console.log("5" + 3)',
          comment_ru: '"5" — это строка! Строка + число = склейка',
          comment_en: '"5" is a string! String + number = concatenation',
          output: '53',
        },
      ],
    },
  },

  {
    id: 'js-boolean',
    term_ru: 'Булевый (boolean)',
    term_en: 'Boolean',
    category: 'JS',
    topicSlug: 'intro-to-js',
    definition_ru: 'Тип данных с двумя значениями: true (правда) и false (ложь).',
    definition_en: 'A data type with only two values: true (yes) and false (no).',
    whyNeeded_ru: 'Boolean — основа любой логики: включён/выключен, залогинен/нет, нажата/ненажата кнопка. Условия if используют boolean.',
    whyNeeded_en: 'Boolean is the foundation of all logic: on/off, logged in/out, button pressed/not. if conditions use boolean.',
    commonMistake_ru: 'Написать True или False с большой буквы. В JavaScript только строчные: true и false.',
    commonMistake_en: 'Writing True or False with a capital letter. In JavaScript only lowercase: true and false.',
    example_ru: 'let isOnline = true',
    example_en: 'let isOnline = true',
    demoMode: 'console',
    demo: {
      steps: [
        {
          code: 'let isOnline = true',
          comment_ru: 'true означает "да" или "включено"',
          comment_en: 'true means "yes" or "on"',
          output: '',
        },
        {
          code: 'console.log(isOnline)',
          comment_ru: 'Выводим значение boolean',
          comment_en: 'We print the boolean value',
          output: 'true',
        },
        {
          code: 'console.log(5 > 3)',
          comment_ru: 'Сравнения тоже возвращают boolean',
          comment_en: 'Comparisons also return boolean',
          output: 'true',
        },
        {
          code: 'console.log(2 > 10)',
          comment_ru: '2 больше 10? Нет — false!',
          comment_en: 'Is 2 greater than 10? No — false!',
          output: 'false',
        },
      ],
    },
  },

  {
    id: 'js-console-log',
    term_ru: 'console.log()',
    term_en: 'console.log()',
    category: 'JS',
    topicSlug: 'intro-to-js',
    definition_ru: 'Команда, которая выводит значение в консоль. Главный инструмент отладки.',
    definition_en: 'A command that prints a value to the console. The main debugging tool.',
    whyNeeded_ru: 'Программа не умеет объяснять, что происходит внутри. console.log — это как фонарик: ты светишь им на переменные и видишь их значения.',
    whyNeeded_en: 'A program cannot explain what is happening inside. console.log is like a torch: you shine it on variables and see their values.',
    commonMistake_ru: 'Написать Console.log или console.Log — с большой буквы. JavaScript чувствителен к регистру: только console.log.',
    commonMistake_en: 'Writing Console.log or console.Log with a capital. JavaScript is case-sensitive: only console.log.',
    example_ru: 'console.log("Привет!")',
    example_en: 'console.log("Hello!")',
    demoMode: 'console',
    demo: {
      steps: [
        {
          code: 'console.log("Привет, мир!")',
          comment_ru: 'Выводим строку — появится в консоли',
          comment_en: 'We print a string — it appears in the console',
          output: 'Привет, мир!',
        },
        {
          code: 'let x = 42\nconsole.log(x)',
          comment_ru: 'Можно выводить переменные — видим их значение',
          comment_en: 'We can print variables — we see their value',
          output: '42',
        },
        {
          code: 'console.log(2 + 2)',
          comment_ru: 'Можно сразу вычислять и выводить результат',
          comment_en: 'We can compute and print the result directly',
          output: '4',
        },
      ],
    },
  },

  {
    id: 'js-function',
    term_ru: 'Функция function',
    term_en: 'Function',
    category: 'JS',
    topicSlug: 'intro-to-js',
    definition_ru: 'Именованный блок кода, который можно вызвать многократно. Как рецепт: написал один раз — используй сколько хочешь.',
    definition_en: 'A named block of code that can be called many times. Like a recipe: write it once, use it as many times as you like.',
    whyNeeded_ru: 'Без функций пришлось бы копировать один и тот же код снова и снова. Функция — это способ не повторяться.',
    whyNeeded_en: 'Without functions you would have to copy the same code over and over. A function is a way to avoid repetition.',
    commonMistake_ru: 'Написать функцию, но забыть её вызвать. Функция не выполняется сама по себе — нужно написать greet().',
    commonMistake_en: 'Writing a function but forgetting to call it. A function does not run by itself — you need to write greet().',
    example_ru: 'function greet() {\n  console.log("Привет!")\n}',
    example_en: 'function greet() {\n  console.log("Hello!")\n}',
    demoMode: 'console',
    demo: {
      steps: [
        {
          code: 'function greet() {\n  console.log("Привет!")\n}',
          comment_ru: 'Объявляем функцию — пока код не выполняется',
          comment_en: 'We declare the function — the code does not run yet',
          output: '',
        },
        {
          code: 'greet()',
          comment_ru: 'Вызываем функцию — теперь она выполняется',
          comment_en: 'We call the function — now it runs',
          output: 'Привет!',
        },
        {
          code: 'greet()\ngreet()',
          comment_ru: 'Можно вызвать сколько угодно раз!',
          comment_en: 'You can call it as many times as you want!',
          output: 'Привет!\nПривет!',
        },
      ],
    },
  },

  {
    id: 'js-arrow',
    term_ru: 'Стрелочная функция =>',
    term_en: 'Arrow function =>',
    category: 'JS',
    topicSlug: 'intro-to-js',
    definition_ru: 'Короткая запись функции с помощью стрелки =>. Вместо function name() {} пишем const name = () => {}.',
    definition_en: 'A short way to write a function using an arrow =>. Instead of function name() {} write const name = () => {}.',
    whyNeeded_ru: 'Стрелочные функции компактнее и удобнее в современном коде. Большинство разработчиков предпочитают их для коротких функций.',
    whyNeeded_en: 'Arrow functions are more compact and convenient in modern code. Most developers prefer them for short functions.',
    commonMistake_ru: 'Пропустить круглые скобки: const fn = => {} вместо const fn = () => {}. Скобки нужны всегда.',
    commonMistake_en: 'Missing the parentheses: const fn = => {} instead of const fn = () => {}. Parentheses are always required.',
    example_ru: 'const greet = () => console.log("Привет!")',
    example_en: 'const greet = () => console.log("Hello!")',
    demoMode: 'console',
    demo: {
      steps: [
        {
          code: 'const double = (n) => n * 2',
          comment_ru: 'Стрелочная функция: принимает n, возвращает n * 2',
          comment_en: 'Arrow function: takes n, returns n * 2',
          output: '',
        },
        {
          code: 'console.log(double(5))',
          comment_ru: '5 × 2 = 10',
          comment_en: '5 × 2 = 10',
          output: '10',
        },
        {
          code: 'console.log(double(21))',
          comment_ru: 'Работает для любого числа',
          comment_en: 'Works for any number',
          output: '42',
        },
      ],
    },
  },

  {
    id: 'js-if',
    term_ru: 'Условие if / else',
    term_en: 'Condition if / else',
    category: 'JS',
    topicSlug: 'js-logic',
    definition_ru: 'if проверяет условие. Если оно true — выполняет блок кода. Иначе — блок в else.',
    definition_en: 'if checks a condition. If it is true — runs the code block. Otherwise — runs the else block.',
    whyNeeded_ru: 'Без if программа делала бы одно и то же всегда. if позволяет принимать решения: показать разное сообщение для разных ситуаций.',
    whyNeeded_en: 'Without if the program would do the same thing every time. if lets you make decisions: show a different message for different situations.',
    commonMistake_ru: 'Написать if age > 18 без скобок. Условие должно быть в скобках: if (age > 18).',
    commonMistake_en: 'Writing if age > 18 without brackets. The condition must be in brackets: if (age > 18).',
    example_ru: 'if (score > 50) {\n  console.log("Победа!")\n}',
    example_en: 'if (score > 50) {\n  console.log("Victory!")\n}',
    demoMode: 'console',
    demo: {
      steps: [
        {
          code: 'let age = 15',
          comment_ru: 'Задаём возраст',
          comment_en: 'We set the age',
          output: '',
        },
        {
          code: 'if (age >= 18) {\n  console.log("Взрослый")\n} else {\n  console.log("Ребёнок")\n}',
          comment_ru: '15 < 18 — условие false, выполняется else',
          comment_en: '15 < 18 — the condition is false, else runs',
          output: 'Ребёнок',
        },
      ],
    },
  },

  {
    id: 'js-for',
    term_ru: 'Цикл for',
    term_en: 'For loop',
    category: 'JS',
    topicSlug: 'js-logic',
    definition_ru: 'Цикл for повторяет блок кода определённое количество раз.',
    definition_en: 'A for loop repeats a block of code a specific number of times.',
    whyNeeded_ru: 'Без цикла тебе пришлось бы написать console.log 100 раз. Цикл делает это автоматически за несколько строк.',
    whyNeeded_en: 'Without a loop you would have to write console.log 100 times. A loop does it automatically in a few lines.',
    commonMistake_ru: 'Написать for (let i = 0; i <= 5; i++) — цикл выполнится 6 раз (0,1,2,3,4,5). Для 5 итераций нужно i < 5.',
    commonMistake_en: 'Writing for (let i = 0; i <= 5; i++) — the loop runs 6 times (0,1,2,3,4,5). For 5 iterations use i < 5.',
    example_ru: 'for (let i = 1; i <= 3; i++) {\n  console.log(i)\n}',
    example_en: 'for (let i = 1; i <= 3; i++) {\n  console.log(i)\n}',
    demoMode: 'console',
    demo: {
      steps: [
        {
          code: 'for (let i = 1; i <= 3; i++) {\n  console.log(i)\n}',
          comment_ru: 'i начинается с 1, повторяется пока i ≤ 3',
          comment_en: 'i starts at 1, repeats while i ≤ 3',
          output: '1\n2\n3',
        },
        {
          code: 'for (let i = 0; i < 5; i++) {\n  console.log("Привет №" + i)\n}',
          comment_ru: 'Цикл из 5 приветствий — пишем один раз!',
          comment_en: '5 greetings in a loop — written just once!',
          output: 'Привет №0\nПривет №1\nПривет №2\nПривет №3\nПривет №4',
        },
      ],
    },
  },

  {
    id: 'js-array',
    term_ru: 'Массив (array)',
    term_en: 'Array',
    category: 'JS',
    topicSlug: 'intro-to-js',
    definition_ru: 'Массив — список значений в квадратных скобках []. Элементы нумеруются с нуля.',
    definition_en: 'An array is a list of values in square brackets []. Elements are numbered starting from zero.',
    whyNeeded_ru: 'Когда нужно хранить много похожих данных — список покупок, имена игроков, набранные очки — массив хранит всё в одной переменной.',
    whyNeeded_en: 'When you need to store many similar items — a shopping list, player names, scores — an array holds everything in one variable.',
    commonMistake_ru: 'Думать, что первый элемент — это [1]. В массивах счёт начинается с нуля: первый элемент — [0].',
    commonMistake_en: 'Thinking the first element is [1]. Arrays start counting from zero: the first element is [0].',
    example_ru: 'const fruits = ["яблоко", "банан", "апельсин"]',
    example_en: 'const fruits = ["apple", "banana", "orange"]',
    demoMode: 'console',
    demo: {
      steps: [
        {
          code: 'const fruits = ["яблоко", "банан", "апельсин"]',
          comment_ru: 'Создаём массив из трёх фруктов',
          comment_en: 'We create an array of three fruits',
          output: '',
        },
        {
          code: 'console.log(fruits[0])',
          comment_ru: 'Первый элемент — индекс 0, не 1!',
          comment_en: 'First element — index 0, not 1!',
          output: 'яблоко',
        },
        {
          code: 'console.log(fruits.length)',
          comment_ru: '.length — количество элементов в массиве',
          comment_en: '.length — the number of elements in the array',
          output: '3',
        },
      ],
    },
  },

  {
    id: 'js-object',
    term_ru: 'Объект (object)',
    term_en: 'Object',
    category: 'JS',
    topicSlug: 'intro-to-js',
    definition_ru: 'Объект — набор пар ключ: значение в фигурных скобках {}. Как карточка с характеристиками.',
    definition_en: 'An object is a collection of key: value pairs in curly braces {}. Like a profile card with characteristics.',
    whyNeeded_ru: 'Объект группирует связанные данные. Персонаж игры — не три отдельных переменных, а один объект с именем, жизнями и оружием.',
    whyNeeded_en: 'An object groups related data. A game character is not three separate variables, but one object with a name, lives, and weapon.',
    commonMistake_ru: 'Обратиться к свойству через запятую: hero,name вместо hero.name. Используй точку или квадратные скобки.',
    commonMistake_en: 'Accessing a property with a comma: hero,name instead of hero.name. Use a dot or square brackets.',
    example_ru: 'const hero = { name: "Алиса", level: 5 }',
    example_en: 'const hero = { name: "Alice", level: 5 }',
    demoMode: 'console',
    demo: {
      steps: [
        {
          code: 'const hero = {\n  name: "Алиса",\n  level: 5,\n  alive: true\n}',
          comment_ru: 'Объект с тремя свойствами — как карточка персонажа',
          comment_en: 'An object with three properties — like a character card',
          output: '',
        },
        {
          code: 'console.log(hero.name)',
          comment_ru: 'Доступ к свойству через точку',
          comment_en: 'Accessing a property with a dot',
          output: 'Алиса',
        },
        {
          code: 'console.log(hero.level)',
          comment_ru: 'Другое свойство',
          comment_en: 'Another property',
          output: '5',
        },
      ],
    },
  },

  {
    id: 'js-comparison',
    term_ru: 'Операторы сравнения',
    term_en: 'Comparison operators',
    category: 'JS',
    topicSlug: 'js-logic',
    definition_ru: 'Операторы для сравнения двух значений: ===, !==, >, <, >=, <=. Результат — всегда boolean.',
    definition_en: 'Operators for comparing two values: ===, !==, >, <, >=, <=. The result is always boolean.',
    whyNeeded_ru: 'Сравнения нужны для условий. Без сравнения нельзя проверить: "введён ли правильный пароль?" или "набрал ли игрок 100 очков?".',
    whyNeeded_en: 'Comparisons are needed for conditions. Without comparison you cannot check: "was the correct password entered?" or "did the player score 100 points?".',
    commonMistake_ru: 'Написать = вместо === для сравнения. Одно равно (=) — это присвоение, три равно (===) — это сравнение.',
    commonMistake_en: 'Writing = instead of === for comparison. One equals (=) is assignment, three equals (===) is comparison.',
    example_ru: 'console.log(5 === 5)',
    example_en: 'console.log(5 === 5)',
    demoMode: 'console',
    demo: {
      steps: [
        {
          code: 'console.log(5 === 5)',
          comment_ru: '=== строгое равенство — и тип, и значение должны совпасть',
          comment_en: '=== is strict equality — both type and value must match',
          output: 'true',
        },
        {
          code: 'console.log(5 > 3)',
          comment_ru: '5 больше 3? Да!',
          comment_en: 'Is 5 greater than 3? Yes!',
          output: 'true',
        },
        {
          code: 'console.log("5" === 5)',
          comment_ru: 'Строка "5" и число 5 — разные типы!',
          comment_en: 'The string "5" and the number 5 are different types!',
          output: 'false',
        },
      ],
    },
  },

  {
    id: 'js-logical',
    term_ru: 'Логические операторы',
    term_en: 'Logical operators',
    category: 'JS',
    topicSlug: 'js-logic',
    definition_ru: '&& (и), || (или), ! (не) — операторы для объединения нескольких условий.',
    definition_en: '&& (and), || (or), ! (not) — operators for combining multiple conditions.',
    whyNeeded_ru: 'Часто нужно проверить сразу несколько вещей: "возраст больше 10 И меньше 18". Без && пришлось бы писать if внутри if.',
    whyNeeded_en: 'Often you need to check several things at once: "age is over 10 AND under 18". Without && you would have to nest if inside if.',
    commonMistake_ru: 'Написать & вместо &&. Один амперсанд — это побитовая операция, два — это логическое "И".',
    commonMistake_en: 'Writing & instead of &&. One ampersand is a bitwise operation, two is logical "and".',
    example_ru: 'if (age > 10 && age < 18) { }',
    example_en: 'if (age > 10 && age < 18) { }',
    demoMode: 'console',
    demo: {
      steps: [
        {
          code: 'let age = 14\nconsole.log(age > 10 && age < 18)',
          comment_ru: '&& — оба условия должны быть true',
          comment_en: '&& — both conditions must be true',
          output: 'true',
        },
        {
          code: 'console.log(age < 5 || age > 12)',
          comment_ru: '|| — хотя бы одно условие должно быть true',
          comment_en: '|| — at least one condition must be true',
          output: 'true',
        },
        {
          code: 'console.log(!true)',
          comment_ru: '! инвертирует: не-true = false',
          comment_en: '! flips it: not-true = false',
          output: 'false',
        },
      ],
    },
  },

  {
    id: 'js-return',
    term_ru: 'return',
    term_en: 'return',
    category: 'JS',
    topicSlug: 'intro-to-js',
    definition_ru: 'return завершает функцию и возвращает значение обратно туда, откуда функция была вызвана.',
    definition_en: 'return exits a function and sends a value back to wherever the function was called from.',
    whyNeeded_ru: 'Без return функция может что-то делать, но не может ДАТЬ результат. return превращает функцию в машину, которая принимает входные данные и отдаёт результат.',
    whyNeeded_en: 'Without return a function can do things but cannot GIVE a result. return turns a function into a machine that takes input and produces output.',
    commonMistake_ru: 'Поставить код после return — он никогда не выполнится. return всегда завершает функцию немедленно.',
    commonMistake_en: 'Placing code after return — it will never run. return always exits the function immediately.',
    example_ru: 'function add(a, b) {\n  return a + b\n}',
    example_en: 'function add(a, b) {\n  return a + b\n}',
    demoMode: 'console',
    demo: {
      steps: [
        {
          code: 'function add(a, b) {\n  return a + b\n}',
          comment_ru: 'Функция принимает два числа и возвращает их сумму',
          comment_en: 'The function takes two numbers and returns their sum',
          output: '',
        },
        {
          code: 'let result = add(3, 7)\nconsole.log(result)',
          comment_ru: 'Результат сохраняется в переменную',
          comment_en: 'The result is saved to a variable',
          output: '10',
        },
        {
          code: 'console.log(add(100, 200))',
          comment_ru: 'Можно использовать прямо в console.log',
          comment_en: 'Can be used directly in console.log',
          output: '300',
        },
      ],
    },
  },

  {
    id: 'js-template',
    term_ru: 'Шаблонная строка',
    term_en: 'Template literal',
    category: 'JS',
    topicSlug: 'intro-to-js',
    definition_ru: 'Шаблонная строка пишется в обратных кавычках `. Позволяет вставлять переменные через ${переменная}.',
    definition_en: 'A template literal is written in backticks `. It lets you insert variables using ${variable}.',
    whyNeeded_ru: 'Вместо "Привет, " + name + "!" можно написать `Привет, ${name}!` — намного чище и понятнее.',
    whyNeeded_en: 'Instead of "Hello, " + name + "!" you can write `Hello, ${name}!` — much cleaner and clearer.',
    commonMistake_ru: 'Использовать обычные кавычки вместо обратных: "Привет ${name}" — переменная не подставится, будет выведено буквально.',
    commonMistake_en: 'Using regular quotes instead of backticks: "Hello ${name}" — the variable will not be inserted, it will print literally.',
    example_ru: '`Привет, ${name}!`',
    example_en: '`Hello, ${name}!`',
    demoMode: 'console',
    demo: {
      steps: [
        {
          code: 'let name = "Алиса"\nlet age = 12',
          comment_ru: 'Задаём имя и возраст',
          comment_en: 'We set the name and age',
          output: '',
        },
        {
          code: 'console.log(`Привет, ${name}!`)',
          comment_ru: 'Переменная вставляется прямо в строку через ${}',
          comment_en: 'The variable is inserted into the string via ${}',
          output: 'Привет, Алиса!',
        },
        {
          code: 'console.log(`${name} — ${age} лет`)',
          comment_ru: 'Можно вставить сколько угодно переменных',
          comment_en: 'You can insert as many variables as you want',
          output: 'Алиса — 12 лет',
        },
      ],
    },
  },

  {
    id: 'js-typeof',
    term_ru: 'Оператор typeof',
    term_en: 'Operator typeof',
    category: 'JS',
    topicSlug: 'intro-to-js',
    definition_ru: 'typeof возвращает строку с типом значения: "number", "string", "boolean", "object", "function".',
    definition_en: 'typeof returns a string with the type of a value: "number", "string", "boolean", "object", "function".',
    whyNeeded_ru: 'Когда не знаешь, что лежит в переменной — typeof покажет. Очень полезно при отладке.',
    whyNeeded_en: 'When you do not know what is in a variable — typeof will show you. Very useful for debugging.',
    commonMistake_ru: 'Ожидать typeof [] === "array". Массивы в JavaScript — это объекты, поэтому typeof [] возвращает "object".',
    commonMistake_en: 'Expecting typeof [] === "array". Arrays in JavaScript are objects, so typeof [] returns "object".',
    example_ru: 'typeof 42',
    example_en: 'typeof 42',
    demoMode: 'console',
    demo: {
      steps: [
        {
          code: 'console.log(typeof 42)',
          comment_ru: '42 — это число',
          comment_en: '42 is a number',
          output: 'number',
        },
        {
          code: 'console.log(typeof "Привет")',
          comment_ru: '"Привет" — это строка',
          comment_en: '"Привет" is a string',
          output: 'string',
        },
        {
          code: 'console.log(typeof true)',
          comment_ru: 'true — это boolean',
          comment_en: 'true is a boolean',
          output: 'boolean',
        },
      ],
    },
  },

  {
    id: 'js-array-push',
    term_ru: 'Метод .push()',
    term_en: 'Method .push()',
    category: 'JS',
    topicSlug: 'intro-to-js',
    definition_ru: '.push() добавляет элемент в конец массива.',
    definition_en: '.push() adds an element to the end of an array.',
    whyNeeded_ru: 'Массивы часто заполняются по ходу программы: новые сообщения, игровые объекты, результаты. .push() — самый простой способ это сделать.',
    whyNeeded_en: 'Arrays are often filled during the program: new messages, game objects, results. .push() is the simplest way to do this.',
    commonMistake_ru: 'Присвоить результат push переменной: let a = arr.push(5). push возвращает новую длину, а не массив!',
    commonMistake_en: 'Assigning the push result to a variable: let a = arr.push(5). push returns the new length, not the array!',
    example_ru: 'arr.push("новый элемент")',
    example_en: 'arr.push("new item")',
    demoMode: 'console',
    demo: {
      steps: [
        {
          code: 'let colors = ["красный", "синий"]',
          comment_ru: 'Начинаем с массива из двух цветов',
          comment_en: 'We start with an array of two colours',
          output: '',
        },
        {
          code: 'colors.push("зелёный")\nconsole.log(colors)',
          comment_ru: 'push добавляет в конец',
          comment_en: 'push adds to the end',
          output: '["красный", "синий", "зелёный"]',
        },
        {
          code: 'console.log(colors.length)',
          comment_ru: 'Теперь три элемента',
          comment_en: 'Now three elements',
          output: '3',
        },
      ],
    },
  },

  {
    id: 'js-math-ops',
    term_ru: 'Математические операции',
    term_en: 'Math operations',
    category: 'JS',
    topicSlug: 'intro-to-js',
    definition_ru: 'JavaScript поддерживает +, -, *, / и ещё ** (степень) и % (остаток от деления).',
    definition_en: 'JavaScript supports +, -, *, / and also ** (exponent) and % (remainder).',
    whyNeeded_ru: 'Математика нужна везде: считать очки, цены, пиксели, время. % (остаток) полезен для определения чётных/нечётных чисел.',
    whyNeeded_en: 'Maths is needed everywhere: counting points, prices, pixels, time. % (remainder) is useful for finding even/odd numbers.',
    commonMistake_ru: 'Написать 2^3 для возведения в степень. В JavaScript нужен **: 2 ** 3 = 8.',
    commonMistake_en: 'Writing 2^3 for exponentiation. In JavaScript use **: 2 ** 3 = 8.',
    example_ru: 'console.log(10 % 3)',
    example_en: 'console.log(10 % 3)',
    demoMode: 'console',
    demo: {
      steps: [
        {
          code: 'console.log(10 + 3)',
          comment_ru: 'Сложение',
          comment_en: 'Addition',
          output: '13',
        },
        {
          code: 'console.log(10 % 3)',
          comment_ru: '% — остаток от деления: 10 / 3 = 3 остаток 1',
          comment_en: '% — remainder: 10 / 3 = 3 remainder 1',
          output: '1',
        },
        {
          code: 'console.log(2 ** 8)',
          comment_ru: '** — степень: 2 в степени 8',
          comment_en: '** — power: 2 to the power of 8',
          output: '256',
        },
      ],
    },
  },

  // ─── Новые CSS-термины ─────────────────────────────────────────────────────

  {
    id: 'css-grid',
    term_ru: 'CSS Grid',
    term_en: 'CSS Grid',
    category: 'CSS',
    topicSlug: 'css-grid',
    definition_ru: 'Двумерная система раскладки: строки и колонки одновременно. Включается через display: grid.',
    definition_en: 'A two-dimensional layout system: rows and columns at the same time. Enabled with display: grid.',
    whyNeeded_ru: 'Flexbox управляет одной осью (ряд или колонка). Grid — двумя одновременно. Идеален для страничных раскладок, фотогалерей, дашбордов.',
    whyNeeded_en: 'Flexbox controls one axis at a time. Grid controls both. Perfect for page layouts, galleries, dashboards.',
    commonMistake_ru: 'Забыть задать grid-template-columns. Без него Grid ведёт себя как обычный блок.',
    commonMistake_en: 'Forgetting to set grid-template-columns. Without it Grid behaves like a regular block.',
    example_ru: 'display: grid; grid-template-columns: 1fr 1fr 1fr',
    example_en: 'display: grid; grid-template-columns: 1fr 1fr 1fr',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '.container { display: grid; }',
          comment_ru: 'Включаем Grid — пока всё в одну колонку',
          comment_en: 'Enable Grid — still one column for now',
          preview: '<div style="display:grid;gap:8px;font-family:sans-serif"><div style="background:#3B5BDB;color:white;padding:12px;border-radius:8px">1</div><div style="background:#3B5BDB;color:white;padding:12px;border-radius:8px">2</div><div style="background:#3B5BDB;color:white;padding:12px;border-radius:8px">3</div></div>',
        },
        {
          code: '.container { display: grid;\n  grid-template-columns: 1fr 1fr 1fr; }',
          comment_ru: '1fr 1fr 1fr — три равные колонки',
          comment_en: '1fr 1fr 1fr — three equal columns',
          preview: '<div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;font-family:sans-serif"><div style="background:#3B5BDB;color:white;padding:12px;border-radius:8px;text-align:center">1</div><div style="background:#3B5BDB;color:white;padding:12px;border-radius:8px;text-align:center">2</div><div style="background:#3B5BDB;color:white;padding:12px;border-radius:8px;text-align:center">3</div></div>',
        },
        {
          code: '.container { display: grid;\n  grid-template-columns: 2fr 1fr;\n  gap: 12px; }',
          comment_ru: '2fr 1fr — левая колонка в два раза шире правой',
          comment_en: '2fr 1fr — left column is twice as wide as the right',
          preview: '<div style="display:grid;grid-template-columns:2fr 1fr;gap:12px;font-family:sans-serif"><div style="background:#3B5BDB;color:white;padding:16px;border-radius:8px">Широкий блок (2fr)</div><div style="background:#7950F2;color:white;padding:16px;border-radius:8px">Узкий (1fr)</div></div>',
        },
      ],
    },
  },

  {
    id: 'css-position',
    term_ru: 'position',
    term_en: 'position',
    category: 'CSS',
    topicSlug: 'css-positioning',
    definition_ru: 'CSS-свойство, определяющее способ позиционирования элемента: static, relative, absolute, fixed, sticky.',
    definition_en: 'CSS property defining how an element is positioned: static, relative, absolute, fixed, sticky.',
    whyNeeded_ru: 'Обычный поток документа ограничен. position позволяет поместить элемент в точное место: всплывающее меню, закреплённую шапку, tooltip.',
    whyNeeded_en: 'Normal document flow is limited. position lets you place an element exactly: dropdown menu, sticky header, tooltip.',
    commonMistake_ru: 'Использовать absolute без relative на родителе. Тогда элемент позиционируется относительно <body>, а не контейнера.',
    commonMistake_en: 'Using absolute without relative on the parent. Then the element is positioned relative to <body>, not the container.',
    example_ru: 'position: absolute; top: 0; right: 0',
    example_en: 'position: absolute; top: 0; right: 0',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '.badge { position: static; }',
          comment_ru: 'static — обычный поток, top/left не работают',
          comment_en: 'static — normal flow, top/left have no effect',
          preview: '<div style="position:relative;width:120px;height:80px;background:#e9ecef;border-radius:8px;font-family:sans-serif;display:flex;align-items:center;justify-content:center;font-size:14px">Карточка<div style="position:static;background:#e03131;color:white;font-size:11px;padding:2px 6px;border-radius:10px">New</div></div>',
        },
        {
          code: '.parent { position: relative; }\n.badge { position: absolute;\n  top: -8px; right: -8px; }',
          comment_ru: 'absolute — позиция от ближайшего relative-родителя',
          comment_en: 'absolute — position from the nearest relative parent',
          preview: '<div style="position:relative;width:120px;height:80px;background:#e9ecef;border-radius:8px;font-family:sans-serif;display:flex;align-items:center;justify-content:center;font-size:14px;margin:12px">Карточка<div style="position:absolute;top:-8px;right:-8px;background:#e03131;color:white;font-size:11px;padding:2px 8px;border-radius:10px">New</div></div>',
        },
      ],
    },
  },

  {
    id: 'css-transform',
    term_ru: 'transform',
    term_en: 'transform',
    category: 'CSS',
    topicSlug: 'css-pseudo-animations',
    definition_ru: 'CSS-свойство для геометрических преобразований без изменения потока документа: rotate, scale, translate, skew.',
    definition_en: 'CSS property for geometric transformations without affecting document flow: rotate, scale, translate, skew.',
    whyNeeded_ru: 'transform работает через GPU и не вызывает перерасчёт layout — самый производительный способ анимировать элементы.',
    whyNeeded_en: 'transform uses the GPU and does not trigger layout recalculation — the most performant way to animate elements.',
    commonMistake_ru: 'Путать translate (сдвиг) с margin. margin меняет поток документа, translate — нет.',
    commonMistake_en: 'Confusing translate (shift) with margin. margin changes document flow, translate does not.',
    example_ru: 'transform: rotate(45deg) scale(1.2)',
    example_en: 'transform: rotate(45deg) scale(1.2)',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: '.box { transform: rotate(45deg); }',
          comment_ru: 'rotate — поворот на 45 градусов',
          comment_en: 'rotate — 45-degree rotation',
          preview: '<div style="display:flex;justify-content:center;padding:20px"><div style="width:60px;height:60px;background:#3B5BDB;border-radius:8px;transform:rotate(45deg)"></div></div>',
        },
        {
          code: '.box { transform: scale(1.5); }',
          comment_ru: 'scale — увеличение в 1.5 раза',
          comment_en: 'scale — 1.5× enlargement',
          preview: '<div style="display:flex;justify-content:center;padding:20px"><div style="width:60px;height:60px;background:#2f9e44;border-radius:8px;transform:scale(1.5)"></div></div>',
        },
        {
          code: '.box { transform: translateX(40px); }',
          comment_ru: 'translateX — сдвиг вправо на 40px',
          comment_en: 'translateX — shift right by 40px',
          preview: '<div style="display:flex;justify-content:center;padding:20px"><div style="width:60px;height:60px;background:#e03131;border-radius:8px;transform:translateX(40px)"></div></div>',
        },
      ],
    },
  },

  {
    id: 'css-rem',
    term_ru: 'rem / em',
    term_en: 'rem / em',
    category: 'CSS',
    topicSlug: 'css-sizing-units',
    definition_ru: 'rem — размер относительно корневого шрифта (html, обычно 16px). em — относительно шрифта родителя. Оба адаптируются при изменении базового размера.',
    definition_en: 'rem — size relative to the root font (html, usually 16px). em — relative to the parent\'s font. Both adapt when the base size changes.',
    whyNeeded_ru: 'px — абсолютный и не масштабируется при изменении настроек браузера. rem/em позволяют делать доступные интерфейсы.',
    whyNeeded_en: 'px is absolute and does not scale with browser font settings. rem/em enable accessible interfaces.',
    commonMistake_ru: 'Использовать em вложенно — размер умножается на каждом уровне. Обычно предпочтительнее rem.',
    commonMistake_en: 'Using em in nested elements — the size multiplies at each level. Usually rem is preferable.',
    example_ru: 'font-size: 1.5rem  /* = 24px при базовом 16px */',
    example_en: 'font-size: 1.5rem  /* = 24px at base 16px */',
    demoMode: 'preview',
    demo: {
      steps: [
        {
          code: 'html { font-size: 16px; }\np { font-size: 1rem; }',
          comment_ru: '1rem = 16px (корневой размер)',
          comment_en: '1rem = 16px (root size)',
          preview: '<p style="font-size:1rem;font-family:sans-serif;margin:0">Текст 1rem = 16px</p>',
        },
        {
          code: 'p { font-size: 1.5rem; }',
          comment_ru: '1.5rem = 24px',
          comment_en: '1.5rem = 24px',
          preview: '<p style="font-size:1.5rem;font-family:sans-serif;margin:0">Текст 1.5rem = 24px</p>',
        },
      ],
    },
  },

  // ─── Новые JS-термины ──────────────────────────────────────────────────────

  {
    id: 'js-map-filter',
    term_ru: 'map() и filter()',
    term_en: 'map() and filter()',
    category: 'JS',
    topicSlug: 'js-arrays',
    definition_ru: 'map() создаёт новый массив, применяя функцию к каждому элементу. filter() создаёт новый массив из элементов, прошедших проверку.',
    definition_en: 'map() creates a new array by applying a function to each element. filter() creates a new array of elements that pass a test.',
    whyNeeded_ru: 'Это два самых часто используемых метода массива в реальном коде. map — трансформация, filter — отбор.',
    whyNeeded_en: 'These are the two most-used array methods in real code. map — transformation, filter — selection.',
    commonMistake_ru: 'Забыть вернуть значение из функции внутри map. Тогда все элементы станут undefined.',
    commonMistake_en: 'Forgetting to return a value from the function inside map. Then all elements become undefined.',
    example_ru: '[1, 2, 3].map(x => x * 2)  // [2, 4, 6]',
    example_en: '[1, 2, 3].map(x => x * 2)  // [2, 4, 6]',
    demoMode: 'console',
    demo: {
      steps: [
        {
          code: 'const nums = [1, 2, 3, 4, 5]',
          comment_ru: 'Исходный массив',
          comment_en: 'Original array',
          output: '',
        },
        {
          code: 'console.log(nums.map(x => x * 2))',
          comment_ru: 'map: умножаем каждый элемент на 2',
          comment_en: 'map: multiply each element by 2',
          output: '[2, 4, 6, 8, 10]',
        },
        {
          code: 'console.log(nums.filter(x => x > 2))',
          comment_ru: 'filter: оставляем только элементы > 2',
          comment_en: 'filter: keep only elements > 2',
          output: '[3, 4, 5]',
        },
      ],
    },
  },

  {
    id: 'js-async-await',
    term_ru: 'async / await',
    term_en: 'async / await',
    category: 'JS',
    topicSlug: 'js-async-basics',
    definition_ru: 'Синтаксис для удобной работы с асинхронным кодом. async делает функцию асинхронной, await ждёт результата Promise.',
    definition_en: 'Syntax for working with asynchronous code comfortably. async makes a function asynchronous, await waits for a Promise result.',
    whyNeeded_ru: 'Загрузка данных из сети занимает время. async/await позволяет написать асинхронный код так, будто он синхронный — без цепочек .then().',
    whyNeeded_en: 'Loading data from the network takes time. async/await lets you write asynchronous code as if it were synchronous — without .then() chains.',
    commonMistake_ru: 'Использовать await вне async-функции. Это синтаксическая ошибка.',
    commonMistake_en: 'Using await outside an async function. This is a syntax error.',
    example_ru: 'const data = await fetch(url).then(r => r.json())',
    example_en: 'const data = await fetch(url).then(r => r.json())',
    demoMode: 'console',
    demo: {
      steps: [
        {
          code: 'async function getData() {\n  // async: функция возвращает Promise\n}',
          comment_ru: 'Ключевое слово async перед function',
          comment_en: 'The async keyword before function',
          output: '',
        },
        {
          code: 'async function getData() {\n  const res = await fetch("/api/data")\n  const json = await res.json()\n  return json\n}',
          comment_ru: 'await приостанавливает функцию, пока не придёт ответ',
          comment_en: 'await pauses the function until the response arrives',
          output: '',
        },
      ],
    },
  },

  {
    id: 'js-localstorage',
    term_ru: 'localStorage',
    term_en: 'localStorage',
    category: 'JS',
    topicSlug: 'js-localstorage',
    definition_ru: 'Хранилище браузера для данных ключ-значение. Данные сохраняются после закрытия вкладки и перезагрузки страницы.',
    definition_en: 'Browser storage for key-value data. Data persists after closing the tab and reloading the page.',
    whyNeeded_ru: 'Позволяет сохранять настройки, темы, незавершённые формы без сервера. Хранит до ~5 МБ строк.',
    whyNeeded_en: 'Lets you save settings, themes, unfinished forms without a server. Stores up to ~5 MB of strings.',
    commonMistake_ru: 'Хранить объект напрямую. localStorage принимает только строки — нужен JSON.stringify(obj) при записи и JSON.parse() при чтении.',
    commonMistake_en: 'Storing an object directly. localStorage accepts only strings — use JSON.stringify(obj) when writing and JSON.parse() when reading.',
    example_ru: 'localStorage.setItem("theme", "dark")',
    example_en: 'localStorage.setItem("theme", "dark")',
    demoMode: 'console',
    demo: {
      steps: [
        {
          code: 'localStorage.setItem("username", "Иван")',
          comment_ru: 'Сохраняем значение по ключу',
          comment_en: 'Save a value by key',
          output: '',
        },
        {
          code: 'console.log(localStorage.getItem("username"))',
          comment_ru: 'Читаем сохранённое значение',
          comment_en: 'Read the saved value',
          output: 'Иван',
        },
        {
          code: 'localStorage.removeItem("username")',
          comment_ru: 'Удаляем значение',
          comment_en: 'Remove the value',
          output: '',
        },
      ],
    },
  },

  {
    id: 'js-trycatch',
    term_ru: 'try / catch',
    term_en: 'try / catch',
    category: 'JS',
    topicSlug: 'js-errors-debugging',
    definition_ru: 'Конструкция обработки ошибок. Код в блоке try выполняется, а если возникает ошибка — управление передаётся в catch.',
    definition_en: 'Error-handling construct. Code in the try block runs; if an error occurs, control passes to catch.',
    whyNeeded_ru: 'Без try/catch любая ошибка (например, от сети или неверных данных) ломает программу. try/catch позволяет обработать ошибку и продолжить работу.',
    whyNeeded_en: 'Without try/catch any error (e.g. network or bad data) crashes the program. try/catch lets you handle errors and continue.',
    commonMistake_ru: 'Написать catch(e) и ничего не сделать с ошибкой. Так ошибки скрываются и найти баг становится сложно.',
    commonMistake_en: 'Writing catch(e) and doing nothing with the error. This hides errors and makes bugs hard to find.',
    example_ru: 'try { riskCode() } catch (e) { console.error(e) }',
    example_en: 'try { riskCode() } catch (e) { console.error(e) }',
    demoMode: 'console',
    demo: {
      steps: [
        {
          code: 'try {\n  console.log(undeclaredVariable)\n}',
          comment_ru: 'Без catch — программа упадёт с ошибкой',
          comment_en: 'Without catch — the program crashes with an error',
          output: '',
          isError: true,
        },
        {
          code: 'try {\n  console.log(undeclaredVariable)\n} catch (e) {\n  console.log("Ошибка поймана:", e.message)\n}',
          comment_ru: 'С catch — ошибка поймана, программа продолжает работу',
          comment_en: 'With catch — error is caught, program continues',
          output: 'Ошибка поймана: undeclaredVariable is not defined',
        },
      ],
    },
  },

  {
    id: 'js-ternary',
    term_ru: 'Тернарный оператор',
    term_en: 'Ternary operator',
    category: 'JS',
    topicSlug: 'js-conditions',
    definition_ru: 'Краткая запись if/else в одну строку: условие ? значение_если_истина : значение_если_ложь.',
    definition_en: 'A one-line shorthand for if/else: condition ? value_if_true : value_if_false.',
    whyNeeded_ru: 'Удобен для коротких условий внутри строк, JSX-шаблонов и инициализации переменных.',
    whyNeeded_en: 'Handy for short conditions inside strings, JSX templates and variable initialisation.',
    commonMistake_ru: 'Вкладывать тернарные операторы друг в друга. Код становится нечитаемым — лучше использовать if/else.',
    commonMistake_en: 'Nesting ternary operators inside each other. The code becomes unreadable — use if/else instead.',
    example_ru: 'const label = age >= 18 ? "взрослый" : "ребёнок"',
    example_en: 'const label = age >= 18 ? "adult" : "child"',
    demoMode: 'console',
    demo: {
      steps: [
        {
          code: 'const age = 20\nconst label = age >= 18 ? "взрослый" : "ребёнок"\nconsole.log(label)',
          comment_ru: 'age = 20, условие истинно → "взрослый"',
          comment_en: 'age = 20, condition is true → "adult"',
          output: 'взрослый',
        },
        {
          code: 'const age = 12\nconst label = age >= 18 ? "взрослый" : "ребёнок"\nconsole.log(label)',
          comment_ru: 'age = 12, условие ложно → "ребёнок"',
          comment_en: 'age = 12, condition is false → "child"',
          output: 'ребёнок',
        },
      ],
    },
  },
]
