import type { GlossaryTerm } from '@/types/glossary'

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  // HTML
  { term: 'HTML', definition: 'HyperText Markup Language — язык разметки для создания структуры веб-страниц.', category: 'HTML' },
  { term: 'Тег', definition: 'Ключевое слово в угловых скобках, например <p> или <div>. Теги определяют элементы страницы.', category: 'HTML' },
  { term: 'Элемент', definition: 'Открывающий тег + содержимое + закрывающий тег. Например: <p>Текст</p>.', category: 'HTML' },
  { term: 'Атрибут', definition: 'Дополнительная информация внутри тега. Например: href в <a href="..."> или class в <div class="...">.', category: 'HTML' },
  { term: 'DOCTYPE', definition: 'Объявление <!DOCTYPE html> в начале файла, сообщающее браузеру, что это HTML5-документ.', category: 'HTML' },
  { term: 'head', definition: 'Тег <head> содержит метаданные страницы: заголовок, кодировку, подключаемые файлы. Не отображается на странице.', category: 'HTML' },
  { term: 'body', definition: 'Тег <body> содержит всё видимое содержимое страницы.', category: 'HTML' },
  { term: 'семантика', definition: 'Использование тегов по их смыслу: <header> для шапки, <nav> для навигации, <article> для статьи и т.д.', category: 'HTML' },
  { term: 'href', definition: 'Атрибут тега <a>, задающий адрес ссылки. Например: <a href="https://example.com">.', category: 'HTML' },
  { term: 'src', definition: 'Атрибут тегов <img>, <script>, <iframe> — указывает путь к ресурсу.', category: 'HTML' },
  { term: 'alt', definition: 'Атрибут тега <img> — альтернативный текст для изображения (если не загрузилось или для скринридеров).', category: 'HTML' },
  { term: 'форма', definition: 'Элемент <form> позволяет пользователю вводить данные: текст, пароль, флажки, кнопки.', category: 'HTML' },
  { term: 'input', definition: 'Поле ввода. Тип задаётся атрибутом type: text, password, email, checkbox, radio, submit.', category: 'HTML' },
  { term: 'div', definition: 'Блочный контейнер без семантического смысла. Используется для группировки элементов и применения стилей.', category: 'HTML' },
  { term: 'span', definition: 'Строчный контейнер без семантического смысла. Используется для выделения части текста.', category: 'HTML' },

  // CSS
  { term: 'CSS', definition: 'Cascading Style Sheets — язык стилей для оформления HTML-элементов: цвет, шрифт, отступы, расположение.', category: 'CSS' },
  { term: 'селектор', definition: 'Часть CSS-правила, указывающая, к каким элементам применять стили. Например: .card, #main, h1.', category: 'CSS' },
  { term: 'свойство', definition: 'Характеристика, которую изменяет CSS. Например: color, font-size, margin.', category: 'CSS' },
  { term: 'значение', definition: 'То, что присваивается CSS-свойству. Например: red, 16px, bold.', category: 'CSS' },
  { term: 'блочная модель', definition: 'Каждый HTML-элемент — прямоугольник из четырёх слоёв: content (содержимое), padding (внутренний отступ), border (граница), margin (внешний отступ).', category: 'CSS' },
  { term: 'margin', definition: 'Внешний отступ элемента — пространство снаружи border.', category: 'CSS' },
  { term: 'padding', definition: 'Внутренний отступ элемента — пространство между содержимым и border.', category: 'CSS' },
  { term: 'border', definition: 'Граница вокруг элемента. Задаётся как: border: 2px solid black.', category: 'CSS' },
  { term: 'Flexbox', definition: 'Система вёрстки CSS для выравнивания элементов в строку или колонку. Включается через display: flex.', category: 'CSS' },
  { term: 'justify-content', definition: 'CSS-свойство Flexbox для выравнивания элементов по главной оси (по горизонтали по умолчанию).', category: 'CSS' },
  { term: 'align-items', definition: 'CSS-свойство Flexbox для выравнивания элементов по поперечной оси (по вертикали по умолчанию).', category: 'CSS' },
  { term: 'gap', definition: 'Расстояние между flex-элементами или grid-ячейками.', category: 'CSS' },
  { term: 'медиазапрос', definition: '@media — правило CSS для применения стилей в зависимости от ширины экрана. Основа адаптивного дизайна.', category: 'CSS' },
  { term: 'псевдокласс', definition: 'Состояние элемента в CSS. Например: :hover (наведение), :focus (фокус), :first-child.', category: 'CSS' },
  { term: 'специфичность', definition: 'Приоритет CSS-правил. id (#) > class (.) > тег. Чем конкретнее селектор, тем выше приоритет.', category: 'CSS' },
  { term: 'transition', definition: 'Плавная анимация изменения CSS-свойства. Например: transition: color 0.3s.', category: 'CSS' },
  { term: 'position', definition: 'Тип позиционирования элемента: static (обычное), relative, absolute, fixed, sticky.', category: 'CSS' },
  { term: 'z-index', definition: 'Порядок слоёв. Элемент с большим z-index отображается поверх элементов с меньшим.', category: 'CSS' },
  { term: 'box-sizing', definition: 'Определяет, включается ли padding и border в ширину/высоту элемента. Рекомендуется: box-sizing: border-box.', category: 'CSS' },

  // JavaScript
  { term: 'JavaScript', definition: 'Язык программирования для веба. Добавляет интерактивность: анимации, события, работу с данными.', category: 'JavaScript' },
  { term: 'переменная', definition: 'Именованный контейнер для хранения значения. Объявляется через let (изменяемая), const (неизменяемая) или var (устаревший способ).', category: 'JavaScript' },
  { term: 'let', definition: 'Ключевое слово для объявления изменяемой переменной с блочной областью видимости.', category: 'JavaScript' },
  { term: 'const', definition: 'Ключевое слово для объявления неизменяемой переменной (константы). Значение нельзя переприсвоить.', category: 'JavaScript' },
  { term: 'тип данных', definition: 'Вид значения: string (строка), number (число), boolean (true/false), null, undefined, object, array.', category: 'JavaScript' },
  { term: 'функция', definition: 'Именованный блок кода, который можно вызвать повторно. Объявляется через function или стрелочную запись () =>.', category: 'JavaScript' },
  { term: 'стрелочная функция', definition: 'Краткая запись функции: const fn = (x) => x * 2. Не имеет своего this.', category: 'JavaScript' },
  { term: 'параметр', definition: 'Переменная внутри функции, принимающая переданное значение. Например: function greet(name) { }.', category: 'JavaScript' },
  { term: 'аргумент', definition: 'Конкретное значение, передаваемое функции при вызове. Например: greet("Иван").', category: 'JavaScript' },
  { term: 'return', definition: 'Инструкция возврата значения из функции. После return функция прекращает выполнение.', category: 'JavaScript' },
  { term: 'условие', definition: 'Конструкция if/else — выполняет разные блоки кода в зависимости от условия (true или false).', category: 'JavaScript' },
  { term: 'цикл', definition: 'Повторение блока кода. for — фиксированное число раз, while — пока условие истинно.', category: 'JavaScript' },
  { term: 'массив', definition: 'Упорядоченный список значений. Создаётся через []. Индексация с нуля.', category: 'JavaScript' },
  { term: 'объект', definition: 'Коллекция пар ключ-значение. Создаётся через {}. Например: { name: "Иван", age: 10 }.', category: 'JavaScript' },
  { term: 'метод', definition: 'Функция, являющаяся свойством объекта. Например: array.push(), string.toUpperCase().', category: 'JavaScript' },
  { term: 'console.log()', definition: 'Вывод значения в консоль браузера. Используется для отладки.', category: 'JavaScript' },
  { term: 'строковый шаблон', definition: 'Строка с обратными кавычками (``) и выражениями ${...}: `Привет, ${name}!`', category: 'JavaScript' },
  { term: 'область видимости', definition: 'Зона, где переменная доступна. let/const — блочная ({...}), var — функциональная.', category: 'JavaScript' },
  { term: 'hoisting', definition: 'Поднятие объявлений функций и var в начало их области видимости до выполнения кода.', category: 'JavaScript' },
  { term: 'callback', definition: 'Функция, передаваемая как аргумент другой функции и вызываемая позже. Например: arr.forEach(callback).', category: 'JavaScript' },

  // DOM
  { term: 'DOM', definition: 'Document Object Model — дерево объектов, представляющих HTML-страницу в памяти браузера.', category: 'DOM' },
  { term: 'document', definition: 'Глобальный объект JavaScript, представляющий HTML-документ. Точка входа для работы с DOM.', category: 'DOM' },
  { term: 'querySelector()', definition: 'Метод поиска первого HTML-элемента по CSS-селектору.', category: 'DOM' },
  { term: 'getElementById()', definition: 'Метод поиска элемента по значению атрибута id.', category: 'DOM' },
  { term: 'textContent', definition: 'Свойство DOM-элемента для чтения или установки текстового содержимого.', category: 'DOM' },
  { term: 'innerHTML', definition: 'Свойство для установки HTML-содержимого элемента. Использовать осторожно: риск XSS.', category: 'DOM' },
  { term: 'classList', definition: 'Объект для управления CSS-классами элемента: add(), remove(), toggle(), contains().', category: 'DOM' },
  { term: 'addEventListener()', definition: 'Метод привязки обработчика к событию элемента. Например: el.addEventListener("click", fn).', category: 'DOM' },
  { term: 'событие', definition: 'Действие пользователя или браузера: click, mouseover, keydown, input, submit, load.', category: 'DOM' },
  { term: 'createElement()', definition: 'Создаёт новый HTML-элемент в памяти: document.createElement("div").', category: 'DOM' },
  { term: 'appendChild()', definition: 'Добавляет элемент как последнего потомка другого элемента.', category: 'DOM' },
  { term: 'XSS', definition: 'Cross-Site Scripting — атака, при которой злоумышленник внедряет вредоносный код через innerHTML или другие уязвимости.', category: 'DOM' },
]
