import type { GlossaryTerm } from '@/types/glossary'

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  // Основы программирования
  { term: 'Программирование', definition: 'Процесс написания точных инструкций (кода) для компьютера, чтобы он выполнял нужные задачи.', category: 'Основы' },
  { term: 'Алгоритм', definition: 'Чёткая конечная последовательность шагов, решающая определённую задачу. Обладает свойствами конечности, однозначности и результативности.', category: 'Основы' },
  { term: 'Баг', definition: 'Ошибка в программе, из-за которой она работает неправильно или не запускается. Слово появилось в 1947 году, когда нашли реального мотылька в компьютере.', category: 'Основы' },
  { term: 'Дебаггинг', definition: 'Процесс поиска и исправления ошибок (багов) в программе.', category: 'Основы' },
  { term: 'Git', definition: 'Система контроля версий: сохраняет историю изменений проекта и позволяет вернуться к любой предыдущей версии. Команда git commit создаёт точку сохранения.', category: 'Основы' },
  { term: 'GitHub', definition: 'Веб-платформа для хранения Git-репозиториев в облаке и совместной работы над проектами.', category: 'Основы' },
  { term: 'VSCode', definition: 'Visual Studio Code — бесплатный редактор кода с подсветкой синтаксиса, автодополнением и встроенной поддержкой Git. Самый популярный редактор среди веб-разработчиков.', category: 'Основы' },
  { term: 'Репозиторий', definition: 'Папка проекта под управлением Git. Хранит все файлы и их историю изменений.', category: 'Основы' },
  { term: 'Компилятор', definition: 'Программа, переводящая код с языка высокого уровня в машинный код или другой формат, понятный компьютеру.', category: 'Основы' },
  { term: 'Синтаксис', definition: 'Правила написания кода — как грамматика в языке. Нарушение синтаксиса вызывает ошибку и программа не запускается.', category: 'Основы' },

  // HTML
  { term: 'HTML', definition: 'HyperText Markup Language — язык разметки для создания структуры веб-страниц.', category: 'HTML' },
  { term: 'Тег', definition: 'Ключевое слово в угловых скобках, например <p> или <div>. Теги определяют элементы страницы.', category: 'HTML' },
  { term: 'Элемент', definition: 'Открывающий тег + содержимое + закрывающий тег. Например: <p>Текст</p>.', category: 'HTML' },
  { term: 'Атрибут', definition: 'Дополнительная информация внутри тега. Например: href в <a href="..."> или class в <div class="...">.', category: 'HTML' },
  { term: 'DOCTYPE', definition: 'Объявление <!DOCTYPE html> в начале файла, сообщающее браузеру, что это HTML5-документ.', category: 'HTML' },
  { term: 'head', definition: 'Тег <head> содержит метаданные страницы: заголовок, кодировку, подключаемые файлы. Не отображается на странице.', category: 'HTML' },
  { term: 'body', definition: 'Тег <body> содержит всё видимое содержимое страницы.', category: 'HTML' },
  { term: 'семантика', definition: 'Использование тегов по их смыслу: <header> для шапки, <nav> для навигации, <article> для статьи и т.д.', category: 'HTML' },
  { term: 'href', definition: 'Атрибут тега <a>, задающий адрес ссылки. Например: <a href="https://example.com">.', category: 'HTML' },
  { term: 'src', definition: 'Атрибут тегов <img>, <script>, <iframe> — указывает путь к ресурсу.', category: 'HTML' },
  { term: 'alt', definition: 'Атрибут тега <img> — альтернативный текст для изображения (если не загрузилось или для скринридеров).', category: 'HTML' },
  { term: 'форма', definition: 'Элемент <form> позволяет пользователю вводить данные: текст, пароль, флажки, кнопки.', category: 'HTML' },
  { term: 'input', definition: 'Поле ввода. Тип задаётся атрибутом type: text, password, email, checkbox, radio, submit.', category: 'HTML' },
  { term: 'div', definition: 'Блочный контейнер без семантического смысла. Используется для группировки элементов и применения стилей.', category: 'HTML' },
  { term: 'span', definition: 'Строчный контейнер без семантического смысла. Используется для выделения части текста.', category: 'HTML' },
  { term: 'table', definition: 'Тег для создания таблицы. Содержит строки <tr>, которые содержат ячейки <td> или заголовки <th>.', category: 'HTML' },
  { term: 'colspan', definition: 'Атрибут ячейки таблицы, объединяющий несколько столбцов по горизонтали. Например: colspan="2".', category: 'HTML' },
  { term: 'rowspan', definition: 'Атрибут ячейки таблицы, объединяющий несколько строк по вертикали. Например: rowspan="3".', category: 'HTML' },
  { term: 'ul', definition: 'Маркированный (неупорядоченный) список. Каждый пункт — тег <li>. Порядок пунктов не важен.', category: 'HTML' },
  { term: 'ol', definition: 'Нумерованный (упорядоченный) список. Каждый пункт — тег <li>. Используется, когда порядок важен.', category: 'HTML' },
  { term: 'blockquote', definition: 'Тег для оформления длинной цитаты. Визуально выделяется отступом. Атрибут cite указывает источник.', category: 'HTML' },
  { term: 'figure', definition: 'Семантический тег для самостоятельного медиаконтента (изображение, диаграмма, код). Часто используется вместе с <figcaption>.', category: 'HTML' },
  { term: 'figcaption', definition: 'Подпись к содержимому тега <figure>. Располагается внутри <figure> до или после основного контента.', category: 'HTML' },
  { term: 'video', definition: 'Тег для встраивания видеофайла на страницу. Поддерживает атрибуты controls, autoplay, loop, muted.', category: 'HTML' },
  { term: 'audio', definition: 'Тег для встраивания аудиофайла на страницу. Поддерживает атрибуты controls, autoplay, loop.', category: 'HTML' },
  { term: 'label', definition: 'Тег подписи к полю формы. Связывается с input через атрибут for, совпадающий с id поля. Улучшает доступность.', category: 'HTML' },
  { term: 'textarea', definition: 'Многострочное текстовое поле ввода. В отличие от <input>, позволяет вводить несколько строк текста.', category: 'HTML' },
  { term: 'select', definition: 'Выпадающий список для выбора одного или нескольких значений. Содержит пункты <option>.', category: 'HTML' },
  { term: 'void element', definition: 'Самозакрывающийся HTML-элемент без содержимого и закрывающего тега. Например: <img>, <input>, <br>, <hr>.', category: 'HTML' },
  { term: 'target', definition: 'Атрибут тега <a>, определяющий, где открыть ссылку. _blank — новая вкладка, _self — текущая (по умолчанию).', category: 'HTML' },

  // CSS
  { term: 'CSS', definition: 'Cascading Style Sheets — язык стилей для оформления HTML-элементов: цвет, шрифт, отступы, расположение.', category: 'CSS' },
  { term: 'селектор', definition: 'Часть CSS-правила, указывающая, к каким элементам применять стили. Например: .card, #main, h1.', category: 'CSS' },
  { term: 'свойство', definition: 'Характеристика, которую изменяет CSS. Например: color, font-size, margin.', category: 'CSS' },
  { term: 'значение', definition: 'То, что присваивается CSS-свойству. Например: red, 16px, bold.', category: 'CSS' },
  { term: 'блочная модель', definition: 'Каждый HTML-элемент — прямоугольник из четырёх слоёв: content (содержимое), padding (внутренний отступ), border (граница), margin (внешний отступ).', category: 'CSS' },
  { term: 'margin', definition: 'Внешний отступ элемента — пространство снаружи border.', category: 'CSS' },
  { term: 'padding', definition: 'Внутренний отступ элемента — пространство между содержимым и border.', category: 'CSS' },
  { term: 'border', definition: 'Граница вокруг элемента. Задаётся как: border: 2px solid black.', category: 'CSS' },
  { term: 'Flexbox', definition: 'Система вёрстки CSS для выравнивания элементов в строку или колонку. Включается через display: flex.', category: 'CSS' },
  { term: 'justify-content', definition: 'CSS-свойство Flexbox для выравнивания элементов по главной оси (по горизонтали по умолчанию).', category: 'CSS' },
  { term: 'align-items', definition: 'CSS-свойство Flexbox для выравнивания элементов по поперечной оси (по вертикали по умолчанию).', category: 'CSS' },
  { term: 'gap', definition: 'Расстояние между flex-элементами или grid-ячейками.', category: 'CSS' },
  { term: 'медиазапрос', definition: '@media — правило CSS для применения стилей в зависимости от ширины экрана. Основа адаптивного дизайна.', category: 'CSS' },
  { term: 'псевдокласс', definition: 'Состояние элемента в CSS. Например: :hover (наведение), :focus (фокус), :first-child.', category: 'CSS' },
  { term: 'специфичность', definition: 'Приоритет CSS-правил. id (#) > class (.) > тег. Чем конкретнее селектор, тем выше приоритет.', category: 'CSS' },
  { term: 'transition', definition: 'Плавная анимация изменения CSS-свойства. Например: transition: color 0.3s.', category: 'CSS' },
  { term: 'position', definition: 'Тип позиционирования элемента: static (обычное), relative, absolute, fixed, sticky.', category: 'CSS' },
  { term: 'z-index', definition: 'Порядок слоёв. Элемент с большим z-index отображается поверх элементов с меньшим.', category: 'CSS' },
  { term: 'box-sizing', definition: 'Определяет, включается ли padding и border в ширину/высоту элемента. Рекомендуется: box-sizing: border-box.', category: 'CSS' },
  { term: 'CSS Grid', definition: 'Двумерная система раскладки CSS. Включается через display: grid. Позволяет задавать строки и колонки одновременно.', category: 'CSS' },
  { term: 'grid-template-columns', definition: 'CSS-свойство, задающее количество и ширину колонок в Grid-контейнере. Например: grid-template-columns: 1fr 2fr 1fr.', category: 'CSS' },
  { term: 'fr', definition: 'Единица измерения в CSS Grid, означающая долю свободного пространства. 1fr = одна часть, 2fr = две части.', category: 'CSS' },
  { term: 'auto-fill', definition: 'Значение в grid-template-columns, автоматически создающее максимально возможное количество колонок заданного размера.', category: 'CSS' },
  { term: 'rem', definition: 'Единица размера CSS относительно корневого размера шрифта (html). 1rem = 16px по умолчанию. Удобна для масштабирования.', category: 'CSS' },
  { term: 'em', definition: 'Единица размера CSS относительно размера шрифта родительского элемента. 2em = вдвое больше шрифта родителя.', category: 'CSS' },
  { term: 'vw', definition: 'Viewport Width — 1% ширины окна браузера. 100vw = полная ширина экрана.', category: 'CSS' },
  { term: 'vh', definition: 'Viewport Height — 1% высоты окна браузера. 100vh = полная высота экрана.', category: 'CSS' },
  { term: 'CSS-переменная', definition: 'Пользовательское CSS-свойство, объявляемое как --название: значение. Используется через var(--название). Удобно для тем.', category: 'CSS' },
  { term: 'transform', definition: 'CSS-свойство для геометрических преобразований: rotate (поворот), scale (масштаб), translate (сдвиг), skew (наклон).', category: 'CSS' },
  { term: 'animation', definition: 'CSS-свойство для создания анимаций с ключевыми кадрами (@keyframes). Задаёт имя, длительность, повторение.', category: 'CSS' },
  { term: 'opacity', definition: 'Прозрачность элемента от 0 (полностью прозрачный) до 1 (полностью непрозрачный). Влияет на весь элемент включая детей.', category: 'CSS' },
  { term: 'display', definition: 'Определяет тип отображения элемента: block, inline, flex, grid, none (скрыт). Одно из важнейших CSS-свойств.', category: 'CSS' },
  { term: 'overflow', definition: 'Поведение при переполнении содержимым: visible (виден), hidden (обрезан), scroll (прокрутка), auto (прокрутка при нужде).', category: 'CSS' },
  { term: 'border-radius', definition: 'Закругление углов элемента. Например: border-radius: 8px — скруглённые углы, border-radius: 50% — круг.', category: 'CSS' },
  { term: 'HEX', definition: 'Шестнадцатеричный формат записи цвета. Например: #FF5733. Первые два символа — красный, следующие — зелёный, последние — синий.', category: 'CSS' },
  { term: 'HSL', definition: 'Формат цвета: Hue (оттенок 0-360°), Saturation (насыщенность 0-100%), Lightness (светлота 0-100%). Пример: hsl(0, 100%, 50%) = красный.', category: 'CSS' },
  { term: 'flex-wrap', definition: 'CSS-свойство Flexbox для переноса элементов на новую строку, если они не помещаются. Значение: wrap — переносить, nowrap — не переносить.', category: 'CSS' },

  // JavaScript
  { term: 'JavaScript', definition: 'Язык программирования для веба. Добавляет интерактивность: анимации, события, работу с данными.', category: 'JavaScript' },
  { term: 'переменная', definition: 'Именованный контейнер для хранения значения. Объявляется через let (изменяемая), const (неизменяемая) или var (устаревший способ).', category: 'JavaScript' },
  { term: 'let', definition: 'Ключевое слово для объявления изменяемой переменной с блочной областью видимости.', category: 'JavaScript' },
  { term: 'const', definition: 'Ключевое слово для объявления неизменяемой переменной (константы). Значение нельзя переприсвоить.', category: 'JavaScript' },
  { term: 'тип данных', definition: 'Вид значения: string (строка), number (число), boolean (true/false), null, undefined, object, array.', category: 'JavaScript' },
  { term: 'функция', definition: 'Именованный блок кода, который можно вызвать повторно. Объявляется через function или стрелочную запись () =>.', category: 'JavaScript' },
  { term: 'стрелочная функция', definition: 'Краткая запись функции: const fn = (x) => x * 2. Не имеет своего this.', category: 'JavaScript' },
  { term: 'параметр', definition: 'Переменная внутри функции, принимающая переданное значение. Например: function greet(name) { }.', category: 'JavaScript' },
  { term: 'аргумент', definition: 'Конкретное значение, передаваемое функции при вызове. Например: greet("Иван").', category: 'JavaScript' },
  { term: 'return', definition: 'Инструкция возврата значения из функции. После return функция прекращает выполнение.', category: 'JavaScript' },
  { term: 'условие', definition: 'Конструкция if/else — выполняет разные блоки кода в зависимости от условия (true или false).', category: 'JavaScript' },
  { term: 'цикл', definition: 'Повторение блока кода. for — фиксированное число раз, while — пока условие истинно.', category: 'JavaScript' },
  { term: 'массив', definition: 'Упорядоченный список значений. Создаётся через []. Индексация с нуля.', category: 'JavaScript' },
  { term: 'объект', definition: 'Коллекция пар ключ-значение. Создаётся через {}. Например: { name: "Иван", age: 10 }.', category: 'JavaScript' },
  { term: 'метод', definition: 'Функция, являющаяся свойством объекта. Например: array.push(), string.toUpperCase().', category: 'JavaScript' },
  { term: 'console.log()', definition: 'Вывод значения в консоль браузера. Используется для отладки.', category: 'JavaScript' },
  { term: 'строковый шаблон', definition: 'Строка с обратными кавычками (``) и выражениями ${...}: `Привет, ${name}!`', category: 'JavaScript' },
  { term: 'область видимости', definition: 'Зона, где переменная доступна. let/const — блочная ({...}), var — функциональная.', category: 'JavaScript' },
  { term: 'hoisting', definition: 'Поднятие объявлений функций и var в начало их области видимости до выполнения кода.', category: 'JavaScript' },
  { term: 'callback', definition: 'Функция, передаваемая как аргумент другой функции и вызываемая позже. Например: arr.forEach(callback).', category: 'JavaScript' },
  { term: '=== (строгое равенство)', definition: 'Оператор сравнения, проверяющий равенство значения И типа. 5 === "5" → false. В отличие от ==, не приводит типы.', category: 'JavaScript' },
  { term: 'тернарный оператор', definition: 'Краткая запись if/else: условие ? значение_если_истина : значение_если_ложь. Например: age >= 18 ? "взрослый" : "ребёнок".', category: 'JavaScript' },
  { term: 'for..of', definition: 'Цикл для перебора итерируемых объектов (массивов, строк). Например: for (const item of array) { }.', category: 'JavaScript' },
  { term: 'break', definition: 'Оператор, немедленно прерывающий выполнение цикла или switch.', category: 'JavaScript' },
  { term: 'continue', definition: 'Оператор, пропускающий текущую итерацию цикла и переходящий к следующей.', category: 'JavaScript' },
  { term: 'map()', definition: 'Метод массива, создающий новый массив путём применения функции к каждому элементу. Например: [1,2,3].map(x => x * 2) → [2,4,6].', category: 'JavaScript' },
  { term: 'filter()', definition: 'Метод массива, создающий новый массив из элементов, прошедших проверку функцией. Например: arr.filter(x => x > 0).', category: 'JavaScript' },
  { term: 'reduce()', definition: 'Метод массива, сворачивающий все элементы в одно значение. Например: [1,2,3].reduce((sum, x) => sum + x, 0) → 6.', category: 'JavaScript' },
  { term: 'find()', definition: 'Метод массива, возвращающий первый элемент, удовлетворяющий условию. Возвращает undefined, если ничего не найдено.', category: 'JavaScript' },
  { term: 'спред-оператор', definition: 'Оператор ... для разворачивания массива или объекта. Например: [...arr1, ...arr2] — объединение массивов.', category: 'JavaScript' },
  { term: 'деструктуризация', definition: 'Синтаксис извлечения значений из массивов или объектов в переменные. Например: const { name, age } = user.', category: 'JavaScript' },
  { term: 'Promise', definition: 'Объект для работы с асинхронными операциями. Находится в одном из состояний: pending (ожидание), fulfilled (выполнено), rejected (ошибка).', category: 'JavaScript' },
  { term: 'async/await', definition: 'Синтаксис для удобной работы с промисами. async делает функцию асинхронной, await ждёт результата промиса.', category: 'JavaScript' },
  { term: 'fetch()', definition: 'Встроенная функция для выполнения HTTP-запросов. Возвращает Promise. Пример: const data = await fetch(url).then(r => r.json()).', category: 'JavaScript' },
  { term: 'try/catch', definition: 'Конструкция обработки ошибок. Код в try выполняется, а если возникает ошибка — управление передаётся в catch.', category: 'JavaScript' },
  { term: 'typeof', definition: 'Оператор, возвращающий строку с типом значения: "string", "number", "boolean", "object", "undefined", "function".', category: 'JavaScript' },
  { term: 'localStorage', definition: 'Хранилище браузера для данных в формате ключ-значение. Данные сохраняются после закрытия вкладки. Методы: setItem, getItem, removeItem.', category: 'JavaScript' },
  { term: 'JSON', definition: 'JavaScript Object Notation — текстовый формат данных. JSON.stringify() переводит объект в строку, JSON.parse() — строку в объект.', category: 'JavaScript' },
  { term: 'NaN', definition: 'Not a Number — специальное значение, возникающее при некорректной математической операции. Например: "текст" / 2 → NaN.', category: 'JavaScript' },

  // DOM
  { term: 'DOM', definition: 'Document Object Model — дерево объектов, представляющих HTML-страницу в памяти браузера.', category: 'DOM' },
  { term: 'document', definition: 'Глобальный объект JavaScript, представляющий HTML-документ. Точка входа для работы с DOM.', category: 'DOM' },
  { term: 'querySelector()', definition: 'Метод поиска первого HTML-элемента по CSS-селектору.', category: 'DOM' },
  { term: 'getElementById()', definition: 'Метод поиска элемента по значению атрибута id.', category: 'DOM' },
  { term: 'textContent', definition: 'Свойство DOM-элемента для чтения или установки текстового содержимого.', category: 'DOM' },
  { term: 'innerHTML', definition: 'Свойство для установки HTML-содержимого элемента. Использовать осторожно: риск XSS.', category: 'DOM' },
  { term: 'classList', definition: 'Объект для управления CSS-классами элемента: add(), remove(), toggle(), contains().', category: 'DOM' },
  { term: 'addEventListener()', definition: 'Метод привязки обработчика к событию элемента. Например: el.addEventListener("click", fn).', category: 'DOM' },
  { term: 'событие', definition: 'Действие пользователя или браузера: click, mouseover, keydown, input, submit, load.', category: 'DOM' },
  { term: 'createElement()', definition: 'Создаёт новый HTML-элемент в памяти: document.createElement("div").', category: 'DOM' },
  { term: 'appendChild()', definition: 'Добавляет элемент как последнего потомка другого элемента.', category: 'DOM' },
  { term: 'XSS', definition: 'Cross-Site Scripting — атака, при которой злоумышленник внедряет вредоносный код через innerHTML или другие уязвимости.', category: 'DOM' },

  // React
  { term: 'React', definition: 'JavaScript-библиотека для создания пользовательских интерфейсов через компонентный подход. Создана в Facebook в 2013 году.', category: 'React' },
  { term: 'Компонент React', definition: 'Функция, возвращающая JSX. Строительный блок React-приложения. Имя начинается с заглавной буквы.', category: 'React' },
  { term: 'JSX', definition: 'Синтаксическое расширение JavaScript для написания HTML-подобного кода в JS-файлах. Компилируется Babel в React.createElement().', category: 'React' },
  { term: 'Props', definition: 'Данные, передаваемые от родительского компонента к дочернему. Только для чтения — дочерний компонент не может их изменить.', category: 'React' },
  { term: 'State', definition: 'Внутреннее состояние компонента. При изменении state React автоматически перерисовывает компонент.', category: 'React' },
  { term: 'useState', definition: 'React Hook для создания реактивного состояния. Возвращает [значение, функцию_обновления].', category: 'React' },
  { term: 'useEffect', definition: 'React Hook для выполнения побочных эффектов: запросов к API, таймеров, подписок. Выполняется после рендера.', category: 'React' },
  { term: 'Virtual DOM', definition: 'Копия DOM в памяти JavaScript. React сравнивает старый и новый Virtual DOM и обновляет в реальном DOM только изменившиеся части.', category: 'React' },
  { term: 'Hook', definition: 'Функция React, имя которой начинается с use. Позволяет использовать state и другие возможности React в функциональных компонентах.', category: 'React' },
  { term: 'key', definition: 'Специальный атрибут React для элементов списка. Помогает React отслеживать, какие элементы изменились, добавились или удалились.', category: 'React' },
  { term: 'Ре-рендер', definition: 'Повторное выполнение функции компонента и обновление DOM при изменении state или props.', category: 'React' },
  { term: 'Условный рендеринг', definition: 'Отображение разного JSX в зависимости от условия. Используются &&, тернарный оператор или if/else перед return.', category: 'React' },
  { term: 'Контролируемый компонент', definition: 'Поле формы, значение которого управляется через state. onChange обновляет state, value={state} отображает текущее значение.', category: 'React' },
  { term: 'ReactDOM', definition: 'Пакет для рендеринга React-компонентов в реальный DOM браузера. ReactDOM.createRoot(el).render(<App />)', category: 'React' },
  { term: 'Fragment', definition: 'Пустой контейнер <> </> или <React.Fragment> для группировки элементов без лишнего DOM-узла.', category: 'React' },
]
